
INSERT OR REPLACE INTO word_frequencies (
  pashto_word, frequency_total, frequency_afghan2023_ot, frequency_afghan2023_nt,
  frequency_yousafzai2019_ot, frequency_yousafzai2019_nt, frequency_rank,
  base_form, word_type, pos, inflection_type, compound_type,
  romanization, dictionary_id, english_translation, has_issues, issue_flags,
  created_at, updated_at
) VALUES
(
        'خليل',
        2,
        0,
        0,
        1,
        1,
        29001,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'راوګرځې',
        2,
        0,
        0,
        1,
        1,
        29002,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'راګرځېدلى.',
        2,
        0,
        0,
        2,
        0,
        29003,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ساتلو په',
        2,
        0,
        0,
        1,
        1,
        29004,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مَلِکه په',
        2,
        0,
        0,
        2,
        0,
        29005,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'چُهټى',
        2,
        0,
        0,
        2,
        0,
        29006,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'چهټى',
        2,
        0,
        0,
        2,
        0,
        29007,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'راننوتل',
        2,
        0,
        0,
        1,
        1,
        29008,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'خوشحالېدو.',
        2,
        0,
        0,
        2,
        0,
        29009,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بچى دې',
        2,
        0,
        0,
        1,
        1,
        29010,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'رايوځائ کړل',
        2,
        0,
        0,
        1,
        1,
        29011,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'جوړوله.',
        2,
        0,
        0,
        2,
        0,
        29012,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'خوشحالېدو،',
        2,
        0,
        0,
        2,
        0,
        29013,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'کارونه،',
        2,
        0,
        0,
        2,
        0,
        29014,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مسلموت',
        2,
        0,
        0,
        2,
        0,
        29015,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'شپاړسمه',
        2,
        0,
        0,
        2,
        0,
        29016,
        'شپاړسم',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حلالولے،',
        2,
        0,
        0,
        2,
        0,
        29017,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'جذبې',
        2,
        0,
        0,
        1,
        1,
        29018,
        'جذبه',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مينامين،',
        2,
        0,
        0,
        2,
        0,
        29019,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حزقياه دې',
        2,
        0,
        0,
        2,
        0,
        29020,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'عمارت په',
        2,
        0,
        0,
        2,
        0,
        29021,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مسلام.',
        2,
        0,
        0,
        2,
        0,
        29022,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'وموندلو،',
        2,
        0,
        0,
        1,
        1,
        29023,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ومنلې',
        2,
        0,
        0,
        2,
        0,
        29024,
        'منل',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'پَتيلو',
        2,
        0,
        0,
        1,
        1,
        29025,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'شوے. په',
        2,
        0,
        0,
        1,
        1,
        29026,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ښوونکى',
        2,
        0,
        0,
        1,
        1,
        29027,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'توښه،',
        2,
        0,
        0,
        2,
        0,
        29028,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مِتردات',
        2,
        0,
        0,
        2,
        0,
        29029,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'نحمياه،',
        2,
        0,
        0,
        2,
        0,
        29030,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مردکى،',
        2,
        0,
        0,
        2,
        0,
        29031,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بِلشان،',
        2,
        0,
        0,
        2,
        0,
        29032,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بِګوئ،',
        2,
        0,
        0,
        2,
        0,
        29033,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'طابئيل',
        2,
        0,
        0,
        2,
        0,
        29034,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'رحُوم،',
        2,
        0,
        0,
        2,
        0,
        29035,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'محصُول،',
        2,
        0,
        0,
        2,
        0,
        29036,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'جزيه',
        2,
        0,
        0,
        2,
        0,
        29037,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'تتنى،',
        2,
        0,
        0,
        2,
        0,
        29038,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حُکم دې',
        2,
        0,
        0,
        1,
        1,
        29039,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ومنلے',
        2,
        0,
        0,
        1,
        1,
        29040,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مطابق.',
        2,
        0,
        0,
        1,
        1,
        29041,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'څوکيدارانو،',
        2,
        0,
        0,
        2,
        0,
        29042,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ضبط',
        2,
        0,
        0,
        2,
        0,
        29043,
        NULL,
        'noun',
        'n. m.',
        NULL,
        NULL,
        'zabt',
        1527818898,
        'seizure, confiscation, control, restraint, discipline, self-control, recording, record',
        0,
        '[]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'نوعيدياه',
        2,
        0,
        0,
        2,
        0,
        29044,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'وېښتۀ مې',
        2,
        0,
        0,
        2,
        0,
        29045,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'قېديانو په',
        2,
        0,
        0,
        2,
        0,
        29046,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ګڼې په',
        2,
        0,
        0,
        1,
        1,
        29047,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'سبتى',
        2,
        0,
        0,
        2,
        0,
        29048,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حارِم',
        2,
        0,
        0,
        2,
        0,
        29049,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'فتحياه،',
        2,
        0,
        0,
        2,
        0,
        29050,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'څوکيداران:',
        2,
        0,
        0,
        2,
        0,
        29051,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'يهوحنان،',
        2,
        0,
        0,
        2,
        0,
        29052,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'پخت',
        2,
        0,
        0,
        2,
        0,
        29053,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'متتاه،',
        2,
        0,
        0,
        1,
        1,
        29054,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حکلياه',
        2,
        0,
        0,
        2,
        0,
        29055,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'نحمياه په',
        2,
        0,
        0,
        2,
        0,
        29056,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'خوراک مې',
        2,
        0,
        0,
        2,
        0,
        29057,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بدعملې',
        2,
        0,
        0,
        2,
        0,
        29058,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مينارو',
        2,
        0,
        0,
        2,
        0,
        29059,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ميناره',
        2,
        0,
        0,
        2,
        0,
        29060,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'هقوض',
        2,
        0,
        0,
        2,
        0,
        29061,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مشيزب‌ايل',
        2,
        0,
        0,
        2,
        0,
        29062,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ټېکدارانو',
        2,
        0,
        0,
        2,
        0,
        29063,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'جوړوونکى',
        2,
        0,
        0,
        2,
        0,
        29064,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'کولحوزه',
        2,
        0,
        0,
        2,
        0,
        29065,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ګورو',
        2,
        0,
        0,
        1,
        1,
        29066,
        'ګور',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'کسانو به',
        2,
        0,
        0,
        2,
        0,
        29067,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ويستلې،',
        2,
        0,
        0,
        2,
        0,
        29068,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'وڅنډله',
        2,
        0,
        0,
        1,
        1,
        29069,
        'څنډل',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'دفتر',
        2,
        0,
        0,
        2,
        0,
        29070,
        NULL,
        'noun',
        'n. m.',
        NULL,
        NULL,
        'daftár',
        1527811285,
        'office, bureau; book, journal, ledger; hereditary land',
        0,
        '[]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'رالېږل.',
        2,
        0,
        0,
        2,
        0,
        29071,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'څوکيداران،',
        2,
        0,
        0,
        2,
        0,
        29072,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'اعتمادى',
        2,
        0,
        0,
        2,
        0,
        29073,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'هودياه،',
        2,
        0,
        0,
        2,
        0,
        29074,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'نختر،',
        2,
        0,
        0,
        2,
        0,
        29075,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بادشاهو',
        2,
        0,
        0,
        2,
        0,
        29076,
        'بادشاه',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بِنوئى،',
        2,
        0,
        0,
        2,
        0,
        29077,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بقبوقياه،',
        2,
        0,
        0,
        2,
        0,
        29078,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'يدوع',
        2,
        0,
        0,
        2,
        0,
        29079,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'موسيقار',
        2,
        0,
        0,
        2,
        0,
        29080,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'نمائش',
        2,
        0,
        0,
        1,
        1,
        29081,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'وشتى ته',
        2,
        0,
        0,
        2,
        0,
        29082,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        '”ما،',
        2,
        0,
        0,
        2,
        0,
        29083,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'حقدارې',
        2,
        0,
        0,
        1,
        1,
        29084,
        'حقدار',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'وشتى په',
        2,
        0,
        0,
        2,
        0,
        29085,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'راګرځېدو',
        2,
        0,
        0,
        2,
        0,
        29086,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مالش',
        2,
        0,
        0,
        2,
        0,
        29087,
        NULL,
        'noun',
        'n. m.',
        NULL,
        NULL,
        'maalísh',
        1527821845,
        'friction, rubbing, massage, filling',
        0,
        '[]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'چُهټۍ',
        2,
        0,
        0,
        2,
        0,
        29088,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'مردکى ورته',
        2,
        0,
        0,
        2,
        0,
        29089,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'بِګتان',
        2,
        0,
        0,
        2,
        0,
        29090,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ترش،',
        2,
        0,
        0,
        2,
        0,
        29091,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'منشيان',
        2,
        0,
        0,
        2,
        0,
        29092,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'رسونکو',
        2,
        0,
        0,
        2,
        0,
        29093,
        'رسېدل',
        'unknown',
        NULL,
        'inflected',
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'يوړو. په',
        2,
        0,
        0,
        2,
        0,
        29094,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ونيسو.',
        2,
        0,
        0,
        1,
        1,
        29095,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'ولوستله',
        2,
        0,
        0,
        1,
        1,
        29096,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'شوى.“',
        2,
        0,
        0,
        1,
        1,
        29097,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        '”همان',
        2,
        0,
        0,
        2,
        0,
        29098,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        '”همان په',
        2,
        0,
        0,
        2,
        0,
        29099,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      ),
(
        'درناوے کول',
        2,
        0,
        0,
        2,
        0,
        29100,
        NULL,
        'unknown',
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        1,
        '["no_dictionary_match","no_pos"]',
        strftime('%s', 'now'),
        strftime('%s', 'now')
      );
