
INSERT OR IGNORE INTO word_verse_mapping 
  (pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse, word_position, created_at)
VALUES
(
            'پرېږدم،',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            21,
            strftime('%s', 'now')
          ),
(
            'ترڅو',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            23,
            strftime('%s', 'now')
          ),
(
            'پورې',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            24,
            strftime('%s', 'now')
          ),
(
            'دې',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            25,
            strftime('%s', 'now')
          ),
(
            'له',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            27,
            strftime('%s', 'now')
          ),
(
            'برکت',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            28,
            strftime('%s', 'now')
          ),
(
            'وى',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            30,
            strftime('%s', 'now')
          ),
(
            'راکړے',
            936,
            'Genesis 32:26',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            26,
            31,
            strftime('%s', 'now')
          ),
(
            'هغه',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            0,
            strftime('%s', 'now')
          ),
(
            'سړى',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            1,
            strftime('%s', 'now')
          ),
(
            'ترې',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            2,
            strftime('%s', 'now')
          ),
(
            'تپوس',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            3,
            strftime('%s', 'now')
          ),
(
            'وکړو،',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            4,
            strftime('%s', 'now')
          ),
(
            'ستا',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            5,
            strftime('%s', 'now')
          ),
(
            'څۀ',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            6,
            strftime('%s', 'now')
          ),
(
            'نوم',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            7,
            strftime('%s', 'now')
          ),
(
            'دے؟',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            8,
            strftime('%s', 'now')
          ),
(
            'نو',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            9,
            strftime('%s', 'now')
          ),
(
            'هغۀ',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            10,
            strftime('%s', 'now')
          ),
(
            'ورته',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            11,
            strftime('%s', 'now')
          ),
(
            'ووئيل،',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            12,
            strftime('%s', 'now')
          ),
(
            'يعقوب',
            937,
            'Genesis 32:27',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            27,
            13,
            strftime('%s', 'now')
          ),
(
            'هغه',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            0,
            strftime('%s', 'now')
          ),
(
            'سړى',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            1,
            strftime('%s', 'now')
          ),
(
            'ورته',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            2,
            strftime('%s', 'now')
          ),
(
            'ووئيل،',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            3,
            strftime('%s', 'now')
          ),
(
            'د',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            4,
            strftime('%s', 'now')
          ),
(
            'نن',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            5,
            strftime('%s', 'now')
          ),
(
            'نه',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            6,
            strftime('%s', 'now')
          ),
(
            'پس',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            7,
            strftime('%s', 'now')
          ),
(
            'به',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            8,
            strftime('%s', 'now')
          ),
(
            'ستا',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            9,
            strftime('%s', 'now')
          ),
(
            'نوم',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            10,
            strftime('%s', 'now')
          ),
(
            'يعقوب',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            11,
            strftime('%s', 'now')
          ),
(
            'نۀ',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            12,
            strftime('%s', 'now')
          ),
(
            'وى',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            13,
            strftime('%s', 'now')
          ),
(
            'تا',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            14,
            strftime('%s', 'now')
          ),
(
            'خُدائ',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            16,
            strftime('%s', 'now')
          ),
(
            'پاک',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            17,
            strftime('%s', 'now')
          ),
(
            'او',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            18,
            strftime('%s', 'now')
          ),
(
            'انسان',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            20,
            strftime('%s', 'now')
          ),
(
            'سره',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            21,
            strftime('%s', 'now')
          ),
(
            'مقابله',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            22,
            strftime('%s', 'now')
          ),
(
            'کړې',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            23,
            strftime('%s', 'now')
          ),
(
            'ده',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            24,
            strftime('%s', 'now')
          ),
(
            'ګټلې',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            27,
            strftime('%s', 'now')
          ),
(
            'ده،',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            28,
            strftime('%s', 'now')
          ),
(
            'اوس',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            30,
            strftime('%s', 'now')
          ),
(
            'اِسرائيل',
            938,
            'Genesis 32:28',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            28,
            35,
            strftime('%s', 'now')
          ),
(
            'يعقوب',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            0,
            strftime('%s', 'now')
          ),
(
            'ورته',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            1,
            strftime('%s', 'now')
          ),
(
            'وفرمائيل،',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            2,
            strftime('%s', 'now')
          ),
(
            'اوس',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            3,
            strftime('%s', 'now')
          ),
(
            'تۀ',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            4,
            strftime('%s', 'now')
          ),
(
            'ما',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            5,
            strftime('%s', 'now')
          ),
(
            'ته',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            6,
            strftime('%s', 'now')
          ),
(
            'خپل',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            7,
            strftime('%s', 'now')
          ),
(
            'نوم',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            8,
            strftime('%s', 'now')
          ),
(
            'وښايه',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            9,
            strftime('%s', 'now')
          ),
(
            'خو',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            10,
            strftime('%s', 'now')
          ),
(
            'هغۀ',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            11,
            strftime('%s', 'now')
          ),
(
            'ووئيل،',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            13,
            strftime('%s', 'now')
          ),
(
            'ولې',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            15,
            strftime('%s', 'now')
          ),
(
            'زما',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            16,
            strftime('%s', 'now')
          ),
(
            'د',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            17,
            strftime('%s', 'now')
          ),
(
            'تپوس',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            19,
            strftime('%s', 'now')
          ),
(
            'کوې؟',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            20,
            strftime('%s', 'now')
          ),
(
            'بيا',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            21,
            strftime('%s', 'now')
          ),
(
            'له',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            24,
            strftime('%s', 'now')
          ),
(
            'برکت',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            25,
            strftime('%s', 'now')
          ),
(
            'ورکړو',
            939,
            'Genesis 32:29',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            29,
            26,
            strftime('%s', 'now')
          ),
(
            'يعقوب',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            0,
            strftime('%s', 'now')
          ),
(
            'ووئيل،',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            1,
            strftime('%s', 'now')
          ),
(
            'ما',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            2,
            strftime('%s', 'now')
          ),
(
            'خُدائ',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            3,
            strftime('%s', 'now')
          ),
(
            'پاک',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            4,
            strftime('%s', 'now')
          ),
(
            'مخامخ',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            5,
            strftime('%s', 'now')
          ),
(
            'ليدلے',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            6,
            strftime('%s', 'now')
          ),
(
            'دے',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            7,
            strftime('%s', 'now')
          ),
(
            'او',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            8,
            strftime('%s', 'now')
          ),
(
            'بيا',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            9,
            strftime('%s', 'now')
          ),
(
            'هم',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            10,
            strftime('%s', 'now')
          ),
(
            'لا',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            11,
            strftime('%s', 'now')
          ),
(
            'ژوندے',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            12,
            strftime('%s', 'now')
          ),
(
            'پاتې',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            13,
            strftime('%s', 'now')
          ),
(
            'يم',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            14,
            strftime('%s', 'now')
          ),
(
            'نو',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            15,
            strftime('%s', 'now')
          ),
(
            'په',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            16,
            strftime('%s', 'now')
          ),
(
            'هغه',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            17,
            strftime('%s', 'now')
          ),
(
            'ځائ',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            18,
            strftime('%s', 'now')
          ),
(
            'يې',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            19,
            strftime('%s', 'now')
          ),
(
            'فنواېل',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            20,
            strftime('%s', 'now')
          ),
(
            'نوم',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            21,
            strftime('%s', 'now')
          ),
(
            'کېښودو',
            940,
            'Genesis 32:30',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            30,
            22,
            strftime('%s', 'now')
          ),
(
            'نمر',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            0,
            strftime('%s', 'now')
          ),
(
            'راختلو',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            1,
            strftime('%s', 'now')
          ),
(
            'چې',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            2,
            strftime('%s', 'now')
          ),
(
            'يعقوب',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            3,
            strftime('%s', 'now')
          ),
(
            'د',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            4,
            strftime('%s', 'now')
          ),
(
            'فنواېل',
            941,
            'Genesis 32:31',
            'yousafzai2019',
            'OT',
            'Genesis',
            32,
            31,
            5,
            strftime('%s', 'now')
          );
