
-- Create unified frequency table
CREATE TABLE IF NOT EXISTS public.word_frequencies_unified (
  id bigserial PRIMARY KEY,
  pashto_word text NOT NULL,
  total_frequency integer NOT NULL,
  ot_frequency integer DEFAULT 0,
  nt_frequency integer DEFAULT 0,
  romanization text,
  pos text,
  english_translation text,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);
INSERT INTO public.word_frequencies_unified (pashto_word, total_frequency, ot_frequency, nt_frequency, romanization, pos, english_translation, metadata)
VALUES
('واغوندو', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کینو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جنګونه', 1, 1, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شخړې', 1, 0, 4, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('راوړلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کبرجنو', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('درنژدې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وګټو.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('بخار', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورکیږی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وسوځی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کولی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('دلیله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ولړزېدل', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('تاسو!»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('برابرۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نشتون', 1, 0, 2, 'nashtóon', 'n.m.', 'lack', '{"english": "lack", "pos": "n.m.", "romanization": "nasht\u00f3on", "r": 4, "a": 2, "i": 17098, "ts": 1586451106776}'),
('معصوم', 1, 0, 0, 'ma''sóom', 'adj.', 'innocent', '{"english": "innocent", "pos": "adj.", "romanization": "ma''s\u00f3om", "r": 3, "a": 3, "i": 15947, "ts": 1527817601}'),
('ویاړم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ګټو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نېزې', 1, 4, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خدای.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('موعظې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پاتموس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سینې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('صیقل', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پرېوتلم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وروخوت»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('کوز', 1, 0, 0, 'kooz', 'loc.adv./ adj.', 'lower, below, down', '{"english": "lower, below, down", "pos": "loc.adv./ adj.", "romanization": "kooz", "r": 3, "a": 3, "i": 13518, "ts": 1527813688}'),
('راکوز', 1, 0, 0, 'raakóoz', 'adj.', 'down, descended', '{"english": "down, descended", "pos": "adj.", "romanization": "raak\u00f3oz", "r": 4, "a": 3, "i": 8624, "ts": 1527818202}'),
('چالاکۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ټګۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نښلوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('باطلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جاهلان', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جاهل', 1, 0, 0, 'jaahíl', 'adj./ n.m.anim.unisex', 'ignorant, stupid', '{"english": "ignorant, stupid", "pos": "adj./ n.m.anim.unisex", "romanization": "jaah\u00edl", "r": 4, "a": 3, "i": 5453, "ts": 1527820479}'),
('فاسدې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('صادقانه', 1, 0, 1, 'saadiqaaná', 'adv./ adj.', 'sincerely, truthfully, faithfully', '{"english": "sincerely, truthfully, faithfully", "pos": "adv./ adj.", "romanization": "saadiqaan\u00e1", "r": 3, "a": 3, "i": 11197, "ts": 1527811328}'),
('تریخوالی', 1, 0, 0, 'treekhwáalay', 'n.m.', 'bitterness, spicyness', '{"english": "bitterness, spicyness", "pos": "n.m.", "romanization": "treekhw\u00e1alay", "r": null, "a": 3, "i": 4323, "ts": 1704701466937}'),
('وبخښلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رغړول', 1, 0, 0, 'rghuRawúl', 'v.trans.', 'to open, turn over, turn, move, to look around', '{"english": "to open, turn over, turn, move, to look around", "pos": "v.trans.", "romanization": "rghuRaw\u00fal", "r": 4, "a": 2, "i": 8814, "ts": 1527820299}'),
('حیرانې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۱۶‏:‌۱۲‌‏-‌۱۳', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('کلیوپاس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لیده.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ویناوو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورسیږی؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('تېرېدلو', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وغړېدلې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بیانولې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رانغلل؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('شکونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شته؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('کباب', 1, 0, 0, 'kabáab', 'n.m.', 'kebab, roast', '{"english": "kebab, roast", "pos": "n.m.", "romanization": "kab\u00e1ab", "r": 4, "a": 2, "i": 12811, "ts": 1527820314}'),
('«همدارنګه', 1, 0, 0, '', 'Noun_Feminine', 'Inferred noun_feminine', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۱۶‏:‌۱۹‌‏-‌۲۰', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راوغورځېده', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کرلې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لټوم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وهې.›»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('کړوپه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شوې.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('نېغه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خر', 1, 3, 0, 'khur', 'n.m.', 'snore, snort, sneeze', '{"english": "snore, snort, sneeze", "pos": "n.m.", "romanization": "khur", "r": 3, "a": 1, "i": 7013, "ts": 1527820910}'),
('خجالته', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۱۳‏:‌۳۳', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۷‏:‌۱۳‌‏-‌۱۴،‌۲۱‌‏-‌۲۳', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('«زیات', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ټکوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('څښلې', 1, 2, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورکاوه.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۲۳‏:‌۳۷‌‏-‌۳۹', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ګیدړ', 1, 0, 0, 'geedáR', 'n.m.anim.unisex', 'jackal, fox', '{"english": "jackal, fox", "pos": "n.m.anim.unisex", "romanization": "geed\u00e1R", "r": 4, "a": 3, "i": 14180, "ts": 1527818189}'),
('روغوم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پنډغالی', 1, 0, 0, 'punDgháalay', 'n.m.', 'camp; sheep or cattle pen, sheepfold; a place where guests are received and entertained', '{"english": "camp; sheep or cattle pen, sheepfold; a place where guests are received and entertained", "pos": "n.m.", "romanization": "punDgh\u00e1alay", "r": 4, "a": 2, "i": 3358, "ts": 1527820090}'),
('څوکیدار', 1, 0, 0, 'tsokeedáar', 'n.m.anim.unisex', 'watchman, doorman, chokidar', '{"english": "watchman, doorman, chokidar", "pos": "n.m.anim.unisex", "romanization": "tsokeed\u00e1ar", "r": 4, "a": 3, "i": 6585, "ts": 1527819211}'),
('خلاصوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('څړځای', 1, 2, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('قربانوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شپول', 1, 0, 0, 'shpol', 'n.m.', 'fence; halo', '{"english": "fence; halo", "pos": "n.m.", "romanization": "shpol", "r": 3, "a": 3, "i": 10635, "ts": 1527820093}'),
('ومومم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پېرانو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پرېږدې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سنګساروی؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('سنګساروو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خدایۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بدلېدلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('فیبی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کینخریه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خادمه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('درپېژنم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اپنتوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اندرونیکاس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یونیا', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('امپلیاتوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اوربانوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('استاخیس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اپلیس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ارستبولوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('هیرودیون', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نرکیسوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('تریفینا', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('تریفوسا', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ګرانې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پرسیس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اسونکریتوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('فلیګون', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('هرمیس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پتروباس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('هرماس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('فیلولوګاس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جولیه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نیریاس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اولیمپیاس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خوږو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('غوړه', 1, 0, 1, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مالۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لوسیوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سوسیپاتوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ترتیوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('منشی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لیکونکی', 1, 0, 0, 'leekóonkay', 'n.m.anim.unisex', 'writer', '{"english": "writer", "pos": "n.m.anim.unisex", "romanization": "leek\u00f3onkay", "r": 4, "a": 3, "i": 14818, "ts": 1527812042}'),
('کوارتس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اعلانوم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('څرګندولو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('زیاتوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('راوخېژی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورژیږی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ښایست', 1, 0, 4, 'xaayíst', 'n.m.', 'beauty', '{"english": "beauty", "pos": "n.m.", "romanization": "xaay\u00edst", "r": 4, "a": 3, "i": 11075, "ts": 1527816280}'),
('ازمېښتونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یم،»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راونیول', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('حد', 1, 0, 4, 'had', 'n.m.', 'boundary, limit, extent', '{"english": "boundary, limit, extent", "pos": "n.m.", "romanization": "had", "r": 4, "a": 3, "i": 6661, "ts": 1527816228}'),
('مقصدونه', 1, 0, 1, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اخلاقی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ایینه', 1, 0, 1, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بخښونکی', 1, 0, 0, 'bakhxóonkay', 'adj.', 'forgiving', '{"english": "forgiving", "pos": "adj.", "romanization": "bakhx\u00f3onkay", "r": 4, "a": 2, "i": 1723, "ts": 1527813469}'),
('ږدو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('غږوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('الوتله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«راولوېد', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('اغیزې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یې:«دا', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('کیږی!»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('زحمتونو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورېبه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورېبل', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پاخه', 1, 0, 1, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وزبېښل', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('قیضو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کیلومترو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۱‏:‌۱۹‌‏-‌۲۸', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۳‏:‌۱۳', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۴‏:‌۱۱', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۴‏:‌۱‌‏-‌۱۳', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('هماغو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ماهیګیرانو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۴‏:‌۱۲‌‏-‌۲۲', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('اعلاناوه', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۴‏:‌۳۱‌‏-‌۳۷', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۴‏:‌۴۲‌‏-‌۴۴', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('«ټول', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('لټوی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۵‏:‌۱۲‌‏-‌۱۶', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('امفیپولیس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اپولونیا', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لوچک', 1, 0, 0, 'loochák', 'n.m.anim.unisex / adj.', 'shabby, having patchy hair (dog); hoodlum, vagabond, derelict', '{"english": "shabby, having patchy hair (dog); hoodlum, vagabond, derelict", "pos": "n.m.anim.unisex / adj.", "romanization": "looch\u00e1k", "r": 3, "a": 2, "i": 14671, "ts": 1593793077468}'),
('اړولې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نومیږی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ومنلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بیانوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ولمسوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بدرګه', 1, 0, 0, 'badragá', 'n.f.', 'escort, accompaniment', '{"english": "escort, accompaniment", "pos": "n.f.", "romanization": "badrag\u00e1", "r": 4, "a": 2, "i": 1776, "ts": 1527813651}'),
('ورسېدلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ژره', 1, 0, 0, 'jzúra', 'n.f.', 'thorn, prickle', '{"english": "thorn, prickle", "pos": "n.f.", "romanization": "jz\u00fara", "r": 4, "a": 2, "i": 9460, "ts": 1527811889}'),
('اپیکوری', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رواقی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('فیلسوفانو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خوښول', 1, 0, 1, 'khwuxawúl', 'v.stat.comp.trans.', 'to like, to choose, to select; to make happy', '{"english": "to like, to choose, to select; to make happy", "pos": "v.stat.comp.trans.", "romanization": "khwuxaw\u00fal", "r": 4, "a": 3, "i": 7415, "ts": 1527812811}'),
('نظرونو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ګرځېدم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نامعلوم', 1, 0, 0, 'naama''alóom', 'adj.', 'unknown', '{"english": "unknown", "pos": "adj.", "romanization": "naama''al\u00f3om", "r": 4, "a": 3, "i": 16896, "ts": 1527815102}'),
('دپاره.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('عبادتځایونو', 1, 4, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('حدونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شاعرانو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('هنر', 1, 0, 0, 'hUnár', 'n.m.', 'art, skill', '{"english": "art, skill", "pos": "n.m.", "romanization": "hUn\u00e1r", "r": 4, "a": 3, "i": 17834, "ts": 1527811731}'),
('مهارت', 1, 6, 0, 'mahaarát', 'n.m.', 'skill, mastery, ability', '{"english": "skill, mastery, ability", "pos": "n.m.", "romanization": "mahaar\u00e1t", "r": 4, "a": 3, "i": 16375, "ts": 1527818462}'),
('دیونیسوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('دامریس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پیروس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سوپاتروس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سکندوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('تسالونیکې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شنبې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کړکۍ', 1, 1, 1, 'kuRkúy', 'n.f.', 'window', '{"english": "window", "pos": "n.f.", "romanization": "kuRk\u00fay", "r": 4, "a": 3, "i": 13044, "ts": 1527812045}'),
('افتیخوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('منزل', 1, 0, 0, 'manzál', 'n.m.', 'floor, storey, story (in a building)', '{"english": "floor, storey, story (in a building)", "pos": "n.m.", "romanization": "manz\u00e1l", "r": 4, "a": 3, "i": 16278, "ts": 1664031322562}'),
('وروغورځاوه', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کښېناستو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('میتیلینې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خیوس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ساموس', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('راورسېدم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ډډه', 1, 0, 1, 'DáDa', 'n.f.', 'direction, side', '{"english": "direction, side", "pos": "n.f.", "romanization": "D\u00e1Da", "r": 4, "a": 3, "i": 8347, "ts": 1527814081}'),
('همدا‌نن', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ساتنې', 1, 1, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('امان', 1, 0, 0, 'amáan', 'n.m.', 'security, calm; mercy, pardon, amnesty', '{"english": "security, calm; mercy, pardon, amnesty", "pos": "n.m.", "romanization": "am\u00e1an", "r": 4, "a": 2, "i": 986, "ts": 1527816144}'),
('سپارم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سخاوتمندانه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('درکولو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('واخیستلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مکاشفې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شانداره', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ډکوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وښودله.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ورسپارل', 1, 2, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رارسیږی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('واړاوه.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('‹څښتن', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('وپېژنه،›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('خطاګانې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یادوم.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('باطلوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شه»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۷‏:‌۱‌‏-‌۱۰', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۹‏:‌۵۷‌‏-‌۶۲', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راځه', 1, 1, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اراموی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۸‏:‌۲۶‌‏-‌۳۹', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('شړې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورولوېدله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پرانیستې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«پورته', 1, 0, 0, '', 'Noun_Feminine', 'Inferred noun_feminine', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('پېښیږی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('اغېزی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بلېدل', 1, 0, 0, 'baledúl', 'v.stat.comp.intrans.', 'to burn, catch fire', '{"english": "to burn, catch fire", "pos": "v.stat.comp.intrans.", "romanization": "baled\u00fal", "r": 4, "a": 2, "i": 2179, "ts": 1527813842}'),
('الوتلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ځنډه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کښېناسته', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('دروی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('هک', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سکون', 1, 0, 0, 'sUkóon', 'n.m.', 'peace, rest, repose, tranquility, calm, peace and quiet, peace of mind', '{"english": "peace, rest, repose, tranquility, calm, peace and quiet, peace of mind", "pos": "n.m.", "romanization": "sUk\u00f3on", "r": 4, "a": 2, "i": 10114, "ts": 1527819019}'),
('‹ستاسو', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('درښایی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«لعنت', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('«نېکان', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('سره،»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ماتولی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خواوې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شاملې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سرپرستۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خصلت', 1, 0, 0, 'khislát', 'n.m.', 'character, trait, disposition; habit', '{"english": "character, trait, disposition; habit", "pos": "n.m.", "romanization": "khisl\u00e1t", "r": 4, "a": 3, "i": 7132, "ts": 1527819699}'),
('فاسده', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خدمتګارانو»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('لوګی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('«امین', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('خدای»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ګړزهار', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کاندی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('غوندی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('وربلل', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نبوت', 1, 0, 0, 'nabUwát', 'n.m.', 'prophecy, the role or mission of a prophet', '{"english": "prophecy, the role or mission of a prophet", "pos": "n.m.", "romanization": "nabUw\u00e1t", "r": 4, "a": 1, "i": 16948, "ts": 1586262390716}'),
('«وفادار', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('رښتینی»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ککړه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کلام»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ورون', 1, 0, 0, 'wroon', 'n.m.', 'thigh, hip', '{"english": "thigh, hip", "pos": "n.m.", "romanization": "wroon", "r": 4, "a": 2, "i": 18209, "ts": 1527819238}'),
('څښتن.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('الوتونکو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جنګیالیو', 1, 11, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('غوښو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خپروم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('برابره', 1, 0, 2, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پرمختللی', 1, 0, 0, 'purmakhtlúlay', 'adj.', 'advanced, developed, enhanced', '{"english": "advanced, developed, enhanced", "pos": "adj.", "romanization": "purmakhtl\u00falay", "r": 4, "a": 3, "i": 3033, "ts": 1527813577}'),
('واوروم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«عادل', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('پېژندنې', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پوچ', 1, 0, 0, 'pooch', 'adj.', 'nonsense, stupid, absurd, senseless', '{"english": "nonsense, stupid, absurd, senseless", "pos": "adj.", "romanization": "pooch", "r": 4, "a": 3, "i": 3558, "ts": 1651787720409}'),
('مغزونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('فنا‌کېدونکی', 1, 0, 0, '', 'Adjective', 'Inferred adjective', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('خزندو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('همجنس', 1, 0, 0, 'humjíns', 'adj./ n.m.anim.unisex', 'homogenous; homosexual', '{"english": "homogenous; homosexual", "pos": "adj./ n.m.anim.unisex", "romanization": "humj\u00edns", "r": null, "a": 2, "i": 17772, "ts": 1690321086684}'),
('شرمه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بې‌لاریو', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('فاسدو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نیتونو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('چارې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بې‌مینې', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('بې‌رحمه', 1, 0, 0, '', 'Noun_Feminine', 'Inferred noun_feminine', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('‹ځکه', 1, 0, 0, '', 'Noun_Feminine', 'Inferred noun_feminine', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ویلی.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('‹مزدوران', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راوغواړه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وو.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ورکړه.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('‹ملګریه', 1, 0, 0, '', 'Noun_Feminine', 'Inferred noun_feminine', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('سخی', 1, 0, 0, 'skháy', 'n.m.anim.unisex', 'calf; bull-calf', '{"english": "calf; bull-calf", "pos": "n.m.anim.unisex", "romanization": "skh\u00e1y", "r": 4, "a": 3, "i": 9889, "ts": 1610447830096}'),
('یم؟›»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ګوښې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۱۰‏:‌۳۵‌‏-‌۴۵', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('«پاڅېږی', 1, 0, 0, '', 'Adjective', 'Inferred adjective', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('وکړیږی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۹‏:‌۱۴‌‏-‌۲۹', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('شی.]»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راټولوونکی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورکوی؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('څخه؟»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('څخه.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('معاف', 1, 0, 0, 'mUaaf', 'adj.', 'forgiven, pardoned, exempt, excused, acquitted, immune, dismissed', '{"english": "forgiven, pardoned, exempt, excused, acquitted, immune, dismissed", "pos": "adj.", "romanization": "mUaaf", "r": 4, "a": 3, "i": 15903, "ts": 1527812118}'),
('چنګک', 1, 0, 0, 'changák', 'n.m.', 'hook, grappling hook; tweezer; fishing rod and hook', '{"english": "hook, grappling hook; tweezer; fishing rod and hook", "pos": "n.m.", "romanization": "chang\u00e1k", "r": 4, "a": 2, "i": 6245, "ts": 1527819052}'),
('واچوه', 1, 1, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('راوباسه', 1, 1, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('عینی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('وڅېړلې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پچې', 1, 10, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('سوځېدله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خوښۍ', 1, 2, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ودرېږم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پېښېدلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اشارې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('امیدوارۍ', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شپږمه', 1, 3, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ولېږله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کوژدن', 1, 0, 3, 'koojzdún', 'n.m.', 'engagement, fiancee', '{"english": "engagement, fiancee", "pos": "n.m.", "romanization": "koojzd\u00fan", "r": 4, "a": 3, "i": 13529, "ts": 1527813389}'),
('ختمیږی.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('خپلوانه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ورننوتله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«بیانوی', 1, 0, 0, '', 'Adjective', 'Inferred adjective', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('رحمت', 1, 0, 1, 'rahmát', 'n.m.', 'mercy, sympathy, pity', '{"english": "mercy, sympathy, pity", "pos": "n.m.", "romanization": "rahm\u00e1t", "r": 4, "a": 3, "i": 8709, "ts": 1527814895}'),
('مټو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کبرجن', 1, 0, 0, 'kaburjún', 'adj.', 'proud, arrogant', '{"english": "proud, arrogant", "pos": "adj.", "romanization": "kaburj\u00fan", "r": 4, "a": 3, "i": 12817, "ts": 1527814896}'),
('راغورځولی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شاهان', 1, 1, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('اورېدله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('«ثنا', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('رایادوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پاکۍ', 1, 0, 4, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ماشومه', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یادېږې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لاره»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('غټېده', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('څرګنده', 1, 0, 2, 'tsargúnda', 'adj.', 'clear, obvious, apparent, disclosed', '{"english": "clear, obvious, apparent, disclosed", "pos": "adj.", "romanization": "tsarg\u00fanda", "r": 4, "a": 3, "i": 6477, "ts": 1708355928197}'),
('ملخانو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('چیچلو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مخونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مخونو', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ګاډیو', 1, 3, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('میدان', 1, 0, 0, 'maydáan', 'n.m.', 'ground (as in sports, battle etc.), public square', '{"english": "ground (as in sports, battle etc.), public square", "pos": "n.m.", "romanization": "mayd\u00e1an", "r": 4, "a": 2, "i": 16564, "ts": 1527820812}'),
('ځغلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لکیو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('نېشونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ابدون', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('آپولیون', 1, 0, 0, '', 'unknown', 'Inferred noun', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کونجونو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('میلیونه', 1, 0, 0, '', 'unknown', 'Inferred noun_plural', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رنګه', 1, 0, 0, 'rangá', 'adj.', 'colourful, multicoloured, chromatic', '{"english": "colourful, multicoloured, chromatic", "pos": "adj.", "romanization": "rang\u00e1", "r": 3, "a": 3, "i": 8874, "ts": 1527820295}'),
('زیړې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لکۍ‌ګانې', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راګېروی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ووهو', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مخالفتونو', 1, 0, 1, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('رټی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('قبلوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خوشحالوونکې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('خوندوره', 1, 0, 0, '', 'unknown', 'Inferred noun_feminine', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('روزل', 1, 2, 1, 'rozúl', 'v.trans.', 'to train, bring up', '{"english": "to train, bring up", "pos": "v.trans.", "romanization": "roz\u00fal", "r": 4, "a": 2, "i": 8934, "ts": 1527815233}'),
('قدمونو', 1, 2, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ګوډې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('زهرجنې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('مړۍ', 1, 0, 0, 'maRúy', 'n.f.', 'piece, bread, bite, sip, gulp, food, meal', '{"english": "piece, bread, bite, sip, gulp, food, meal", "pos": "n.f.", "romanization": "maR\u00fay", "r": 4, "a": 2, "i": 15583, "ts": 1527816684}'),
('منظره', 1, 0, 0, 'manzará', 'n.f.', 'view, scenery', '{"english": "view, scenery", "pos": "n.f.", "romanization": "manzar\u00e1", "r": 3, "a": 2, "i": 16310, "ts": 1527815981}'),
('رپېږم.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ولړزوله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ولړزوم.»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('بیا»', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('خلق', 1, 0, 0, 'khalq', 'n.m./ n.m.pl.', 'people, nation, populace; creature, created', '{"english": "people, nation, populace; creature, created", "pos": "n.m./ n.m.pl.", "romanization": "khalq", "r": 4, "a": 3, "i": 7184, "ts": 1527812343}'),
('لړزېدونکی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('لړزېدونکې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('راوستونکی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('ښکنځل', 1, 0, 1, 'xkandzúl', 'v.trans.', 'to swear or curse at someone', '{"english": "to swear or curse at someone", "pos": "v.trans.", "romanization": "xkandz\u00fal", "r": 4, "a": 2, "i": 11116, "ts": 1527823539}'),
('۱۴‏:‌۳۴‌‏-‌۳۵', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('پټېدلی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('‹قتل', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('بیول', 1, 0, 0, 'buyawul', 'v.trans.', 'pour, drain, spill', '{"english": "pour, drain, spill", "pos": "v.trans.", "romanization": "buyawul", "r": 3, "a": null, "i": 2727, "ts": 1527817902}'),
('جېب', 1, 0, 0, 'jeb', 'n.m.', 'pocket', '{"english": "pocket", "pos": "n.m.", "romanization": "jeb", "r": 4, "a": null, "i": 5784, "ts": 1527819538}'),
('‹زنا', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('اندام', 1, 0, 0, 'andáam', 'n.m.', 'limb, extremity; organ; figure; member', '{"english": "limb, extremity; organ; figure; member", "pos": "n.m.", "romanization": "and\u00e1am", "r": 4, "a": 2, "i": 1131, "ts": 1527811803}'),
('۱۹‏:‌۹', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۱۶‏:‌۱۸', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('‹کله', 1, 0, 0, '', 'Verb', 'Inferred verb', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('ورکړی.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۶‏:‌۲۹‌‏-‌۳۰', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('غاښ', 1, 0, 0, 'ghaax', 'n.m.', 'tooth', '{"english": "tooth", "pos": "n.m.", "romanization": "ghaax", "r": 4, "a": 3, "i": 11694, "ts": 1527816746}'),
('غاښ.›', 1, 0, 0, '', 'Noun', 'Inferred noun', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('اخله', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یونیم', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('۶‏:‌۲۷‌‏-‌۲۸', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('۶‏:‌۳۲‌‏-‌۳۶', 1, 0, 0, '', 'Numeral', 'Inferred numeral', '{"source": "inference", "confidence": "medium", "gender": "", "pos_family": ""}'),
('راخېژوی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('پوخوالی', 1, 0, 0, 'pokhwáalay', 'n.m.', 'baking, roasting; maturity, ripeness; sureness, definiteness', '{"english": "baking, roasting; maturity, ripeness; sureness, definiteness", "pos": "n.m.", "romanization": "pokhw\u00e1alay", "r": 4, "a": 2, "i": 3566, "ts": 1527812248}'),
('بنیادی', 1, 0, 0, '', 'unknown', 'Inferred adjective', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('شیدو', 1, 0, 2, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('روزنې', 1, 0, 0, '', 'unknown', 'Inferred verb', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('تمرین', 1, 0, 3, 'tamréen', 'n.m.', 'practice, exercise, drill, training', '{"english": "practice, exercise, drill, training", "pos": "n.m.", "romanization": "tamr\u00e9en", "r": 4, "a": 2, "i": 4700, "ts": 1527817134}'),
('کړي', 0, 67, 86, '', '', '', '{}'),
('دي', 0, 60, 126, '', '', '', '{}'),
('شوي', 0, 47, 78, '', '', '', '{}'),
('شي', 0, 45, 136, '', '', '', '{}'),
('نبي', 0, 42, 0, '', '', '', '{}'),
('طایفې', 0, 39, 0, '', '', '', '{}'),
('وو،', 0, 39, 8, '', '', '', '{}'),
('ښارګوټي', 0, 39, 0, '', '', '', '{}'),
('یروبعام', 0, 38, 0, '', '', '', '{}'),
('ؤ،', 0, 37, 12, '', '', '', '{}'),
('پاچاهي', 0, 35, 4, '', '', '', '{}'),
('وي', 0, 33, 109, '', '', '', '{}'),
('وکړي', 0, 32, 40, '', '', '', '{}'),
('ییل', 0, 31, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('بیت', 0, 28, 0, 'bayt', 'n.m.', 'couplet (poetry); house, family, Arabic prefix meaning "place of"', '{"english": "couplet (poetry); house, family, Arabic prefix meaning \"place of\"", "pos": "n.m.", "romanization": "bayt", "r": 3, "a": 2, "i": 2587, "ts": 1527813630}'),
('یواب', 0, 28, 0, '', '', '', '{}'),
('فلسطینیانو', 0, 22, 0, '', '', '', '{}'),
('نامه،', 0, 22, 0, '', '', '', '{}'),
('منسي', 0, 20, 0, '', '', '', '{}'),
('شو،', 0, 19, 18, '', '', '', '{}'),
('دی،', 0, 19, 79, '', '', '', '{}'),
('حبرون', 0, 18, 0, '', '', '', '{}'),
('طایفو', 0, 17, 0, '', '', '', '{}'),
('قوي', 0, 17, 20, '', '', '', '{}'),
('لاوي', 0, 17, 0, '', '', '', '{}'),
('شاهي', 0, 15, 1, '', '', '', '{}'),
('کړئ', 0, 14, 19, '', '', '', '{}'),
('وکړئ', 0, 13, 28, '', '', '', '{}'),
('جلعاد', 0, 13, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('قهات', 0, 13, 0, '', '', '', '{}'),
('دي،', 0, 12, 60, '', '', '', '{}'),
('وکړه،', 0, 12, 4, '', '', '', '{}'),
('اخیا', 0, 12, 0, '', '', '', '{}'),
('مراري', 0, 12, 0, '', '', '', '{}'),
('وه،', 0, 12, 3, '', '', '', '{}'),
('کالیب', 0, 12, 0, '', '', '', '{}'),
('نسب', 0, 12, 0, '', '', '', '{}'),
('قبیله', 0, 11, 0, '', '', '', '{}'),
('معکه', 0, 11, 0, '', '', '', '{}'),
('ادوم', 0, 11, 0, 'adóom', 'n.m.', 'thigh, leg', '{"english": "thigh, leg", "pos": "n.m.", "romanization": "ad\u00f3om", "r": 1, "a": 2, "i": 389, "ts": 1573658287586}'),
('اساف', 0, 11, 0, '', '', '', '{}'),
('ساتونکي', 0, 11, 3, '', '', '', '{}'),
('حداد', 0, 11, 0, '', '', '', '{}'),
('طایفه', 0, 11, 0, '', '', '', '{}'),
('ویلي', 0, 10, 2, '', '', '', '{}'),
('جنګیالي', 0, 10, 0, '', '', '', '{}'),
('مسوولان', 0, 10, 0, '', '', '', '{}'),
('جرشون', 0, 10, 0, '', '', '', '{}'),
('هیمان', 0, 10, 0, '', '', '', '{}'),
('وایي', 0, 10, 40, '', '', '', '{}'),
('جنګي', 0, 10, 1, '', '', '', '{}'),
('پلار،', 0, 10, 0, '', '', '', '{}'),
('لمسی', 0, 10, 0, '', '', '', '{}'),
('سړي', 0, 9, 12, '', '', '', '{}'),
('کلي', 0, 9, 0, '', '', '', '{}'),
('هددعزر', 0, 9, 0, '', '', '', '{}'),
('شي،', 0, 9, 37, '', '', '', '{}'),
('عمونیانو', 0, 9, 0, '', '', '', '{}'),
('نفتالي', 0, 8, 0, '', '', '', '{}'),
('فلسطینیان', 0, 8, 0, '', '', '', '{}'),
('کړ،', 0, 8, 5, '', '', '', '{}'),
('زرویه', 0, 8, 0, '', '', '', '{}'),
('بنایاه', 0, 8, 0, '', '', '', '{}'),
('یوناتان', 0, 8, 0, '', '', '', '{}'),
('عمون', 0, 8, 0, '', '', '', '{}'),
('کړي،', 0, 8, 19, '', '', '', '{}'),
('سپرونه', 0, 8, 0, '', '', '', '{}'),
('وې،', 0, 8, 1, '', '', '', '{}'),
('شمعي', 0, 8, 0, '', '', '', '{}'),
('میکا', 0, 8, 0, '', '', '', '{}'),
('حصرون', 0, 8, 0, '', '', '', '{}'),
('ماخیر', 0, 8, 0, '', '', '', '{}'),
('څړځایونه', 0, 8, 0, '', '', '', '{}'),
('اسا', 0, 8, 0, '', '', '', '{}'),
('لرګي', 0, 7, 0, '', '', '', '{}'),
('راوړي', 0, 7, 10, '', '', '', '{}'),
('ییل،', 0, 7, 0, '', '', '', '{}'),
('شئ', 0, 7, 40, '', '', '', '{}'),
('کوي', 0, 7, 111, '', '', '', '{}'),
('زېږېدلي', 0, 7, 0, '', '', '', '{}'),
('یدوتون', 0, 7, 0, '', '', '', '{}'),
('څښتنه،', 0, 7, 1, '', '', '', '{}'),
('جت', 0, 7, 0, '', '', '', '{}'),
('سوریایانو', 0, 7, 0, '', '', '', '{}'),
('ودانولو', 0, 7, 0, '', '', '', '{}'),
('یشیه', 0, 7, 0, '', '', '', '{}'),
('ایتامار', 0, 7, 0, '', '', '', '{}'),
('تاریخ', 0, 7, 0, '', '', '', '{}'),
('یتر', 0, 6, 0, '', '', '', '{}'),
('ووایئ', 0, 6, 4, '', '', '', '{}'),
('عسکري', 0, 6, 0, '', '', '', '{}'),
('لحم', 0, 6, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('کړې،', 0, 6, 1, '', '', '', '{}'),
('یئ', 0, 6, 47, '', '', '', '{}'),
('روبین،', 0, 6, 0, '', '', '', '{}'),
('څړځایونو', 0, 6, 0, '', '', '', '{}'),
('موسیقۍ', 0, 6, 0, '', '', '', '{}'),
('ووایي', 0, 6, 14, '', '', '', '{}'),
('ده،', 0, 6, 22, '', '', '', '{}'),
('ارونه', 0, 6, 0, '', '', '', '{}'),
('حانون', 0, 6, 0, '', '', '', '{}'),
('قیمتي', 0, 6, 6, '', '', '', '{}'),
('زر،', 0, 6, 0, '', '', '', '{}'),
('شلومیت', 0, 6, 0, '', '', '', '{}'),
('تحویلخانو', 0, 6, 0, '', '', '', '{}'),
('زوی،', 0, 6, 0, '', '', '', '{}'),
('کړوسی', 0, 6, 0, '', '', '', '{}'),
('باشان', 0, 6, 0, '', '', '', '{}'),
('یساکار', 0, 5, 0, '', '', '', '{}'),
('یریموت', 0, 5, 0, '', '', '', '{}'),
('استازي', 0, 5, 1, '', '', '', '{}'),
('کړه،', 0, 5, 3, '', '', '', '{}'),
('ابیشای', 0, 5, 0, '', '', '', '{}'),
('یهویاداع', 0, 5, 0, '', '', '', '{}'),
('کسیزو', 0, 5, 0, '', '', '', '{}'),
('یعییل', 0, 5, 0, '', '', '', '{}'),
('کړئ،', 0, 5, 5, '', '', '', '{}'),
('کاوه،', 0, 5, 1, '', '', '', '{}'),
('لاړ،', 0, 5, 0, '', '', '', '{}'),
('کړل،', 0, 5, 3, '', '', '', '{}'),
('وي،', 0, 5, 56, '', '', '', '{}'),
('عزه', 0, 5, 0, '', '', '', '{}'),
('سبر', 0, 5, 0, '', '', '', '{}'),
('بتان', 0, 5, 0, '', '', '', '{}'),
('جبعون', 0, 5, 0, '', '', '', '{}'),
('خپلوان،', 0, 5, 0, '', '', '', '{}'),
('شمعیه', 0, 5, 0, '', '', '', '{}'),
('ربابونه', 0, 5, 0, '', '', '', '{}'),
('سندرغاړو', 0, 5, 0, '', '', '', '{}'),
('کوي،', 0, 5, 54, '', '', '', '{}'),
('سپېڅلي', 0, 5, 11, '', '', '', '{}'),
('خدایه،', 0, 5, 0, '', '', '', '{}'),
('سوریایان', 0, 5, 0, '', '', '', '{}'),
('نومېده،', 0, 5, 0, '', '', '', '{}'),
('درلودل،', 0, 5, 0, '', '', '', '{}'),
('شوبال', 0, 5, 0, '', '', '', '{}'),
('یزهار،', 0, 5, 0, '', '', '', '{}'),
('رحبیا', 0, 5, 0, '', '', '', '{}'),
('امریا،', 0, 5, 0, '', '', '', '{}'),
('عزي', 0, 5, 0, '', '', '', '{}'),
('کوټو', 0, 5, 0, '', '', '', '{}'),
('شمع', 0, 5, 0, '', '', '', '{}'),
('یعبیز', 0, 5, 0, '', '', '', '{}'),
('شلوم', 0, 5, 0, '', '', '', '{}'),
('نامې', 0, 5, 0, '', '', '', '{}'),
('اصیل', 0, 5, 0, '', '', '', '{}'),
('دروند', 0, 5, 1, '', '', '', '{}'),
('ورکړي', 0, 4, 11, '', '', '', '{}'),
('میلې', 0, 4, 0, '', '', '', '{}'),
('یقطان', 0, 4, 0, '', '', '', '{}'),
('ابیناداب', 0, 4, 0, '', '', '', '{}'),
('مړي', 0, 4, 7, '', '', '', '{}'),
('وسلې', 0, 4, 3, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('جنګیالی', 0, 4, 0, 'jangyaaláy', 'n.m.', 'warrior, fighter, soldier', '{"english": "warrior, fighter, soldier", "pos": "n.m.", "romanization": "jangyaal\u00e1y", "r": 4, "a": 2, "i": 5692, "ts": 1527816936}'),
('خوندي', 0, 4, 1, '', '', '', '{}'),
('تقوع', 0, 4, 0, '', '', '', '{}'),
('عناتوت', 0, 4, 0, '', '', '', '{}'),
('عزموت', 0, 4, 0, '', '', '', '{}'),
('حانان', 0, 4, 0, '', '', '', '{}'),
('میکاییل،', 0, 4, 0, '', '', '', '{}'),
('فرقو', 0, 4, 0, '', '', '', '{}'),
('صادوق،', 0, 4, 0, '', '', '', '{}'),
('لوېدیځې', 0, 4, 0, '', '', '', '{}'),
('دان', 0, 4, 0, '', '', '', '{}'),
('راکړئ', 0, 4, 0, '', '', '', '{}'),
('راشي', 0, 4, 4, '', '', '', '{}'),
('قریت', 0, 4, 0, '', '', '', '{}'),
('یعاریم', 0, 4, 0, '', '', '', '{}'),
('شرنګېدونکی', 0, 4, 1, '', '', '', '{}'),
('کیږي', 0, 4, 44, '', '', '', '{}'),
('عزییل', 0, 4, 0, '', '', '', '{}'),
('خلکو،', 0, 4, 2, '', '', '', '{}'),
('غږول', 0, 4, 1, '', '', '', '{}'),
('کوئ', 0, 4, 49, '', '', '', '{}'),
('رعیت', 0, 4, 0, '', '', '', '{}'),
('برنجي', 0, 4, 0, '', '', '', '{}'),
('اخیملک', 0, 4, 0, '', '', '', '{}'),
('ټنه', 0, 4, 0, '', '', '', '{}'),
('رافا', 0, 4, 0, '', '', '', '{}'),
('وبا', 0, 4, 0, '', '', '', '{}'),
('عمرام،', 0, 4, 0, '', '', '', '{}'),
('موشي', 0, 4, 0, '', '', '', '{}'),
('محلي،', 0, 4, 0, '', '', '', '{}'),
('شلو', 0, 4, 0, '', '', '', '{}'),
('چارو', 0, 4, 0, '', '', '', '{}'),
('ناداب،', 0, 4, 0, '', '', '', '{}'),
('ناداب', 0, 4, 0, '', '', '', '{}'),
('شوباییل', 0, 4, 0, '', '', '', '{}'),
('واخلي', 0, 4, 2, '', '', '', '{}'),
('ځوانانو', 0, 4, 2, '', '', '', '{}'),
('مشاور', 0, 4, 0, '', '', '', '{}'),
('ږیرو', 0, 4, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یحییل', 0, 4, 0, '', '', '', '{}'),
('فارص', 0, 4, 0, '', '', '', '{}'),
('نقشې', 0, 4, 1, '', '', '', '{}'),
('رام', 0, 4, 0, '', '', '', '{}'),
('افراتې', 0, 4, 0, '', '', '', '{}'),
('حور', 0, 4, 0, '', '', '', '{}'),
('وزېږول', 0, 4, 0, '', '', '', '{}'),
('اشحور', 0, 4, 0, '', '', '', '{}'),
('شمای', 0, 4, 0, '', '', '', '{}'),
('عوبدیا', 0, 4, 0, '', '', '', '{}'),
('مېشت', 0, 4, 0, '', '', '', '{}'),
('عزي،', 0, 4, 0, '', '', '', '{}'),
('جرشونیانو', 0, 4, 0, '', '', '', '{}'),
('بریعه', 0, 4, 0, '', '', '', '{}'),
('احاز', 0, 4, 0, '', '', '', '{}'),
('زیمري', 0, 4, 0, '', '', '', '{}'),
('نباط', 0, 4, 0, '', '', '', '{}'),
('شیلوه', 0, 4, 0, '', '', '', '{}'),
('قمچینو', 0, 4, 0, '', '', '', '{}'),
('الیشمع،', 0, 3, 0, '', '', '', '{}'),
('الیفلط', 0, 3, 0, '', '', '', '{}'),
('راولي', 0, 3, 1, '', '', '', '{}'),
('هدورام،', 0, 3, 0, '', '', '', '{}'),
('پوښ', 0, 3, 0, '', '', '', '{}'),
('ګانو', 0, 3, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('یې؟', 0, 3, 1, '', '', '', '{}'),
('یوناتان،', 0, 3, 0, '', '', '', '{}'),
('واورېدل،', 0, 3, 0, '', '', '', '{}'),
('کډه', 0, 3, 0, '', '', '', '{}'),
('شول،', 0, 3, 1, '', '', '', '{}'),
('پټي', 0, 3, 0, '', '', '', '{}'),
('زړورو', 0, 3, 0, '', '', '', '{}'),
('کسیزې', 0, 3, 0, '', '', '', '{}'),
('عیرا', 0, 3, 0, '', '', '', '{}'),
('ابیعزر', 0, 3, 0, '', '', '', '{}'),
('سبکای', 0, 3, 0, '', '', '', '{}'),
('عشتاروت', 0, 3, 0, '', '', '', '{}'),
('یدیعییل', 0, 3, 0, '', '', '', '{}'),
('الي', 0, 3, 0, '', '', '', '{}'),
('مواب', 0, 3, 0, '', '', '', '{}'),
('غشو', 0, 3, 0, '', '', '', '{}'),
('یسي', 0, 3, 0, '', '', '', '{}'),
('وکړي،', 0, 3, 18, '', '', '', '{}'),
('شمالي', 0, 3, 0, '', '', '', '{}'),
('حمات', 0, 3, 0, '', '', '', '{}'),
('ګانې', 0, 3, 1, 'gaané', 'suff.', 'plural suffix for femine nouns ending with ا etc.', '{"english": "plural suffix for femine nouns ending with \u0627 etc.", "pos": "suff.", "romanization": "gaan\u00e9", "r": 4, "a": 2, "i": 13733, "ts": 1588784938063}'),
('ولري', 0, 3, 11, '', '', '', '{}'),
('جازر', 0, 3, 0, '', '', '', '{}'),
('اوري', 0, 3, 2, '', '', '', '{}'),
('راوړئ', 0, 3, 1, '', '', '', '{}'),
('لومړي', 0, 3, 0, '', '', '', '{}'),
('وغږوي', 0, 3, 0, '', '', '', '{}'),
('کننیا', 0, 3, 0, '', '', '', '{}'),
('ډوډۍ،', 0, 3, 0, '', '', '', '{}'),
('یحزییل', 0, 3, 0, '', '', '', '{}'),
('وشي', 0, 3, 1, '', '', '', '{}'),
('راشئ', 0, 3, 2, '', '', '', '{}'),
('مرستیالان', 0, 3, 0, '', '', '', '{}'),
('اورېدلي', 0, 3, 5, '', '', '', '{}'),
('مهرباني', 0, 3, 0, '', '', '', '{}'),
('ورکړه،', 0, 3, 0, '', '', '', '{}'),
('باج', 0, 3, 0, '', '', '', '{}'),
('صوبې', 0, 3, 0, '', '', '', '{}'),
('ټکول', 0, 3, 0, '', '', '', '{}'),
('ناحاش', 0, 3, 0, '', '', '', '{}'),
('رسمي', 0, 3, 0, '', '', '', '{}'),
('شوه،', 0, 3, 1, '', '', '', '{}'),
('حام', 0, 3, 0, '', '', '', '{}'),
('عیبر', 0, 3, 0, '', '', '', '{}'),
('قناز', 0, 3, 0, '', '', '', '{}'),
('ایصر', 0, 3, 0, '', '', '', '{}'),
('اونام', 0, 3, 0, '', '', '', '{}'),
('ګرامه', 0, 3, 0, '', '', '', '{}'),
('قدو', 0, 3, 0, '', '', '', '{}'),
('یاییر', 0, 3, 0, '', '', '', '{}'),
('لحمي', 0, 3, 0, '', '', '', '{}'),
('ورکړ،', 0, 3, 1, '', '', '', '{}'),
('عملي', 0, 3, 2, '', '', '', '{}'),
('پیروي', 0, 3, 14, '', '', '', '{}'),
('کومي', 0, 3, 3, '', '', '', '{}'),
('جرشون،', 0, 3, 0, '', '', '', '{}'),
('لعدان', 0, 3, 0, '', '', '', '{}'),
('عمرام', 0, 3, 0, '', '', '', '{}'),
('الیعازر', 0, 3, 0, '', '', '', '{}'),
('یزهار', 0, 3, 0, '', '', '', '{}'),
('محلي', 0, 3, 0, '', '', '', '{}'),
('کیږي،', 0, 3, 27, '', '', '', '{}'),
('ورسیږي', 0, 3, 3, '', '', '', '{}'),
('پاچا،', 0, 3, 1, '', '', '', '{}'),
('وروسپارل', 0, 3, 0, '', '', '', '{}'),
('لست', 0, 3, 2, '', '', '', '{}'),
('یعزیا', 0, 3, 0, '', '', '', '{}'),
('زکور', 0, 3, 0, '', '', '', '{}'),
('اعلانول', 0, 3, 0, '', '', '', '{}'),
('حشبیا', 0, 3, 0, '', '', '', '{}'),
('متتیا', 0, 3, 0, '', '', '', '{}'),
('غږوونکي', 0, 3, 0, '', '', '', '{}'),
('پنځلسمه', 0, 3, 0, '', '', '', '{}'),
('حننیا', 0, 3, 0, '', '', '', '{}'),
('قوري', 0, 3, 0, '', '', '', '{}'),
('مشلمیا', 0, 3, 0, '', '', '', '{}'),
('شفیم', 0, 3, 0, '', '', '', '{}'),
('نیر', 0, 3, 0, '', '', '', '{}'),
('درباریان', 0, 3, 0, '', '', '', '{}'),
('مقلوت', 0, 3, 0, '', '', '', '{}'),
('عتني', 0, 3, 0, '', '', '', '{}'),
('شافاط', 0, 3, 0, '', '', '', '{}'),
('ذکر', 0, 3, 0, '', '', '', '{}'),
('کېده،', 0, 3, 3, '', '', '', '{}'),
('خپاره', 0, 3, 0, '', '', '', '{}'),
('ټنو', 0, 3, 0, '', '', '', '{}'),
('شهرت', 0, 3, 0, '', '', '', '{}'),
('ایتان', 0, 3, 0, '', '', '', '{}'),
('سلما', 0, 3, 0, '', '', '', '{}'),
('ابیجایل', 0, 3, 0, '', '', '', '{}'),
('یرحمییل', 0, 3, 0, '', '', '', '{}'),
('یشعي', 0, 3, 0, '', '', '', '{}'),
('راقم', 0, 3, 0, '', '', '', '{}'),
('موزا', 0, 3, 0, '', '', '', '{}'),
('لمسي', 0, 3, 0, '', '', '', '{}'),
('نیمایي', 0, 3, 0, '', '', '', '{}'),
('غړي', 0, 3, 16, '', '', '', '{}'),
('ابشالوم', 0, 3, 0, '', '', '', '{}'),
('رفایا', 0, 3, 0, '', '', '', '{}'),
('سرایا', 0, 3, 0, '', '', '', '{}'),
('استوګنځایونو', 0, 3, 0, '', '', '', '{}'),
('بالع،', 0, 3, 0, '', '', '', '{}'),
('غزېدلې', 0, 3, 0, '', '', '', '{}'),
('فینحاس', 0, 3, 0, '', '', '', '{}'),
('اخیطوب،', 0, 3, 0, '', '', '', '{}'),
('عزریا،', 0, 3, 0, '', '', '', '{}'),
('قهاتیانو', 0, 3, 0, '', '', '', '{}'),
('نیکه،', 0, 3, 0, '', '', '', '{}'),
('شان،', 0, 3, 0, '', '', '', '{}'),
('کې،', 0, 3, 3, '', '', '', '{}'),
('بالع', 0, 3, 0, '', '', '', '{}'),
('اولام', 0, 3, 0, '', '', '', '{}'),
('نۀ', 0, 3, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('زمري', 0, 3, 1, '', '', '', '{}'),
('رزون', 0, 3, 0, '', '', '', '{}'),
('ییز', 0, 3, 2, '', '', '', '{}'),
('ییزو', 0, 3, 0, '', '', '', '{}'),
('کته', 0, 3, 0, '', '', '', '{}'),
('اشیره', 0, 3, 0, '', '', '', '{}'),
('بعشا', 0, 3, 0, '', '', '', '{}'),
('وغواړئ', 0, 2, 0, '', '', '', '{}'),
('نوجه،', 0, 2, 0, '', '', '', '{}'),
('نفج،', 0, 2, 0, '', '', '', '{}'),
('یافیع،', 0, 2, 0, '', '', '', '{}'),
('الیاداع', 0, 2, 0, '', '', '', '{}'),
('یهویاکین', 0, 2, 0, '', '', '', '{}'),
('یفلیط', 0, 2, 0, '', '', '', '{}'),
('شومیر', 0, 2, 0, '', '', '', '{}'),
('اوزال،', 0, 2, 0, '', '', '', '{}'),
('دقله،', 0, 2, 0, '', '', '', '{}'),
('عوبال،', 0, 2, 0, '', '', '', '{}'),
('ابیماییل،', 0, 2, 0, '', '', '', '{}'),
('شیبا،', 0, 2, 0, '', '', '', '{}'),
('حننیا،', 0, 2, 0, '', '', '', '{}'),
('شوعال،', 0, 2, 0, '', '', '', '{}'),
('باصر،', 0, 2, 0, '', '', '', '{}'),
('یتران', 0, 2, 0, '', '', '', '{}'),
('زۀ', 0, 2, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('میکال', 0, 2, 0, '', '', '', '{}'),
('ابدي', 0, 2, 1, '', '', '', '{}'),
('پردي', 0, 2, 1, '', '', '', '{}'),
('کال،', 0, 2, 0, '', '', '', '{}'),
('ورځ،', 0, 2, 0, '', '', '', '{}'),
('مشلام،', 0, 2, 0, '', '', '', '{}'),
('عدایا،', 0, 2, 0, '', '', '', '{}'),
('اوفیر،', 0, 2, 0, '', '', '', '{}'),
('حویله', 0, 2, 0, '', '', '', '{}'),
('یوباب', 0, 2, 0, '', '', '', '{}'),
('ښځې،', 0, 2, 1, '', '', '', '{}'),
('جلبوع', 0, 2, 0, '', '', '', '{}'),
('تعقیب', 0, 2, 0, '', '', '', '{}'),
('غشي', 0, 2, 0, '', '', '', '{}'),
('ورسېدل،', 0, 2, 0, '', '', '', '{}'),
('یزرعیل', 0, 2, 0, '', '', '', '{}'),
('اوسېدل،', 0, 2, 0, '', '', '', '{}'),
('ورغلل،', 0, 2, 0, '', '', '', '{}'),
('خانه', 0, 2, 0, '', '', '', '{}'),
('یابیش', 0, 2, 0, '', '', '', '{}'),
('لاړل،', 0, 2, 1, '', '', '', '{}'),
('څېړۍ', 0, 2, 0, '', '', '', '{}'),
('هډوکي', 0, 2, 0, '', '', '', '{}'),
('وئ', 0, 2, 4, '', '', '', '{}'),
('اوسېدونکي', 0, 2, 0, '', '', '', '{}'),
('کلا', 0, 2, 0, '', '', '', '{}'),
('ووژني،', 0, 2, 0, '', '', '', '{}'),
('دودو', 0, 2, 0, '', '', '', '{}'),
('اخوخ', 0, 2, 0, '', '', '', '{}'),
('اسراییلي', 0, 2, 0, '', '', '', '{}'),
('رفاییم', 0, 2, 0, '', '', '', '{}'),
('درولې', 0, 2, 0, '', '', '', '{}'),
('کرښې', 0, 2, 0, '', '', '', '{}'),
('زړورتوب', 0, 2, 0, '', '', '', '{}'),
('اوبدلو', 0, 2, 0, '', '', '', '{}'),
('مصري', 0, 2, 0, '', '', '', '{}'),
('عساهیل', 0, 2, 0, '', '', '', '{}'),
('حالز', 0, 2, 0, '', '', '', '{}'),
('فلون', 0, 2, 0, '', '', '', '{}'),
('عقیش', 0, 2, 0, '', '', '', '{}'),
('مهرای', 0, 2, 0, '', '', '', '{}'),
('نطوفې', 0, 2, 0, '', '', '', '{}'),
('فرعاتون', 0, 2, 0, '', '', '', '{}'),
('حرار', 0, 2, 0, '', '', '', '{}'),
('کرمل', 0, 2, 0, '', '', '', '{}'),
('حیتي', 0, 2, 0, '', '', '', '{}'),
('زاباد', 0, 2, 0, '', '', '', '{}'),
('احلای', 0, 2, 0, '', '', '', '{}'),
('حوتام', 0, 2, 0, '', '', '', '{}'),
('عروعیر', 0, 2, 0, '', '', '', '{}'),
('صقلغ', 0, 2, 0, '', '', '', '{}'),
('واوسیږي', 0, 2, 0, '', '', '', '{}'),
('لیندې', 0, 2, 0, '', '', '', '{}'),
('ویشتلو', 0, 2, 0, '', '', '', '{}'),
('ښي', 0, 2, 1, '', '', '', '{}'),
('ويشتلی', 0, 2, 0, '', '', '', '{}'),
('لرونکي', 0, 2, 0, '', '', '', '{}'),
('درو', 0, 2, 0, '', '', '', '{}'),
('درکړي،', 0, 2, 1, '', '', '', '{}'),
('عماسای', 0, 2, 0, '', '', '', '{}'),
('داوده،', 0, 2, 0, '', '', '', '{}'),
('یوزاباد،', 0, 2, 0, '', '', '', '{}'),
('یدیعییل،', 0, 2, 0, '', '', '', '{}'),
('تنه،', 0, 2, 0, '', '', '', '{}'),
('راضي', 0, 2, 2, '', '', '', '{}'),
('یساکار،', 0, 2, 0, '', '', '', '{}'),
('اوښان،', 0, 2, 0, '', '', '', '{}'),
('قچرې', 0, 2, 0, '', '', '', '{}'),
('ممیزو', 0, 2, 0, '', '', '', '{}'),
('پادې', 0, 2, 0, '', '', '', '{}'),
('اسماني', 0, 2, 10, '', '', '', '{}'),
('درناوي', 0, 2, 6, '', '', '', '{}'),
('الې', 0, 2, 0, '', '', '', '{}'),
('ربابونه،', 0, 2, 0, '', '', '', '{}'),
('چنګونه،', 0, 2, 0, '', '', '', '{}'),
('سرني', 0, 2, 3, '', '', '', '{}'),
('درلود،', 0, 2, 3, '', '', '', '{}'),
('نجاران', 0, 2, 0, '', '', '', '{}'),
('راوړل،', 0, 2, 0, '', '', '', '{}'),
('شوباب،', 0, 2, 0, '', '', '', '{}'),
('ایبحار،', 0, 2, 0, '', '', '', '{}'),
('الیشوع،', 0, 2, 0, '', '', '', '{}'),
('الیفالط،', 0, 2, 0, '', '', '', '{}'),
('ونیسي', 0, 2, 2, '', '', '', '{}'),
('هو،', 0, 2, 4, '', '', '', '{}'),
('فراسیم', 0, 2, 0, '', '', '', '{}'),
('بلسام', 0, 2, 0, '', '', '', '{}'),
('یوسي،', 0, 2, 1, '', '', '', '{}'),
('یوییل،', 0, 2, 0, '', '', '', '{}'),
('یوسي', 0, 2, 3, '', '', '', '{}'),
('ستنو', 0, 2, 0, '', '', '', '{}'),
('قرباني', 0, 2, 4, '', '', '', '{}'),
('غږولو', 0, 2, 0, '', '', '', '{}'),
('ودرولې', 0, 2, 0, '', '', '', '{}'),
('یحییل،', 0, 2, 0, '', '', '', '{}'),
('بنایاه،', 0, 2, 0, '', '', '', '{}'),
('حوسه', 0, 2, 0, '', '', '', '{}'),
('ګوره،', 0, 2, 0, '', '', '', '{}'),
('وټاکلې', 0, 2, 0, '', '', '', '{}'),
('تللې،', 0, 2, 0, '', '', '', '{}'),
('شوې،', 0, 2, 2, '', '', '', '{}'),
('رسیږي', 0, 2, 0, '', '', '', '{}'),
('موابیانو', 0, 2, 0, '', '', '', '{}'),
('ویشت', 0, 2, 0, '', '', '', '{}'),
('قرارګاوې', 0, 2, 0, '', '', '', '{}'),
('توعو', 0, 2, 0, '', '', '', '{}'),
('زرو،', 0, 2, 3, '', '', '', '{}'),
('ادومیانو', 0, 2, 0, '', 'unknown', '', '{"english": "", "pos": "unknown", "romanization": "", "r": null, "a": null, "i": null, "ts": ""}'),
('عمومي', 0, 2, 0, '', '', '', '{}'),
('منشي', 0, 2, 0, '', '', '', '{}'),
('خواخوږي', 0, 2, 1, '', '', '', '{}'),
('رالېږلي', 0, 2, 0, '', '', '', '{}'),
('دي؟', 0, 2, 15, '', '', '', '{}'),
('ونیول،', 0, 2, 0, '', '', '', '{}'),
('ږیرې', 0, 2, 0, '', '', '', '{}'),
('کالي', 0, 2, 5, '', '', '', '{}'),
('عمونیان', 0, 2, 0, '', '', '', '{}'),
('چلوونکي', 0, 2, 0, '', '', '', '{}'),
('ربه', 0, 2, 0, '', '', '', '{}'),
('قوماندې', 0, 2, 0, '', '', '', '{}'),
('ختیځه', 0, 2, 0, '', '', '', '{}'),
('شوفک', 0, 2, 0, '', '', '', '{}'),
('ماشک', 0, 2, 0, '', '', '', '{}'),
('کوش', 0, 2, 0, '', '', '', '{}'),
('رعمه', 0, 2, 0, '', '', '', '{}'),
('ددان', 0, 2, 0, '', '', '', '{}'),
('عیلام،', 0, 2, 0, '', '', '', '{}'),
('لود', 0, 2, 0, '', '', '', '{}'),
('شالح', 0, 2, 0, '', '', '', '{}'),
('اسماعیل', 0, 2, 0, '', '', '', '{}'),
('عیفر،', 0, 2, 0, '', '', '', '{}'),
('یعوش،', 0, 2, 0, '', '', '', '{}'),
('تیمان،', 0, 2, 0, '', '', '', '{}'),
('عمالیق', 0, 2, 0, '', '', '', '{}'),
('تمناع', 0, 2, 0, '', '', '', '{}'),
('زارح،', 0, 2, 0, '', '', '', '{}'),
('سعیر', 0, 2, 0, '', '', '', '{}'),
('دیشان', 0, 2, 0, '', '', '', '{}'),
('لوتان', 0, 2, 0, '', '', '', '{}'),
('حوري', 0, 2, 0, '', '', '', '{}'),
('ایه', 0, 2, 0, '', '', '', '{}'),
('عنه', 0, 2, 0, '', '', '', '{}'),
('قبیلوي', 0, 2, 0, '', '', '', '{}'),
('حوشاتي', 0, 2, 0, '', '', '', '{}'),
('نومېد', 0, 2, 0, '', '', '', '{}'),
('راوپاراوه', 0, 2, 0, '', '', '', '{}'),
('کېږدي', 0, 2, 1, '', '', '', '{}'),
('سزاګانو', 0, 2, 0, '', '', '', '{}'),
('نازله', 0, 2, 0, '', '', '', '{}'),
('یبوسي', 0, 2, 0, '', '', '', '{}'),
('اوسپنه', 0, 2, 0, '', '', '', '{}'),
('برنج', 0, 2, 0, '', '', '', '{}'),
('مواد', 0, 2, 0, '', '', '', '{}'),
('زویه،', 0, 2, 1, '', '', '', '{}'),
('اوسه،', 0, 2, 0, '', '', '', '{}'),
('لرګي،', 0, 2, 0, '', '', '', '{}'),
('کارګران', 0, 2, 0, '', '', '', '{}'),
('عمرونه', 0, 2, 0, '', '', '', '{}'),
('زیتام', 0, 2, 0, '', '', '', '{}'),
('یریا،', 0, 2, 0, '', '', '', '{}'),
('یقمعام', 0, 2, 0, '', '', '', '{}'),
('عیدر', 0, 2, 0, '', '', '', '{}'),
('کېدله،', 0, 2, 0, '', '', '', '{}'),
('اوړو،', 0, 2, 0, '', '', '', '{}'),
('اخترونو', 0, 2, 0, '', '', '', '{}'),
('مذهبي', 0, 2, 2, '', '', '', '{}'),
('وټاکي', 0, 2, 0, '', '', '', '{}'),
('ابیهو،', 0, 2, 0, '', '', '', '{}'),
('شلوموت', 0, 2, 0, '', '', '', '{}'),
('یحت', 0, 2, 0, '', '', '', '{}'),
('اساف،', 0, 2, 0, '', '', '', '{}'),
('شرنګېدونکي', 0, 2, 0, '', '', '', '{}'),
('نتنیا', 0, 2, 0, '', '', '', '{}'),
('شمعي،', 0, 2, 0, '', '', '', '{}'),
('یریموت،', 0, 2, 0, '', '', '', '{}'),
('روممتي', 0, 2, 0, '', '', '', '{}'),
('هوتیر', 0, 2, 0, '', '', '', '{}'),
('محزیوت', 0, 2, 0, '', '', '', '{}'),
('۲۸۸', 0, 2, 0, '', '', '', '{}'),
('سندرغاړي', 0, 2, 0, '', '', '', '{}'),
('څلورمه', 0, 2, 0, '', '', '', '{}'),
('پنځمه', 0, 2, 0, '', '', '', '{}'),
('نهمه', 0, 2, 0, '', '', '', '{}'),
('یوولسمه', 0, 2, 0, '', '', '', '{}'),
('دولسمه', 0, 2, 0, '', '', '', '{}'),
('عزر', 0, 2, 0, '', '', '', '{}'),
('وویني', 0, 2, 5, '', '', '', '{}'),
('ته،', 0, 2, 0, '', '', '', '{}'),
('ساتله', 0, 2, 0, '', '', '', '{}'),
('زکري', 0, 2, 0, '', '', '', '{}'),
('مشران،', 0, 2, 0, '', '', '', '{}'),
('زبدي', 0, 2, 0, '', '', '', '{}'),
('نطوفاتي', 0, 2, 0, '', '', '', '{}'),
('کلوب', 0, 2, 0, '', '', '', '{}'),
('لوېدیځو', 0, 2, 0, '', '', '', '{}'),
('یواش', 0, 2, 0, '', '', '', '{}'),
('اوښانو', 0, 2, 0, '', '', '', '{}'),
('اخیتوفل', 0, 2, 0, '', '', '', '{}'),
('څارویو', 0, 2, 0, '', '', '', '{}'),
('کړم،', 0, 2, 7, '', '', '', '{}'),
('پرېږدئ', 0, 2, 8, '', '', '', '{}'),
('اوفیر', 0, 2, 0, '', '', '', '{}'),
('شتمني', 0, 2, 1, '', '', '', '{}'),
('حکمراني', 0, 2, 0, '', '', '', '{}'),
('سیوري', 0, 2, 0, '', '', '', '{}'),
('وښایي', 0, 2, 5, '', '', '', '{}'),
('پورې،', 0, 2, 0, '', '', '', '{}'),
('پاچاهیو', 0, 2, 0, '', '', '', '{}'),
('شیله', 0, 2, 0, '', '', '', '{}'),
('ایتان،', 0, 2, 0, '', '', '', '{}'),
('کرمي', 0, 2, 0, '', '', '', '{}'),
('عزریا', 0, 2, 0, '', '', '', '{}'),
('عزوبې', 0, 2, 0, '', '', '', '{}'),
('سجوب', 0, 2, 0, '', '', '', '{}'),
('وزېږېدل', 0, 2, 0, '', '', '', '{}'),
('جشور', 0, 2, 0, '', '', '', '{}'),
('ښارګوټی', 0, 2, 0, '', '', '', '{}'),
('یاداع', 0, 2, 0, '', '', '', '{}'),
('ابیشور', 0, 2, 0, '', '', '', '{}'),
('ابیحایل', 0, 2, 0, '', '', '', '{}'),
('سلد', 0, 2, 0, '', '', '', '{}'),
('افایم', 0, 2, 0, '', '', '', '{}'),
('شیشان', 0, 2, 0, '', '', '', '{}'),
('درلودلې،', 0, 2, 0, '', '', '', '{}'),
('یرحاع', 0, 2, 0, '', '', '', '{}'),
('عتای', 0, 2, 0, '', '', '', '{}'),
('قورح،', 0, 2, 0, '', '', '', '{}'),
('عیفه', 0, 2, 0, '', '', '', '{}'),
('جازیز', 0, 2, 0, '', '', '', '{}'),
('شاعف', 0, 2, 0, '', '', '', '{}'),
('اوسېدلې،', 0, 2, 0, '', '', '', '{}'),
('حمت', 0, 2, 0, '', '', '', '{}'),
('وه؛', 0, 2, 0, '', '', '', '{}'),
('شکنیا', 0, 2, 0, '', '', '', '{}'),
('نعریا', 0, 2, 0, '', '', '', '{}'),
('الیوعینای،', 0, 2, 0, '', '', '', '{}'),
('عقوب،', 0, 2, 0, '', '', '', '{}'),
('یوحانان،', 0, 2, 0, '', '', '', '{}'),
('حلا', 0, 2, 0, '', '', '', '{}'),
('نعره', 0, 2, 0, '', '', '', '{}')
ON CONFLICT (pashto_word) DO UPDATE SET
  total_frequency = EXCLUDED.total_frequency,
  ot_frequency = EXCLUDED.ot_frequency,
  nt_frequency = EXCLUDED.nt_frequency,
  romanization = EXCLUDED.romanization,
  pos = EXCLUDED.pos,
  english_translation = EXCLUDED.english_translation,
  metadata = EXCLUDED.metadata,
  updated_at = now();