import json
import os
from typing import Dict, Any, Optional
from functools import lru_cache

APP_ROOT = os.path.dirname(os.path.abspath(__file__))
LEXICON_PATH = os.path.join(APP_ROOT, 'nouns_lexicon.json')

# Auto-detect simple noun patterns when lexicon entry missing, without
# importing the UI (avoid circular imports). Prefer the small fast index
# generated by normalize_dictionary_data.py.
FAST_DICT_INDEX_PATH = os.path.join(APP_ROOT, 'dictionary_fast_index.json')

def _normalize_pashto_char(text: str) -> str:
    if not isinstance(text, str):
        return text
    return text.replace('ي', 'ی').replace('ى', 'ی').replace('ئ', 'ی')

@lru_cache(maxsize=1)
def _load_fast_index() -> Dict[str, Any]:
    try:
        if os.path.exists(FAST_DICT_INDEX_PATH):
            with open(FAST_DICT_INDEX_PATH, 'r', encoding='utf-8') as f:
                return json.load(f)
    except Exception:
        return {}
    return {}

def _fast_dict_lookup(word: str) -> Dict[str, Any]:
    idx = _load_fast_index()
    if not idx:
        return {}
    by_p = idx.get('by_pashto', {})
    by_pn = idx.get('by_pashto_norm', {})
    if word in by_p:
        return by_p[word] or {}
    nkey = _normalize_pashto_char(word)
    return by_pn.get(nkey, {}) or {}

def _infer_noun_pattern_from_dict(lemma_ps: str) -> str:
    entry = _fast_dict_lookup(lemma_ps)
    pos = str(entry.get('pos_norm') or entry.get('pos') or '').lower()
    rom = entry.get('rom', '') or ''
    if not pos or 'n' not in pos:
        return ''
    if rom.endswith('áy'):
        return 'stressed_ay'
    return ''


def load_lexicon() -> Dict[str, Any]:
    try:
        with open(LEXICON_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return {}


NOUNS: Dict[str, Any] = load_lexicon()


def infer_default_pattern(lemma: str) -> str:
    return 'masc_basic_consonant'


# --- Pattern implementations ---

def _pattern_1_basic(lemma: str) -> Dict[str, tuple]:
    # Pattern #1 Basic. If feminine (ends with ـه), use feminine slots; else masculine.
    if lemma.endswith('ه'):
        base = lemma[:-1]
        return {
            'plain_f': (base + 'ه', ''),
            'inflection_1_f': (base + 'ې', ''),
            'inflection_2_f': (base + 'و', ''),
            'vocative_f': (base + 'ې', ''),
            'vocative_pl_f': (base + 'و', ''),
        }
    else:
        stem = lemma
        return {
            'plain_m': (stem, ''),
            'inflection_1_m': (stem, ''),
            'inflection_2_m': (stem + 'و', ''),
            # vocatives often not distinct for masc here; omit unless needed
        }


def _pattern_4_pashtoon(stem: str) -> Dict[str, tuple]:
    fem_base = (stem[:-2] + 'نه') if stem.endswith('ون') else (stem + 'ه')
    return {
        'plain_m': (stem, ''),
        'plain_f': (fem_base, ''),
        'inflection_1_m': (stem[:-2] + 'انه' if stem.endswith('ون') else stem + 'انه', ''),  # پښتانه
        'inflection_1_f': (fem_base[:-1] + 'ې', ''),  # پښتنې
        'inflection_2_m': (stem[:-2] + 'نو' if stem.endswith('ون') else stem + 'نو', ''),   # پښتنو
        'vocative_m': (stem + 'ه', ''),        # پښتونه
        'vocative_f': (fem_base[:-1] + 'ې', ''),
    }


def _pattern_2_unstressed_y(lemma: str) -> Dict[str, tuple]:
    stem = lemma[:-1] if lemma.endswith('ی') else lemma
    return {
        'plain_m': (stem + 'ی', ''),
        'plain_f': (stem + 'ې', ''),
        'inflection_1_m': (stem + 'ي', ''),
        'inflection_1_f': (stem + 'ې', ''),
        'inflection_2': (stem + 'یو', ''),
    }


def _pattern_3_stressed_ay(lemma: str) -> Dict[str, tuple]:
    stem = lemma[:-1] if lemma.endswith('ی') else lemma
    return {
        'plain_m': (stem + 'ی', ''),
        'plain_f': (stem + 'ۍ', ''),
        'inflection_1_m': (stem + 'ي', ''),
        'inflection_1_f': (stem + 'ۍ', ''),
        'inflection_2': (stem + 'یو', ''),
    }


def _pattern_5_short_squish(stem: str) -> Dict[str, tuple]:
    return {
        'plain_m': (stem, ''),
        'plain_f': (stem + 'ه', ''),
        'inflection_1_m': (stem + 'ه', ''),
        'inflection_1_f': (stem + 'ې', ''),
        'inflection_2': (stem + 'و', ''),
    }


def _pattern_half_fem_inanim_ee(lemma: str) -> Dict[str, tuple]:
    stem = lemma[:-1] if (lemma.endswith('ي') or lemma.endswith('ی')) else lemma
    return {
        'plain_f': (stem + 'ي', ''),
        'inflection_1_f': (stem + 'ۍ', ''),
        'inflection_2_f': (stem + 'یو', ''),
    }


def inflect_noun(lemma: str, pattern: Optional[str] = None) -> Dict[str, Any]:
    entry = NOUNS.get(lemma, {})
    pat = pattern or entry.get('pattern') or infer_default_pattern(lemma)

    if pat in ('masc_basic_consonant', 'basic'):
        forms = _pattern_1_basic(lemma)
    elif pat == 'pashtoon':
        forms = _pattern_4_pashtoon(lemma)
    elif pat == 'unstressed_y':
        forms = _pattern_2_unstressed_y(lemma)
    elif pat == 'stressed_ay':
        forms = _pattern_3_stressed_ay(lemma)
    elif pat == 'short_squish':
        forms = _pattern_5_short_squish(lemma)
    elif pat == 'fem_inanim_ee':
        forms = _pattern_half_fem_inanim_ee(lemma)
    else:
        forms = {}

    return {
        'meta': {
            'lemma': lemma,
            'pattern': pat,
            'pattern_info': entry.get('pattern_info', ''),
        },
        'forms': forms,
    }


# --- Helpers to map forms to lemmas ---

def build_noun_forms_index() -> Dict[str, str]:
    index: Dict[str, str] = {}
    for lemma in NOUNS.keys():
        data = inflect_noun(lemma)
        # include the lemma itself
        index[lemma] = lemma
        for ps, _ in data['forms'].values():
            index[ps] = lemma
    return index


def find_noun_lemma_for_form(form_ps: str) -> str:
    try:
        idx = build_noun_forms_index()
        return idx.get(form_ps, '')
    except Exception:
        return ''


# --- Classification helpers (Type 1-6 mapping) ---

_PATTERN_TO_TYPE = {
    'masc_basic_consonant': 1,  # baseline masculine/feminine simple endings
    'basic': 1,
    'unstressed_y': 2,
    'stressed_ay': 3,
    'pashtoon': 4,
    'short_squish': 5,
    'fem_inanim_ee': 6,
}


def classify_inflection_type(lemma: str, pattern: Optional[str] = None) -> int:
    """Return an integer 1..6 indicating noun inflection type.

    Mapping is a pragmatic approximation based on our internal pattern names.
    If an exact pattern is not available, we try to infer from the lemma shape.
    """
    entry = NOUNS.get(lemma, {})
    pat = pattern or entry.get('pattern') or infer_default_pattern(lemma)
    if pat in _PATTERN_TO_TYPE:
        return _PATTERN_TO_TYPE[pat]
    # Heuristics when pattern unknown
    if lemma.endswith('ه'):
        return 1
    if lemma.endswith('ی') or lemma.endswith('ي'):
        # Without stress info, default to 2
        return 2
    if lemma.endswith('ون'):
        return 4
    return 1
