-- Comprehensive update of biblical names
-- Generated by comprehensive-name-search.py
-- Found 32 names that need updating

-- یهودا (ID: 11877) - Update from unknown/None to proper_noun: Judah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Judah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهودا';

-- منسی (ID: 40508) - Insert: Manasseh
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('منسی', 'proper_noun', 'n. prop.', 'Manasseh', 0, '[]');

-- الیشع (ID: 13301) - Update from unknown/None to proper_noun: Elisha
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Elisha', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'الیشع';

-- جدعون (ID: 12699) - Update from unknown/None to proper_noun: Gideon
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Gideon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'جدعون';

-- نفتالی (ID: 40613) - Insert: Naphtali
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('نفتالی', 'proper_noun', 'n. prop.', 'Naphtali', 0, '[]');

-- آسا (ID: 13536) - Update from unknown/None to proper_noun: Asa
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Asa', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'آسا';

-- زبولون (ID: 13653) - Update from unknown/None to proper_noun: Zebulun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zebulun', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زبولون';

-- شمشون (ID: 13693) - Update from unknown/None to proper_noun: Samson
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Samson', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'شمشون';

-- یهویاکین (ID: 17736) - Update from unknown/None to proper_noun: Jehoiachin
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoiachin', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهویاکین';

-- تیموتاوس (ID: 16408) - Update from unknown/None to proper_noun: Timothy
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Timothy', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'تیموتاوس';

-- سیلاس (ID: 15871) - Update from unknown/None to proper_noun: Silas
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Silas', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'سیلاس';

-- رحبعام (ID: 15096) - Update from unknown/None to proper_noun: Rehoboam
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Rehoboam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'رحبعام';

-- ابیا (ID: 17215) - Update from unknown/None to proper_noun: Abijah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abijah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیا';

-- یهوشافاط (ID: 16477) - Update from unknown/None to proper_noun: Jehoshaphat
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoshaphat', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوشافاط';

-- یوآش (ID: 14660) - Update from unknown/None to proper_noun: Joash
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Joash', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوآش';

-- جاد (ID: 12731) - Update from unknown/n. m. to proper_noun: Gad
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Gad', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'جاد';

-- ناتان (ID: 17712) - Update from unknown/None to proper_noun: Nathan
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nathan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ناتان';

-- اخزیا (ID: 15481) - Update from unknown/None to proper_noun: Ahaziah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ahaziah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اخزیا';

-- اشعیا (ID: 14337) - Update from unknown/None to proper_noun: Isaiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Isaiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اشعیا';

-- یوشیا (ID: 15180) - Update from unknown/None to proper_noun: Josiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Josiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوشیا';

-- میکال (ID: 30436) - Update from verb/v. to proper_noun: Michal
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Michal', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'میکال';

-- یورام (ID: 18011) - Update from unknown/None to proper_noun: Jehoram
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoram', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یورام';

-- یوناتان (ID: 18672) - Update from unknown/None to proper_noun: Jonathan
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jonathan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوناتان';

-- بتشبع (ID: 35025) - Update from unknown/None to proper_noun: Bathsheba
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Bathsheba', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'بتشبع';

-- اندریاس (ID: 20958) - Update from unknown/None to proper_noun: Andrew
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Andrew', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اندریاس';

-- توما (ID: 17196) - Update from unknown/None to proper_noun: Thomas
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Thomas', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'توما';

-- یفتاح (ID: 16545) - Update from unknown/None to proper_noun: Jephthah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jephthah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یفتاح';

-- عزرا (ID: 14312) - Update from unknown/None to proper_noun: Ezra
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ezra', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عزرا';

-- زکریا (ID: 15265) - Update from unknown/None to proper_noun: Zechariah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zechariah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زکریا';

-- مرتا (ID: 16790) - Update from unknown/None to proper_noun: Martha
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Martha', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مرتا';

-- ابرام (ID: 14112) - Update from unknown/None to proper_noun: Abram
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abram', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابرام';

-- حام (ID: 18070) - Update from unknown/None to proper_noun: Ham
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ham', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حام';
