-- Comprehensive update of biblical names - 100+ names
-- Generated by comprehensive-name-search.py + manual additions
-- Found names from multiple search strategies

-- Common Kings and Leaders
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Judah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهودا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Manasseh', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'منسی';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Elisha', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'الیشع';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Gideon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'جدعون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Naphtali', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'نفتالی';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Asa', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'آسا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zebulun', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زبولون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Samson', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'شمشون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoiachin', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهویاکین';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Timothy', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'تیموتاوس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Silas', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'سیلاس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Rehoboam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'رحبعام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abijah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoshaphat', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوشافاط';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Joash', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوآش';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Gad', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'جاد';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nathan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ناتان';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ahaziah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اخزیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Isaiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اشعیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Josiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوشیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Michal', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'میکال';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoram', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یورام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jonathan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوناتان';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Bathsheba', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'بتشبع';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Andrew', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اندریاس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Thomas', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'توما';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jephthah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یفتاح';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ezra', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عزرا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zechariah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زکریا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Martha', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مرتا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abram', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابرام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ham', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حام';

-- Additional names found in queries
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Adam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'آدم';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Eve', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حوا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Cain', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'قابیل';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'هابیل';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Lot', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'لوط';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ishmael', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اسماعیل';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Rebekah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ربکا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Laban', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'لابان';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Dinah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'دینا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Adonijah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ادونیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zerubbabel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زروبابل';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nehemiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'نحمیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Matthew', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'متی';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Titus', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'تیتوس';

-- Abi- names (names starting with Abi-)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abimelech', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیملک';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abiezer', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیعزر';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abishai', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیشای';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abiram', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیرام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abiathar', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیاتار';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abidan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابیدان';

-- Jeho- names (names starting with Jeho-)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoiada', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهویاداع';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoiakim', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهویاقیم';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoahaz', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوآحاز';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehohanan', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوحانان';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehozadak', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوصاداق';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehoshaphat', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یهوشبع';

-- Other names found
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jairim', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعاریم';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jezer', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعزیر';

-- Additional names found in queries
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ahaz', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'احاز';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Asher', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'آشر';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Issachar', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یساکار';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zedekiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'صدقیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ehud', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ایهود';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Elizabeth', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'الیزابت';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Amos', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عاموس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Hosea', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'هوشع';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nicodemus', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'نیکودیموس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Uzziah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عزریا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Deborah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'دبوره';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jotham', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوتام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nimrod', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'نمرود';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Elon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ایلون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abdon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عبدون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Hannah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حنا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nahum', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ناحوم';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Habakkuk', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حبقوق';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Amon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'آمون';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Obadiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عوبدیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Shem', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'سام';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Methuselah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'متوشالح';

-- Prophet names
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jonah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یونس';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Micah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'میکا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Hezekiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حزقیا';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zephaniah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'صفنیاه';
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Haggai', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'حجى';

