-- =========================================
-- CURATED TOPICS ENTRIES - BUILT FROM WORDS
-- Generated by matching words from word_frequencies to categories
-- Words can belong to multiple categories
-- =========================================

-- Clear existing mappings
DELETE FROM category_verse_mappings;

-- Insert curated entries
-- grammar_conjunctions (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar_conjunctions', 'نو', 1040, 'Genesis 36:24', 'yousafzai2019', 'OT', 'Genesis', 36, 24),
('grammar_conjunctions', 'نو', 625, 'Genesis 24:47', 'yousafzai2019', 'OT', 'Genesis', 24, 47),
('grammar_conjunctions', 'اګر', 1420, 'Genesis 48:14', 'yousafzai2019', 'OT', 'Genesis', 48, 14),
('grammar_conjunctions', 'اګر', 1217, 'Genesis 42:8', 'yousafzai2019', 'OT', 'Genesis', 42, 8);

-- grammar (28 entries from 14 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar', 'نو', 1788, 'Exodus 12:33', 'yousafzai2019', 'OT', 'Exodus', 12, 33),
('grammar', 'نو', 1040, 'Genesis 36:24', 'yousafzai2019', 'OT', 'Genesis', 36, 24),
('grammar', 'له', 1103, 'Genesis 38:25', 'yousafzai2019', 'OT', 'Genesis', 38, 25),
('grammar', 'له', 1065, 'Genesis 37:23', 'yousafzai2019', 'OT', 'Genesis', 37, 23),
('grammar', 'زما', 586, 'Genesis 24:8', 'yousafzai2019', 'OT', 'Genesis', 24, 8),
('grammar', 'زما', 323, 'Genesis 13:8', 'yousafzai2019', 'OT', 'Genesis', 13, 8),
('grammar', 'ستا', 1086, 'Genesis 38:8', 'yousafzai2019', 'OT', 'Genesis', 38, 8),
('grammar', 'ستا', 1074, 'Genesis 37:32', 'yousafzai2019', 'OT', 'Genesis', 37, 32),
('grammar', 'کله', 2407, 'Exodus 33:8', 'yousafzai2019', 'OT', 'Exodus', 33, 8),
('grammar', 'کله', 1404, 'Genesis 47:29', 'yousafzai2019', 'OT', 'Genesis', 47, 29),
('grammar', 'مونږ', 1192, 'Genesis 41:38', 'yousafzai2019', 'OT', 'Genesis', 41, 38),
('grammar', 'مونږ', 1544, 'Exodus 3:18', 'yousafzai2019', 'OT', 'Exodus', 3, 18),
('grammar', 'زمونږ', 2431, 'Exodus 34:9', 'yousafzai2019', 'OT', 'Exodus', 34, 9),
('grammar', 'زمونږ', 972, 'Genesis 34:10', 'yousafzai2019', 'OT', 'Genesis', 34, 10),
('grammar', 'هلته', 1754, 'Exodus 11:7', 'yousafzai2019', 'OT', 'Exodus', 11, 7),
('grammar', 'هلته', 1368, 'Genesis 46:27', 'yousafzai2019', 'OT', 'Genesis', 46, 27),
('grammar', 'اوس', 1224, 'Genesis 42:15', 'yousafzai2019', 'OT', 'Genesis', 42, 15),
('grammar', 'اوس', 1371, 'Genesis 46:30', 'yousafzai2019', 'OT', 'Genesis', 46, 30),
('grammar', 'دومره', 683, 'Genesis 26:4', 'yousafzai2019', 'OT', 'Genesis', 26, 4),
('grammar', 'دومره', 992, 'Genesis 34:30', 'yousafzai2019', 'OT', 'Genesis', 34, 30),
('grammar', 'دلته', 1321, 'Genesis 45:8', 'yousafzai2019', 'OT', 'Genesis', 45, 8),
('grammar', 'دلته', 1139, 'Genesis 40:8', 'yousafzai2019', 'OT', 'Genesis', 40, 8),
('grammar', 'ته', 1738, 'Exodus 10:20', 'yousafzai2019', 'OT', 'Exodus', 10, 20),
('grammar', 'ته', 2272, 'Exodus 29:10', 'yousafzai2019', 'OT', 'Exodus', 29, 10),
('grammar', 'اګر', 1217, 'Genesis 42:8', 'yousafzai2019', 'OT', 'Genesis', 42, 8),
('grammar', 'اګر', 1420, 'Genesis 48:14', 'yousafzai2019', 'OT', 'Genesis', 48, 14),
('grammar', 'درسره', 927, 'Genesis 32:17', 'yousafzai2019', 'OT', 'Genesis', 32, 17),
('grammar', 'درسره', 956, 'Genesis 33:14', 'yousafzai2019', 'OT', 'Genesis', 33, 14);

-- grammar_prepositions (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar_prepositions', 'له', 1103, 'Genesis 38:25', 'yousafzai2019', 'OT', 'Genesis', 38, 25),
('grammar_prepositions', 'له', 2495, 'Exodus 36:3', 'yousafzai2019', 'OT', 'Exodus', 36, 3),
('grammar_prepositions', 'ته', 367, 'Genesis 15:10', 'yousafzai2019', 'OT', 'Genesis', 15, 10),
('grammar_prepositions', 'ته', 1212, 'Genesis 42:3', 'yousafzai2019', 'OT', 'Genesis', 42, 3);

-- grammar_pronouns (8 entries from 4 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar_pronouns', 'زما', 219, 'Genesis 9:17', 'yousafzai2019', 'OT', 'Genesis', 9, 17),
('grammar_pronouns', 'زما', 1538, 'Exodus 3:12', 'yousafzai2019', 'OT', 'Exodus', 3, 12),
('grammar_pronouns', 'ستا', 1086, 'Genesis 38:8', 'yousafzai2019', 'OT', 'Genesis', 38, 8),
('grammar_pronouns', 'ستا', 529, 'Genesis 21:25', 'yousafzai2019', 'OT', 'Genesis', 21, 25),
('grammar_pronouns', 'مونږ', 59, 'Genesis 3:3', 'yousafzai2019', 'OT', 'Genesis', 3, 3),
('grammar_pronouns', 'مونږ', 689, 'Genesis 26:10', 'yousafzai2019', 'OT', 'Genesis', 26, 10),
('grammar_pronouns', 'زمونږ', 2431, 'Exodus 34:9', 'yousafzai2019', 'OT', 'Exodus', 34, 9),
('grammar_pronouns', 'زمونږ', 1494, 'Exodus 1:9', 'yousafzai2019', 'OT', 'Exodus', 1, 9);

-- states_quality (8 entries from 4 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('states_quality', 'پاک', 2436, 'Exodus 34:14', 'yousafzai2019', 'OT', 'Exodus', 34, 14),
('states_quality', 'پاک', 1721, 'Exodus 10:3', 'yousafzai2019', 'OT', 'Exodus', 10, 3),
('states_quality', 'ښه', 1517, 'Exodus 2:14', 'yousafzai2019', 'OT', 'Exodus', 2, 14),
('states_quality', 'ښه', 913, 'Genesis 31:55', 'yousafzai2019', 'OT', 'Genesis', 31, 55),
('states_quality', 'بد', 48, 'Genesis 2:17', 'yousafzai2019', 'OT', 'Genesis', 2, 17),
('states_quality', 'بد', 2067, 'Exodus 22:22', 'yousafzai2019', 'OT', 'Exodus', 22, 22),
('states_quality', 'مقدس', 2250, 'Exodus 28:29', 'yousafzai2019', 'OT', 'Exodus', 28, 29),
('states_quality', 'مقدس', 2476, 'Exodus 35:19', 'yousafzai2019', 'OT', 'Exodus', 35, 19);

-- states (27 entries from 14 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('states', 'پاک', 18, 'Genesis 1:18', 'yousafzai2019', 'OT', 'Genesis', 1, 18),
('states', 'پاک', 1573, 'Exodus 4:27', 'yousafzai2019', 'OT', 'Exodus', 4, 27),
('states', 'لوی', 1193, 'Genesis 41:39', 'yousafzai2019', 'OT', 'Genesis', 41, 39),
('states', 'لوی', 522, 'Genesis 21:18', 'yousafzai2019', 'OT', 'Genesis', 21, 18),
('states', 'ژوند', 2042, 'Exodus 21:30', 'yousafzai2019', 'OT', 'Exodus', 21, 30),
('states', 'ژوند', 390, 'Genesis 16:12', 'yousafzai2019', 'OT', 'Genesis', 16, 12),
('states', 'مړ', 1222, 'Genesis 42:13', 'yousafzai2019', 'OT', 'Genesis', 42, 13),
('states', 'مړ', 497, 'Genesis 20:7', 'yousafzai2019', 'OT', 'Genesis', 20, 7),
('states', 'مرګ', 1735, 'Exodus 10:17', 'yousafzai2019', 'OT', 'Exodus', 10, 17),
('states', 'مرګ', 1427, 'Genesis 48:21', 'yousafzai2019', 'OT', 'Genesis', 48, 21),
('states', 'ښه', 435, 'Genesis 18:16', 'yousafzai2019', 'OT', 'Genesis', 18, 16),
('states', 'ښه', 913, 'Genesis 31:55', 'yousafzai2019', 'OT', 'Genesis', 31, 55),
('states', 'بد', 2067, 'Exodus 22:22', 'yousafzai2019', 'OT', 'Exodus', 22, 22),
('states', 'بد', 2755, 'Leviticus 5:4', 'yousafzai2019', 'OT', 'Leviticus', 5, 4),
('states', 'مقدس', 2250, 'Exodus 28:29', 'yousafzai2019', 'OT', 'Exodus', 28, 29),
('states', 'مقدس', 2295, 'Exodus 29:33', 'yousafzai2019', 'OT', 'Exodus', 29, 33),
('states', 'لږ', 1285, 'Genesis 44:4', 'yousafzai2019', 'OT', 'Genesis', 44, 4),
('states', 'لږ', 1317, 'Genesis 45:4', 'yousafzai2019', 'OT', 'Genesis', 45, 4),
('states', 'لوړ', 2540, 'Exodus 37:10', 'yousafzai2019', 'OT', 'Exodus', 37, 10),
('states', 'لوړ', 175, 'Genesis 7:19', 'yousafzai2019', 'OT', 'Genesis', 7, 19),
('states', 'نوی', 1493, 'Exodus 1:8', 'yousafzai2019', 'OT', 'Exodus', 1, 8),
('states', 'اوږد', 2135, 'Exodus 25:10', 'yousafzai2019', 'OT', 'Exodus', 25, 10),
('states', 'اوږد', 1730, 'Exodus 10:12', 'yousafzai2019', 'OT', 'Exodus', 10, 12),
('states', 'زوړ', 409, 'Genesis 17:17', 'yousafzai2019', 'OT', 'Genesis', 17, 17),
('states', 'زوړ', 513, 'Genesis 21:7', 'yousafzai2019', 'OT', 'Genesis', 21, 7),
('states', 'وړوکی', 472, 'Genesis 19:20', 'yousafzai2019', 'OT', 'Genesis', 19, 20),
('states', 'وړوکی', 1092, 'Genesis 38:14', 'yousafzai2019', 'OT', 'Genesis', 38, 14);

-- buildings (13 entries from 7 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('buildings', 'کور', 1113, 'Genesis 39:5', 'yousafzai2019', 'OT', 'Genesis', 39, 5),
('buildings', 'کور', 454, 'Genesis 19:2', 'yousafzai2019', 'OT', 'Genesis', 19, 2),
('buildings', 'ښار', 468, 'Genesis 19:16', 'yousafzai2019', 'OT', 'Genesis', 19, 16),
('buildings', 'ښار', 267, 'Genesis 11:4', 'yousafzai2019', 'OT', 'Genesis', 11, 4),
('buildings', 'دېوال', 1450, 'Genesis 49:22', 'yousafzai2019', 'OT', 'Genesis', 49, 22),
('buildings', 'تخت', 1784, 'Exodus 12:29', 'yousafzai2019', 'OT', 'Exodus', 12, 29),
('buildings', 'تخت', 2539, 'Exodus 37:9', 'yousafzai2019', 'OT', 'Exodus', 37, 9),
('buildings', 'دروازه', 462, 'Genesis 19:10', 'yousafzai2019', 'OT', 'Genesis', 19, 10),
('buildings', 'دروازه', 2215, 'Exodus 27:13', 'yousafzai2019', 'OT', 'Exodus', 27, 13),
('buildings', 'خېمه', 2510, 'Exodus 36:18', 'yousafzai2019', 'OT', 'Exodus', 36, 18),
('buildings', 'خېمه', 2219, 'Exodus 27:19', 'yousafzai2019', 'OT', 'Exodus', 27, 19),
('buildings', 'کړکۍ', 687, 'Genesis 26:8', 'yousafzai2019', 'OT', 'Genesis', 26, 8),
('buildings', 'کړکۍ', 186, 'Genesis 8:6', 'yousafzai2019', 'OT', 'Genesis', 8, 6);

-- family_male (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('family_male', 'زوی', 118, 'Genesis 5:12', 'yousafzai2019', 'OT', 'Genesis', 5, 12),
('family_male', 'زوی', 664, 'Genesis 25:19', 'yousafzai2019', 'OT', 'Genesis', 25, 19),
('family_male', 'پلار', 1020, 'Genesis 35:27', 'yousafzai2019', 'OT', 'Genesis', 35, 27),
('family_male', 'پلار', 1033, 'Genesis 36:15', 'yousafzai2019', 'OT', 'Genesis', 36, 15),
('family_male', 'ورور', 1317, 'Genesis 45:4', 'yousafzai2019', 'OT', 'Genesis', 45, 4),
('family_male', 'ورور', 1229, 'Genesis 42:20', 'yousafzai2019', 'OT', 'Genesis', 42, 20);

-- family (14 entries from 7 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('family', 'زوی', 2580, 'Exodus 38:23', 'yousafzai2019', 'OT', 'Exodus', 38, 23),
('family', 'زوی', 664, 'Genesis 25:19', 'yousafzai2019', 'OT', 'Genesis', 25, 19),
('family', 'پلار', 1020, 'Genesis 35:27', 'yousafzai2019', 'OT', 'Genesis', 35, 27),
('family', 'پلار', 1415, 'Genesis 48:9', 'yousafzai2019', 'OT', 'Genesis', 48, 9),
('family', 'ورور', 1301, 'Genesis 44:20', 'yousafzai2019', 'OT', 'Genesis', 44, 20),
('family', 'ورور', 1222, 'Genesis 42:13', 'yousafzai2019', 'OT', 'Genesis', 42, 13),
('family', 'لور', 1356, 'Genesis 46:15', 'yousafzai2019', 'OT', 'Genesis', 46, 15),
('family', 'لور', 490, 'Genesis 19:38', 'yousafzai2019', 'OT', 'Genesis', 19, 38),
('family', 'بچی', 1503, 'Exodus 1:22', 'yousafzai2019', 'OT', 'Exodus', 1, 22),
('family', 'بچی', 1760, 'Exodus 12:3', 'yousafzai2019', 'OT', 'Exodus', 12, 3),
('family', 'خپلوان', 296, 'Genesis 12:1', 'yousafzai2019', 'OT', 'Genesis', 12, 1),
('family', 'خپلوان', 1566, 'Exodus 4:18', 'yousafzai2019', 'OT', 'Exodus', 4, 18),
('family', 'نمسۍ', 1032, 'Genesis 36:14', 'yousafzai2019', 'OT', 'Genesis', 36, 14),
('family', 'نمسۍ', 1348, 'Genesis 46:7', 'yousafzai2019', 'OT', 'Genesis', 46, 7);

-- time_periods (10 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('time_periods', 'وخت', 1179, 'Genesis 41:25', 'yousafzai2019', 'OT', 'Genesis', 41, 25),
('time_periods', 'وخت', 2582, 'Exodus 38:25', 'yousafzai2019', 'OT', 'Exodus', 38, 25),
('time_periods', 'ورځ', 1771, 'Exodus 12:14', 'yousafzai2019', 'OT', 'Exodus', 12, 14),
('time_periods', 'ورځ', 542, 'Genesis 22:4', 'yousafzai2019', 'OT', 'Genesis', 22, 4),
('time_periods', 'شپه', 493, 'Genesis 20:3', 'yousafzai2019', 'OT', 'Genesis', 20, 3),
('time_periods', 'شپه', 1751, 'Exodus 11:4', 'yousafzai2019', 'OT', 'Exodus', 11, 4),
('time_periods', 'ماښام', 453, 'Genesis 19:1', 'yousafzai2019', 'OT', 'Genesis', 19, 1),
('time_periods', 'ماښام', 1455, 'Genesis 49:27', 'yousafzai2019', 'OT', 'Genesis', 49, 27),
('time_periods', 'موده', 558, 'Genesis 22:20', 'yousafzai2019', 'OT', 'Genesis', 22, 20),
('time_periods', 'موده', 994, 'Genesis 35:1', 'yousafzai2019', 'OT', 'Genesis', 35, 1);

-- time (19 entries from 11 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('time', 'وخت', 1370, 'Genesis 46:29', 'yousafzai2019', 'OT', 'Genesis', 46, 29),
('time', 'وخت', 1105, 'Genesis 38:27', 'yousafzai2019', 'OT', 'Genesis', 38, 27),
('time', 'ورځ', 194, 'Genesis 8:14', 'yousafzai2019', 'OT', 'Genesis', 8, 14),
('time', 'ورځ', 542, 'Genesis 22:4', 'yousafzai2019', 'OT', 'Genesis', 22, 4),
('time', 'اوس', 1582, 'Exodus 5:5', 'yousafzai2019', 'OT', 'Exodus', 5, 5),
('time', 'اوس', 1010, 'Genesis 35:17', 'yousafzai2019', 'OT', 'Genesis', 35, 17),
('time', 'کال', 2095, 'Exodus 23:19', 'yousafzai2019', 'OT', 'Exodus', 23, 19),
('time', 'کال', 2448, 'Exodus 34:26', 'yousafzai2019', 'OT', 'Exodus', 34, 26),
('time', 'شپه', 493, 'Genesis 20:3', 'yousafzai2019', 'OT', 'Genesis', 20, 3),
('time', 'شپه', 380, 'Genesis 16:2', 'yousafzai2019', 'OT', 'Genesis', 16, 2),
('time', 'ماښام', 453, 'Genesis 19:1', 'yousafzai2019', 'OT', 'Genesis', 19, 1),
('time', 'ماښام', 2221, 'Exodus 27:21', 'yousafzai2019', 'OT', 'Exodus', 27, 21),
('time', 'موده', 1115, 'Genesis 39:7', 'yousafzai2019', 'OT', 'Genesis', 39, 7),
('time', 'موده', 994, 'Genesis 35:1', 'yousafzai2019', 'OT', 'Genesis', 35, 1),
('time', 'سبا', 2424, 'Exodus 34:2', 'yousafzai2019', 'OT', 'Exodus', 34, 2),
('time', 'سبا', 1703, 'Exodus 9:18', 'yousafzai2019', 'OT', 'Exodus', 9, 18),
('time', 'اوړی', 202, 'Genesis 8:22', 'yousafzai2019', 'OT', 'Genesis', 8, 22),
('time', 'هفته', 2088, 'Exodus 23:12', 'yousafzai2019', 'OT', 'Exodus', 23, 12),
('time', 'ژمی', 202, 'Genesis 8:22', 'yousafzai2019', 'OT', 'Genesis', 8, 22);

-- miscellaneous (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('miscellaneous', 'وخت', 526, 'Genesis 21:22', 'yousafzai2019', 'OT', 'Genesis', 21, 22),
('miscellaneous', 'وخت', 2582, 'Exodus 38:25', 'yousafzai2019', 'OT', 'Exodus', 38, 25);

-- questions (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('questions', 'څنګه', 1337, 'Genesis 45:24', 'yousafzai2019', 'OT', 'Genesis', 45, 24),
('questions', 'څنګه', 2297, 'Exodus 29:35', 'yousafzai2019', 'OT', 'Exodus', 29, 35),
('questions', 'ولې', 1253, 'Genesis 43:6', 'yousafzai2019', 'OT', 'Genesis', 43, 6),
('questions', 'ولې', 609, 'Genesis 24:31', 'yousafzai2019', 'OT', 'Genesis', 24, 31),
('questions', 'پوښتنه', 1237, 'Genesis 42:28', 'yousafzai2019', 'OT', 'Genesis', 42, 28),
('questions', 'پوښتنه', 1274, 'Genesis 43:27', 'yousafzai2019', 'OT', 'Genesis', 43, 27);

-- grammar_adverbs (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar_adverbs', 'هلته', 2020, 'Exodus 21:6', 'yousafzai2019', 'OT', 'Exodus', 21, 6),
('grammar_adverbs', 'هلته', 655, 'Genesis 25:10', 'yousafzai2019', 'OT', 'Genesis', 25, 10),
('grammar_adverbs', 'اوس', 486, 'Genesis 19:34', 'yousafzai2019', 'OT', 'Genesis', 19, 34),
('grammar_adverbs', 'اوس', 1371, 'Genesis 46:30', 'yousafzai2019', 'OT', 'Genesis', 46, 30),
('grammar_adverbs', 'دلته', 1599, 'Exodus 5:22', 'yousafzai2019', 'OT', 'Exodus', 5, 22),
('grammar_adverbs', 'دلته', 1139, 'Genesis 40:8', 'yousafzai2019', 'OT', 'Genesis', 40, 8);

-- position (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('position', 'هلته', 691, 'Genesis 26:12', 'yousafzai2019', 'OT', 'Genesis', 26, 12),
('position', 'هلته', 2020, 'Exodus 21:6', 'yousafzai2019', 'OT', 'Exodus', 21, 6),
('position', 'دلته', 585, 'Genesis 24:7', 'yousafzai2019', 'OT', 'Genesis', 24, 7),
('position', 'دلته', 1321, 'Genesis 45:8', 'yousafzai2019', 'OT', 'Genesis', 45, 8),
('position', 'لرې', 2433, 'Exodus 34:11', 'yousafzai2019', 'OT', 'Exodus', 34, 11),
('position', 'لرې', 145, 'Genesis 6:7', 'yousafzai2019', 'OT', 'Genesis', 6, 7);

-- spatial (17 entries from 9 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('spatial', 'هلته', 1368, 'Genesis 46:27', 'yousafzai2019', 'OT', 'Genesis', 46, 27),
('spatial', 'هلته', 1464, 'Genesis 50:5', 'yousafzai2019', 'OT', 'Genesis', 50, 5),
('spatial', 'دلته', 1599, 'Exodus 5:22', 'yousafzai2019', 'OT', 'Exodus', 5, 22),
('spatial', 'دلته', 1139, 'Genesis 40:8', 'yousafzai2019', 'OT', 'Genesis', 40, 8),
('spatial', 'لرې', 542, 'Genesis 22:4', 'yousafzai2019', 'OT', 'Genesis', 22, 4),
('spatial', 'لرې', 2433, 'Exodus 34:11', 'yousafzai2019', 'OT', 'Exodus', 34, 11),
('spatial', 'بهر', 2532, 'Exodus 37:2', 'yousafzai2019', 'OT', 'Exodus', 37, 2),
('spatial', 'بهر', 1534, 'Exodus 3:8', 'yousafzai2019', 'OT', 'Exodus', 3, 8),
('spatial', 'وروستو', 338, 'Genesis 14:5', 'yousafzai2019', 'OT', 'Genesis', 14, 5),
('spatial', 'وروستو', 539, 'Genesis 22:1', 'yousafzai2019', 'OT', 'Genesis', 22, 1),
('spatial', 'شا', 2187, 'Exodus 26:22', 'yousafzai2019', 'OT', 'Exodus', 26, 22),
('spatial', 'شا', 478, 'Genesis 19:26', 'yousafzai2019', 'OT', 'Genesis', 19, 26),
('spatial', 'جنوب', 2211, 'Exodus 27:9', 'yousafzai2019', 'OT', 'Exodus', 27, 9),
('spatial', 'جنوب', 2568, 'Exodus 38:9', 'yousafzai2019', 'OT', 'Exodus', 38, 9),
('spatial', 'پاس', 7, 'Genesis 1:7', 'yousafzai2019', 'OT', 'Genesis', 1, 7),
('spatial', 'پاس', 2511, 'Exodus 36:19', 'yousafzai2019', 'OT', 'Exodus', 36, 19),
('spatial', 'ورې', 1231, 'Genesis 42:22', 'yousafzai2019', 'OT', 'Genesis', 42, 22);

-- time_concepts (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('time_concepts', 'اوس', 1411, 'Genesis 48:5', 'yousafzai2019', 'OT', 'Genesis', 48, 5),
('time_concepts', 'اوس', 1534, 'Exodus 3:8', 'yousafzai2019', 'OT', 'Exodus', 3, 8);

-- body_parts_torso (12 entries from 7 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('body_parts_torso', 'لاس', 2422, 'Exodus 33:23', 'yousafzai2019', 'OT', 'Exodus', 33, 23),
('body_parts_torso', 'لاس', 1555, 'Exodus 4:7', 'yousafzai2019', 'OT', 'Exodus', 4, 7),
('body_parts_torso', 'شا', 2198, 'Exodus 26:33', 'yousafzai2019', 'OT', 'Exodus', 26, 33),
('body_parts_torso', 'شا', 429, 'Genesis 18:10', 'yousafzai2019', 'OT', 'Genesis', 18, 10),
('body_parts_torso', 'څنګ', 2247, 'Exodus 28:26', 'yousafzai2019', 'OT', 'Exodus', 28, 26),
('body_parts_torso', 'خېټه', 70, 'Genesis 3:14', 'yousafzai2019', 'OT', 'Genesis', 3, 14),
('body_parts_torso', 'خېټه', 667, 'Genesis 25:22', 'yousafzai2019', 'OT', 'Genesis', 25, 22),
('body_parts_torso', 'ګوته', 2733, 'Leviticus 4:17', 'yousafzai2019', 'OT', 'Leviticus', 4, 17),
('body_parts_torso', 'ګوته', 2750, 'Leviticus 4:34', 'yousafzai2019', 'OT', 'Leviticus', 4, 34),
('body_parts_torso', 'اوږه', 623, 'Genesis 24:45', 'yousafzai2019', 'OT', 'Genesis', 24, 45),
('body_parts_torso', 'پوښتۍ', 2289, 'Exodus 29:27', 'yousafzai2019', 'OT', 'Exodus', 29, 27),
('body_parts_torso', 'پوښتۍ', 2290, 'Exodus 29:28', 'yousafzai2019', 'OT', 'Exodus', 29, 28);

-- body_parts (26 entries from 15 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('body_parts', 'لاس', 2422, 'Exodus 33:23', 'yousafzai2019', 'OT', 'Exodus', 33, 23),
('body_parts', 'لاس', 59, 'Genesis 3:3', 'yousafzai2019', 'OT', 'Genesis', 3, 3),
('body_parts', 'غوږ', 2097, 'Exodus 23:21', 'yousafzai2019', 'OT', 'Exodus', 23, 21),
('body_parts', 'غوږ', 1706, 'Exodus 9:21', 'yousafzai2019', 'OT', 'Exodus', 9, 21),
('body_parts', 'شا', 2524, 'Exodus 36:32', 'yousafzai2019', 'OT', 'Exodus', 36, 32),
('body_parts', 'شا', 2187, 'Exodus 26:22', 'yousafzai2019', 'OT', 'Exodus', 26, 22),
('body_parts', 'ادوم', 958, 'Genesis 33:16', 'yousafzai2019', 'OT', 'Genesis', 33, 16),
('body_parts', 'ادوم', 339, 'Genesis 14:6', 'yousafzai2019', 'OT', 'Genesis', 14, 6),
('body_parts', 'څنګ', 2247, 'Exodus 28:26', 'yousafzai2019', 'OT', 'Exodus', 28, 26),
('body_parts', 'سترګه', 2038, 'Exodus 21:26', 'yousafzai2019', 'OT', 'Exodus', 21, 26),
('body_parts', 'سترګه', 566, 'Genesis 23:6', 'yousafzai2019', 'OT', 'Genesis', 23, 6),
('body_parts', 'خېټه', 668, 'Genesis 25:23', 'yousafzai2019', 'OT', 'Genesis', 25, 23),
('body_parts', 'خېټه', 667, 'Genesis 25:22', 'yousafzai2019', 'OT', 'Genesis', 25, 22),
('body_parts', 'ګوته', 2750, 'Leviticus 4:34', 'yousafzai2019', 'OT', 'Leviticus', 4, 34),
('body_parts', 'ګوته', 1196, 'Genesis 41:42', 'yousafzai2019', 'OT', 'Genesis', 41, 42),
('body_parts', 'پښه', 1198, 'Genesis 41:44', 'yousafzai2019', 'OT', 'Genesis', 41, 44),
('body_parts', 'مرۍ', 1436, 'Genesis 49:8', 'yousafzai2019', 'OT', 'Genesis', 49, 8),
('body_parts', 'پوزه', 625, 'Genesis 24:47', 'yousafzai2019', 'OT', 'Genesis', 24, 47),
('body_parts', 'پوزه', 600, 'Genesis 24:22', 'yousafzai2019', 'OT', 'Genesis', 24, 22),
('body_parts', 'اوږه', 623, 'Genesis 24:45', 'yousafzai2019', 'OT', 'Genesis', 24, 45),
('body_parts', 'غاښ', 2036, 'Exodus 21:24', 'yousafzai2019', 'OT', 'Exodus', 21, 24),
('body_parts', 'غاښ', 2039, 'Exodus 21:27', 'yousafzai2019', 'OT', 'Exodus', 21, 27),
('body_parts', 'پوښتۍ', 2290, 'Exodus 29:28', 'yousafzai2019', 'OT', 'Exodus', 29, 28),
('body_parts', 'پوښتۍ', 52, 'Genesis 2:21', 'yousafzai2019', 'OT', 'Genesis', 2, 21),
('body_parts', 'پونده', 71, 'Genesis 3:15', 'yousafzai2019', 'OT', 'Genesis', 3, 15),
('body_parts', 'پونده', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17);

-- states_size (10 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('states_size', 'لوی', 1344, 'Genesis 46:3', 'yousafzai2019', 'OT', 'Genesis', 46, 3),
('states_size', 'لوی', 437, 'Genesis 18:18', 'yousafzai2019', 'OT', 'Genesis', 18, 18),
('states_size', 'لږ', 2404, 'Exodus 33:5', 'yousafzai2019', 'OT', 'Exodus', 33, 5),
('states_size', 'لږ', 1513, 'Exodus 2:10', 'yousafzai2019', 'OT', 'Exodus', 2, 10),
('states_size', 'لوړ', 2540, 'Exodus 37:10', 'yousafzai2019', 'OT', 'Exodus', 37, 10),
('states_size', 'لوړ', 2148, 'Exodus 25:23', 'yousafzai2019', 'OT', 'Exodus', 25, 23),
('states_size', 'اوږد', 78, 'Genesis 3:22', 'yousafzai2019', 'OT', 'Genesis', 3, 22),
('states_size', 'اوږد', 2181, 'Exodus 26:16', 'yousafzai2019', 'OT', 'Exodus', 26, 16),
('states_size', 'وړوکی', 472, 'Genesis 19:20', 'yousafzai2019', 'OT', 'Genesis', 19, 20),
('states_size', 'وړوکی', 1092, 'Genesis 38:14', 'yousafzai2019', 'OT', 'Genesis', 38, 14);

-- states_life (9 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('states_life', 'ژوند', 78, 'Genesis 3:22', 'yousafzai2019', 'OT', 'Genesis', 3, 22),
('states_life', 'ژوند', 2035, 'Exodus 21:23', 'yousafzai2019', 'OT', 'Exodus', 21, 23),
('states_life', 'مړ', 2048, 'Exodus 21:36', 'yousafzai2019', 'OT', 'Exodus', 21, 36),
('states_life', 'مړ', 1247, 'Genesis 42:38', 'yousafzai2019', 'OT', 'Genesis', 42, 38),
('states_life', 'مرګ', 697, 'Genesis 26:18', 'yousafzai2019', 'OT', 'Genesis', 26, 18),
('states_life', 'مرګ', 1475, 'Genesis 50:16', 'yousafzai2019', 'OT', 'Genesis', 50, 16),
('states_life', 'نوی', 1493, 'Exodus 1:8', 'yousafzai2019', 'OT', 'Exodus', 1, 8),
('states_life', 'زوړ', 513, 'Genesis 21:7', 'yousafzai2019', 'OT', 'Genesis', 21, 7),
('states_life', 'زوړ', 409, 'Genesis 17:17', 'yousafzai2019', 'OT', 'Genesis', 17, 17);

-- numbers_cardinal (21 entries from 11 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('numbers_cardinal', 'دوه', 2522, 'Exodus 36:30', 'yousafzai2019', 'OT', 'Exodus', 36, 30),
('numbers_cardinal', 'دوه', 2198, 'Exodus 26:33', 'yousafzai2019', 'OT', 'Exodus', 26, 33),
('numbers_cardinal', 'درې', 138, 'Genesis 5:32', 'yousafzai2019', 'OT', 'Genesis', 5, 32),
('numbers_cardinal', 'درې', 1356, 'Genesis 46:15', 'yousafzai2019', 'OT', 'Genesis', 46, 15),
('numbers_cardinal', 'څلور', 2550, 'Exodus 37:20', 'yousafzai2019', 'OT', 'Exodus', 37, 20),
('numbers_cardinal', 'څلور', 2049, 'Exodus 22:1', 'yousafzai2019', 'OT', 'Exodus', 22, 1),
('numbers_cardinal', 'لس', 115, 'Genesis 5:9', 'yousafzai2019', 'OT', 'Genesis', 5, 9),
('numbers_cardinal', 'لس', 588, 'Genesis 24:10', 'yousafzai2019', 'OT', 'Genesis', 24, 10),
('numbers_cardinal', 'شپږ', 2158, 'Exodus 25:33', 'yousafzai2019', 'OT', 'Exodus', 25, 33),
('numbers_cardinal', 'شپږ', 2508, 'Exodus 36:16', 'yousafzai2019', 'OT', 'Exodus', 36, 16),
('numbers_cardinal', 'څلوېښت', 2531, 'Exodus 37:1', 'yousafzai2019', 'OT', 'Exodus', 37, 1),
('numbers_cardinal', 'څلوېښت', 2186, 'Exodus 26:21', 'yousafzai2019', 'OT', 'Exodus', 26, 21),
('numbers_cardinal', 'دېرش', 280, 'Genesis 11:17', 'yousafzai2019', 'OT', 'Genesis', 11, 17),
('numbers_cardinal', 'دېرش', 1796, 'Exodus 12:41', 'yousafzai2019', 'OT', 'Exodus', 12, 41),
('numbers_cardinal', 'پنځوس', 2568, 'Exodus 38:9', 'yousafzai2019', 'OT', 'Exodus', 38, 9),
('numbers_cardinal', 'پنځوس', 2504, 'Exodus 36:12', 'yousafzai2019', 'OT', 'Exodus', 36, 12),
('numbers_cardinal', 'څوارلس', 1363, 'Genesis 46:22', 'yousafzai2019', 'OT', 'Genesis', 46, 22),
('numbers_cardinal', 'څوارلس', 151, 'Genesis 6:15', 'yousafzai2019', 'OT', 'Genesis', 6, 15),
('numbers_cardinal', 'شپاړس', 2522, 'Exodus 36:30', 'yousafzai2019', 'OT', 'Exodus', 36, 30),
('numbers_cardinal', 'شپاړس', 1359, 'Genesis 46:18', 'yousafzai2019', 'OT', 'Genesis', 46, 18),
('numbers_cardinal', 'نولس', 288, 'Genesis 11:25', 'yousafzai2019', 'OT', 'Genesis', 11, 25);

-- numbers (27 entries from 14 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('numbers', 'دوه', 2522, 'Exodus 36:30', 'yousafzai2019', 'OT', 'Exodus', 36, 30),
('numbers', 'دوه', 2507, 'Exodus 36:15', 'yousafzai2019', 'OT', 'Exodus', 36, 15),
('numbers', 'درې', 1032, 'Genesis 36:14', 'yousafzai2019', 'OT', 'Genesis', 36, 14),
('numbers', 'درې', 1335, 'Genesis 45:22', 'yousafzai2019', 'OT', 'Genesis', 45, 22),
('numbers', 'څلور', 2543, 'Exodus 37:13', 'yousafzai2019', 'OT', 'Exodus', 37, 13),
('numbers', 'څلور', 2528, 'Exodus 36:36', 'yousafzai2019', 'OT', 'Exodus', 36, 36),
('numbers', 'کم', 1720, 'Exodus 10:2', 'yousafzai2019', 'OT', 'Exodus', 10, 2),
('numbers', 'کم', 1761, 'Exodus 12:4', 'yousafzai2019', 'OT', 'Exodus', 12, 4),
('numbers', 'لږ', 1317, 'Genesis 45:4', 'yousafzai2019', 'OT', 'Genesis', 45, 4),
('numbers', 'لږ', 1384, 'Genesis 47:9', 'yousafzai2019', 'OT', 'Genesis', 47, 9),
('numbers', 'لس', 115, 'Genesis 5:9', 'yousafzai2019', 'OT', 'Genesis', 5, 9),
('numbers', 'لس', 2216, 'Exodus 27:16', 'yousafzai2019', 'OT', 'Exodus', 27, 16),
('numbers', 'شپږ', 2443, 'Exodus 34:21', 'yousafzai2019', 'OT', 'Exodus', 34, 21),
('numbers', 'شپږ', 2459, 'Exodus 35:2', 'yousafzai2019', 'OT', 'Exodus', 35, 2),
('numbers', 'څلوېښت', 160, 'Genesis 7:4', 'yousafzai2019', 'OT', 'Genesis', 7, 4),
('numbers', 'څلوېښت', 2186, 'Exodus 26:21', 'yousafzai2019', 'OT', 'Exodus', 26, 21),
('numbers', 'دېرش', 1796, 'Exodus 12:41', 'yousafzai2019', 'OT', 'Exodus', 12, 41),
('numbers', 'دېرش', 1384, 'Genesis 47:9', 'yousafzai2019', 'OT', 'Genesis', 47, 9),
('numbers', 'پنځوس', 2211, 'Exodus 27:9', 'yousafzai2019', 'OT', 'Exodus', 27, 9),
('numbers', 'پنځوس', 2568, 'Exodus 38:9', 'yousafzai2019', 'OT', 'Exodus', 38, 9),
('numbers', 'څلورم', 2241, 'Exodus 28:20', 'yousafzai2019', 'OT', 'Exodus', 28, 20),
('numbers', 'څلورم', 2429, 'Exodus 34:7', 'yousafzai2019', 'OT', 'Exodus', 34, 7),
('numbers', 'څوارلس', 1363, 'Genesis 46:22', 'yousafzai2019', 'OT', 'Genesis', 46, 22),
('numbers', 'څوارلس', 2501, 'Exodus 36:9', 'yousafzai2019', 'OT', 'Exodus', 36, 9),
('numbers', 'شپاړس', 2522, 'Exodus 36:30', 'yousafzai2019', 'OT', 'Exodus', 36, 30),
('numbers', 'شپاړس', 1359, 'Genesis 46:18', 'yousafzai2019', 'OT', 'Genesis', 46, 18),
('numbers', 'نولس', 288, 'Genesis 11:25', 'yousafzai2019', 'OT', 'Genesis', 11, 25);

-- nature_land (10 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('nature_land', 'زمکه', 409, 'Genesis 17:17', 'yousafzai2019', 'OT', 'Genesis', 17, 17),
('nature_land', 'زمکه', 173, 'Genesis 7:17', 'yousafzai2019', 'OT', 'Genesis', 7, 17),
('nature_land', 'غر', 1527, 'Exodus 3:1', 'yousafzai2019', 'OT', 'Exodus', 3, 1),
('nature_land', 'غر', 2110, 'Exodus 24:1', 'yousafzai2019', 'OT', 'Exodus', 24, 1),
('nature_land', 'صحرا', 1544, 'Exodus 3:18', 'yousafzai2019', 'OT', 'Exodus', 3, 18),
('nature_land', 'صحرا', 640, 'Genesis 24:62', 'yousafzai2019', 'OT', 'Genesis', 24, 62),
('nature_land', 'مېوه', 67, 'Genesis 3:11', 'yousafzai2019', 'OT', 'Genesis', 3, 11),
('nature_land', 'مېوه', 68, 'Genesis 3:12', 'yousafzai2019', 'OT', 'Genesis', 3, 12),
('nature_land', 'بوټی', 1140, 'Genesis 40:9', 'yousafzai2019', 'OT', 'Genesis', 40, 9),
('nature_land', 'بوټی', 36, 'Genesis 2:5', 'yousafzai2019', 'OT', 'Genesis', 2, 5);

-- nature (20 entries from 12 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('nature', 'زمکه', 178, 'Genesis 7:22', 'yousafzai2019', 'OT', 'Genesis', 7, 22),
('nature', 'زمکه', 173, 'Genesis 7:17', 'yousafzai2019', 'OT', 'Genesis', 7, 17),
('nature', 'سمندر', 1201, 'Genesis 41:49', 'yousafzai2019', 'OT', 'Genesis', 41, 49),
('nature', 'سمندر', 925, 'Genesis 32:12', 'yousafzai2019', 'OT', 'Genesis', 32, 12),
('nature', 'غر', 2110, 'Exodus 24:1', 'yousafzai2019', 'OT', 'Exodus', 24, 1),
('nature', 'غر', 1527, 'Exodus 3:1', 'yousafzai2019', 'OT', 'Exodus', 3, 1),
('nature', 'صحرا', 339, 'Genesis 14:6', 'yousafzai2019', 'OT', 'Genesis', 14, 6),
('nature', 'صحرا', 518, 'Genesis 21:14', 'yousafzai2019', 'OT', 'Genesis', 21, 14),
('nature', 'مېوه', 59, 'Genesis 3:3', 'yousafzai2019', 'OT', 'Genesis', 3, 3),
('nature', 'مېوه', 68, 'Genesis 3:12', 'yousafzai2019', 'OT', 'Genesis', 3, 12),
('nature', 'بوټی', 36, 'Genesis 2:5', 'yousafzai2019', 'OT', 'Genesis', 2, 5),
('nature', 'بوټی', 1730, 'Exodus 10:12', 'yousafzai2019', 'OT', 'Exodus', 10, 12),
('nature', 'مار', 70, 'Genesis 3:14', 'yousafzai2019', 'OT', 'Genesis', 3, 14),
('nature', 'مار', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17),
('nature', 'واوره', 1554, 'Exodus 4:6', 'yousafzai2019', 'OT', 'Exodus', 4, 6),
('nature', 'آس', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17),
('nature', 'غوا', 2080, 'Exodus 23:4', 'yousafzai2019', 'OT', 'Exodus', 23, 4),
('nature', 'غوا', 2049, 'Exodus 22:1', 'yousafzai2019', 'OT', 'Exodus', 22, 1),
('nature', 'اوښ', 642, 'Genesis 24:64', 'yousafzai2019', 'OT', 'Genesis', 24, 64),
('nature', 'سپی', 1754, 'Exodus 11:7', 'yousafzai2019', 'OT', 'Exodus', 11, 7);

-- actions_fight (7 entries from 4 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('actions_fight', 'جنګ', 1580, 'Exodus 5:3', 'yousafzai2019', 'OT', 'Exodus', 5, 3),
('actions_fight', 'جنګ', 335, 'Genesis 14:2', 'yousafzai2019', 'OT', 'Genesis', 14, 2),
('actions_fight', 'ماته', 597, 'Genesis 24:19', 'yousafzai2019', 'OT', 'Genesis', 24, 19),
('actions_fight', 'شکست', 555, 'Genesis 22:17', 'yousafzai2019', 'OT', 'Genesis', 22, 17),
('actions_fight', 'شکست', 339, 'Genesis 14:6', 'yousafzai2019', 'OT', 'Genesis', 14, 6),
('actions_fight', 'جګړه', 699, 'Genesis 26:20', 'yousafzai2019', 'OT', 'Genesis', 26, 20),
('actions_fight', 'جګړه', 1516, 'Exodus 2:13', 'yousafzai2019', 'OT', 'Exodus', 2, 13);

-- age_stages (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('age_stages', 'مشر', 1321, 'Genesis 45:8', 'yousafzai2019', 'OT', 'Genesis', 45, 8),
('age_stages', 'مشر', 580, 'Genesis 24:2', 'yousafzai2019', 'OT', 'Genesis', 24, 2),
('age_stages', 'زوړ', 513, 'Genesis 21:7', 'yousafzai2019', 'OT', 'Genesis', 21, 7),
('age_stages', 'زوړ', 409, 'Genesis 17:17', 'yousafzai2019', 'OT', 'Genesis', 17, 17);

-- body_parts_head (9 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('body_parts_head', 'غوږ', 1299, 'Genesis 44:18', 'yousafzai2019', 'OT', 'Genesis', 44, 18),
('body_parts_head', 'غوږ', 1706, 'Exodus 9:21', 'yousafzai2019', 'OT', 'Exodus', 9, 21),
('body_parts_head', 'سترګه', 1115, 'Genesis 39:7', 'yousafzai2019', 'OT', 'Genesis', 39, 7),
('body_parts_head', 'سترګه', 566, 'Genesis 23:6', 'yousafzai2019', 'OT', 'Genesis', 23, 6),
('body_parts_head', 'مرۍ', 1436, 'Genesis 49:8', 'yousafzai2019', 'OT', 'Genesis', 49, 8),
('body_parts_head', 'پوزه', 625, 'Genesis 24:47', 'yousafzai2019', 'OT', 'Genesis', 24, 47),
('body_parts_head', 'پوزه', 600, 'Genesis 24:22', 'yousafzai2019', 'OT', 'Genesis', 24, 22),
('body_parts_head', 'غاښ', 2036, 'Exodus 21:24', 'yousafzai2019', 'OT', 'Exodus', 21, 24),
('body_parts_head', 'غاښ', 2039, 'Exodus 21:27', 'yousafzai2019', 'OT', 'Exodus', 21, 27);

-- places (7 entries from 4 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('places', 'لاره', 1337, 'Genesis 45:24', 'yousafzai2019', 'OT', 'Genesis', 45, 24),
('places', 'لاره', 663, 'Genesis 25:18', 'yousafzai2019', 'OT', 'Genesis', 25, 18),
('places', 'لار', 2096, 'Exodus 23:20', 'yousafzai2019', 'OT', 'Exodus', 23, 20),
('places', 'لار', 1107, 'Genesis 38:29', 'yousafzai2019', 'OT', 'Genesis', 38, 29),
('places', 'جنوب', 2568, 'Exodus 38:9', 'yousafzai2019', 'OT', 'Exodus', 38, 9),
('places', 'جنوب', 2183, 'Exodus 26:18', 'yousafzai2019', 'OT', 'Exodus', 26, 18),
('places', 'سړک', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17);

-- food (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('food', 'خوراک', 2437, 'Exodus 34:15', 'yousafzai2019', 'OT', 'Exodus', 34, 15),
('food', 'خوراک', 1269, 'Genesis 43:22', 'yousafzai2019', 'OT', 'Genesis', 43, 22),
('food', 'مېوه', 68, 'Genesis 3:12', 'yousafzai2019', 'OT', 'Genesis', 3, 12),
('food', 'مېوه', 47, 'Genesis 2:16', 'yousafzai2019', 'OT', 'Genesis', 2, 16),
('food', 'غوښه', 368, 'Genesis 15:11', 'yousafzai2019', 'OT', 'Genesis', 15, 11),
('food', 'غوښه', 1150, 'Genesis 40:19', 'yousafzai2019', 'OT', 'Genesis', 40, 19);

-- weather (10 entries from 6 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('weather', 'آسمان', 521, 'Genesis 21:17', 'yousafzai2019', 'OT', 'Genesis', 21, 17),
('weather', 'آسمان', 182, 'Genesis 8:2', 'yousafzai2019', 'OT', 'Genesis', 8, 2),
('weather', 'باران', 168, 'Genesis 7:12', 'yousafzai2019', 'OT', 'Genesis', 7, 12),
('weather', 'باران', 1716, 'Exodus 9:33', 'yousafzai2019', 'OT', 'Exodus', 9, 33),
('weather', 'نمر', 475, 'Genesis 19:23', 'yousafzai2019', 'OT', 'Genesis', 19, 23),
('weather', 'نمر', 374, 'Genesis 15:17', 'yousafzai2019', 'OT', 'Genesis', 15, 17),
('weather', 'طوفان', 1717, 'Exodus 9:34', 'yousafzai2019', 'OT', 'Exodus', 9, 34),
('weather', 'سپوږمۍ', 16, 'Genesis 1:16', 'yousafzai2019', 'OT', 'Genesis', 1, 16),
('weather', 'سپوږمۍ', 1051, 'Genesis 37:9', 'yousafzai2019', 'OT', 'Genesis', 37, 9),
('weather', 'واوره', 1554, 'Exodus 4:6', 'yousafzai2019', 'OT', 'Exodus', 4, 6);

-- abstract_good (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('abstract_good', 'ښه', 913, 'Genesis 31:55', 'yousafzai2019', 'OT', 'Genesis', 31, 55),
('abstract_good', 'ښه', 435, 'Genesis 18:16', 'yousafzai2019', 'OT', 'Genesis', 18, 16),
('abstract_good', 'رحم', 2418, 'Exodus 33:19', 'yousafzai2019', 'OT', 'Exodus', 33, 19),
('abstract_good', 'رحم', 2428, 'Exodus 34:6', 'yousafzai2019', 'OT', 'Exodus', 34, 6),
('abstract_good', 'عدالت', 1598, 'Exodus 5:21', 'yousafzai2019', 'OT', 'Exodus', 5, 21),
('abstract_good', 'عدالت', 2752, 'Leviticus 5:1', 'yousafzai2019', 'OT', 'Leviticus', 5, 1);

-- grammar_adjectives (11 entries from 6 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('grammar_adjectives', 'ښه', 913, 'Genesis 31:55', 'yousafzai2019', 'OT', 'Genesis', 31, 55),
('grammar_adjectives', 'ښه', 435, 'Genesis 18:16', 'yousafzai2019', 'OT', 'Genesis', 18, 16),
('grammar_adjectives', 'بد', 2755, 'Leviticus 5:4', 'yousafzai2019', 'OT', 'Leviticus', 5, 4),
('grammar_adjectives', 'بد', 48, 'Genesis 2:17', 'yousafzai2019', 'OT', 'Genesis', 2, 17),
('grammar_adjectives', 'نوی', 1493, 'Exodus 1:8', 'yousafzai2019', 'OT', 'Exodus', 1, 8),
('grammar_adjectives', 'جنوب', 2183, 'Exodus 26:18', 'yousafzai2019', 'OT', 'Exodus', 26, 18),
('grammar_adjectives', 'جنوب', 2211, 'Exodus 27:9', 'yousafzai2019', 'OT', 'Exodus', 27, 9),
('grammar_adjectives', 'اوږد', 2148, 'Exodus 25:23', 'yousafzai2019', 'OT', 'Exodus', 25, 23),
('grammar_adjectives', 'اوږد', 2572, 'Exodus 38:13', 'yousafzai2019', 'OT', 'Exodus', 38, 13),
('grammar_adjectives', 'زوړ', 513, 'Genesis 21:7', 'yousafzai2019', 'OT', 'Genesis', 21, 7),
('grammar_adjectives', 'زوړ', 409, 'Genesis 17:17', 'yousafzai2019', 'OT', 'Genesis', 17, 17);

-- religious_actions (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('religious_actions', 'برکت', 554, 'Genesis 22:16', 'yousafzai2019', 'OT', 'Genesis', 22, 16),
('religious_actions', 'برکت', 579, 'Genesis 24:1', 'yousafzai2019', 'OT', 'Genesis', 24, 1),
('religious_actions', 'قربان', 962, 'Genesis 33:20', 'yousafzai2019', 'OT', 'Genesis', 33, 20),
('religious_actions', 'قربان', 2300, 'Exodus 29:38', 'yousafzai2019', 'OT', 'Exodus', 29, 38);

-- religious (10 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('religious', 'برکت', 526, 'Genesis 21:22', 'yousafzai2019', 'OT', 'Genesis', 21, 22),
('religious', 'برکت', 579, 'Genesis 24:1', 'yousafzai2019', 'OT', 'Genesis', 24, 1),
('religious', 'مقدس', 2589, 'Exodus 39:1', 'yousafzai2019', 'OT', 'Exodus', 39, 1),
('religious', 'مقدس', 2250, 'Exodus 28:29', 'yousafzai2019', 'OT', 'Exodus', 28, 29),
('religious', 'فرښته', 2401, 'Exodus 33:2', 'yousafzai2019', 'OT', 'Exodus', 33, 2),
('religious', 'فرښته', 1528, 'Exodus 3:2', 'yousafzai2019', 'OT', 'Exodus', 3, 2),
('religious', 'مَلِک', 504, 'Genesis 20:14', 'yousafzai2019', 'OT', 'Genesis', 20, 14),
('religious', 'مَلِک', 680, 'Genesis 26:1', 'yousafzai2019', 'OT', 'Genesis', 26, 1),
('religious', 'قربان', 333, 'Genesis 13:18', 'yousafzai2019', 'OT', 'Genesis', 13, 18),
('religious', 'قربان', 2742, 'Leviticus 4:26', 'yousafzai2019', 'OT', 'Leviticus', 4, 26);

-- direction (10 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('direction', 'بهر', 1521, 'Exodus 2:20', 'yousafzai2019', 'OT', 'Exodus', 2, 20),
('direction', 'بهر', 2200, 'Exodus 26:35', 'yousafzai2019', 'OT', 'Exodus', 26, 35),
('direction', 'وروستو', 338, 'Genesis 14:5', 'yousafzai2019', 'OT', 'Genesis', 14, 5),
('direction', 'وروستو', 944, 'Genesis 33:2', 'yousafzai2019', 'OT', 'Genesis', 33, 2),
('direction', 'شا', 2192, 'Exodus 26:27', 'yousafzai2019', 'OT', 'Exodus', 26, 27),
('direction', 'شا', 478, 'Genesis 19:26', 'yousafzai2019', 'OT', 'Genesis', 19, 26),
('direction', 'جنوب', 2183, 'Exodus 26:18', 'yousafzai2019', 'OT', 'Exodus', 26, 18),
('direction', 'جنوب', 2568, 'Exodus 38:9', 'yousafzai2019', 'OT', 'Exodus', 38, 9),
('direction', 'پاس', 2179, 'Exodus 26:14', 'yousafzai2019', 'OT', 'Exodus', 26, 14),
('direction', 'پاس', 2511, 'Exodus 36:19', 'yousafzai2019', 'OT', 'Exodus', 36, 19);

-- religious_concepts (6 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('religious_concepts', 'مقدس', 2295, 'Exodus 29:33', 'yousafzai2019', 'OT', 'Exodus', 29, 33),
('religious_concepts', 'مقدس', 2198, 'Exodus 26:33', 'yousafzai2019', 'OT', 'Exodus', 26, 33),
('religious_concepts', 'فرښته', 1778, 'Exodus 12:23', 'yousafzai2019', 'OT', 'Exodus', 12, 23),
('religious_concepts', 'فرښته', 1422, 'Genesis 48:16', 'yousafzai2019', 'OT', 'Genesis', 48, 16),
('religious_concepts', 'مَلِک', 531, 'Genesis 21:27', 'yousafzai2019', 'OT', 'Genesis', 21, 27),
('religious_concepts', 'مَلِک', 690, 'Genesis 26:11', 'yousafzai2019', 'OT', 'Genesis', 26, 11);

-- time_months (4 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('time_months', 'کال', 338, 'Genesis 14:5', 'yousafzai2019', 'OT', 'Genesis', 14, 5),
('time_months', 'کال', 2095, 'Exodus 23:19', 'yousafzai2019', 'OT', 'Exodus', 23, 19),
('time_months', 'اوړی', 202, 'Genesis 8:22', 'yousafzai2019', 'OT', 'Genesis', 8, 22),
('time_months', 'ژمی', 202, 'Genesis 8:22', 'yousafzai2019', 'OT', 'Genesis', 8, 22);

-- emotions_positive (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('emotions_positive', 'رحم', 468, 'Genesis 19:16', 'yousafzai2019', 'OT', 'Genesis', 19, 16),
('emotions_positive', 'رحم', 1129, 'Genesis 39:21', 'yousafzai2019', 'OT', 'Genesis', 39, 21);

-- emotions (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('emotions', 'رحم', 2418, 'Exodus 33:19', 'yousafzai2019', 'OT', 'Exodus', 33, 19),
('emotions', 'رحم', 2428, 'Exodus 34:6', 'yousafzai2019', 'OT', 'Exodus', 34, 6);

-- abstract_concepts (5 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('abstract_concepts', 'رحم', 468, 'Genesis 19:16', 'yousafzai2019', 'OT', 'Genesis', 19, 16),
('abstract_concepts', 'رحم', 1129, 'Genesis 39:21', 'yousafzai2019', 'OT', 'Genesis', 39, 21),
('abstract_concepts', 'خلاصون', 1446, 'Genesis 49:18', 'yousafzai2019', 'OT', 'Genesis', 49, 18),
('abstract_concepts', 'عدالت', 2752, 'Leviticus 5:1', 'yousafzai2019', 'OT', 'Leviticus', 5, 1),
('abstract_concepts', 'عدالت', 2082, 'Exodus 23:6', 'yousafzai2019', 'OT', 'Exodus', 23, 6);

-- measurement (5 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('measurement', 'ډک', 1178, 'Genesis 41:24', 'yousafzai2019', 'OT', 'Genesis', 41, 24),
('measurement', 'ډک', 20, 'Genesis 1:20', 'yousafzai2019', 'OT', 'Genesis', 1, 20),
('measurement', 'شمېر', 1588, 'Exodus 5:11', 'yousafzai2019', 'OT', 'Exodus', 5, 11),
('measurement', 'شمېر', 1761, 'Exodus 12:4', 'yousafzai2019', 'OT', 'Exodus', 12, 4),
('measurement', 'شمېره', 167, 'Genesis 7:11', 'yousafzai2019', 'OT', 'Genesis', 7, 11);

-- actions_communication (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('actions_communication', 'پوښتنه', 1274, 'Genesis 43:27', 'yousafzai2019', 'OT', 'Genesis', 43, 27),
('actions_communication', 'پوښتنه', 1237, 'Genesis 42:28', 'yousafzai2019', 'OT', 'Genesis', 42, 28);

-- family_female (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('family_female', 'لور', 486, 'Genesis 19:34', 'yousafzai2019', 'OT', 'Genesis', 19, 34),
('family_female', 'لور', 1356, 'Genesis 46:15', 'yousafzai2019', 'OT', 'Genesis', 46, 15),
('family_female', 'نمسۍ', 1032, 'Genesis 36:14', 'yousafzai2019', 'OT', 'Genesis', 36, 14),
('family_female', 'نمسۍ', 1348, 'Genesis 46:7', 'yousafzai2019', 'OT', 'Genesis', 46, 7);

-- family_general (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('family_general', 'بچی', 1761, 'Exodus 12:4', 'yousafzai2019', 'OT', 'Exodus', 12, 4),
('family_general', 'بچی', 1503, 'Exodus 1:22', 'yousafzai2019', 'OT', 'Exodus', 1, 22),
('family_general', 'خپلوان', 296, 'Genesis 12:1', 'yousafzai2019', 'OT', 'Genesis', 12, 1),
('family_general', 'خپلوان', 323, 'Genesis 13:8', 'yousafzai2019', 'OT', 'Genesis', 13, 8);

-- numbers_quantities (4 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('numbers_quantities', 'کم', 633, 'Genesis 24:55', 'yousafzai2019', 'OT', 'Genesis', 24, 55),
('numbers_quantities', 'کم', 123, 'Genesis 5:17', 'yousafzai2019', 'OT', 'Genesis', 5, 17),
('numbers_quantities', 'لږ', 592, 'Genesis 24:14', 'yousafzai2019', 'OT', 'Genesis', 24, 14),
('numbers_quantities', 'لږ', 1258, 'Genesis 43:11', 'yousafzai2019', 'OT', 'Genesis', 43, 11);

-- nature_water (3 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('nature_water', 'سمندر', 1201, 'Genesis 41:49', 'yousafzai2019', 'OT', 'Genesis', 41, 49),
('nature_water', 'سمندر', 10, 'Genesis 1:10', 'yousafzai2019', 'OT', 'Genesis', 1, 10),
('nature_water', 'واوره', 1554, 'Exodus 4:6', 'yousafzai2019', 'OT', 'Exodus', 4, 6);

-- commerce (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('commerce', 'شته', 609, 'Genesis 24:31', 'yousafzai2019', 'OT', 'Genesis', 24, 31),
('commerce', 'شته', 1401, 'Genesis 47:26', 'yousafzai2019', 'OT', 'Genesis', 47, 26);

-- descriptions_appearance (3 entries from 2 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('descriptions_appearance', 'ښایسته', 1196, 'Genesis 41:42', 'yousafzai2019', 'OT', 'Genesis', 41, 42),
('descriptions_appearance', 'ښایسته', 1172, 'Genesis 41:18', 'yousafzai2019', 'OT', 'Genesis', 41, 18),
('descriptions_appearance', 'ښکلی', 1505, 'Exodus 2:2', 'yousafzai2019', 'OT', 'Exodus', 2, 2);

-- descriptions_character (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('descriptions_character', 'وفادار', 527, 'Genesis 21:23', 'yousafzai2019', 'OT', 'Genesis', 21, 23);

-- relationships (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('relationships', 'ملګری', 1098, 'Genesis 38:20', 'yousafzai2019', 'OT', 'Genesis', 38, 20);

-- work (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('work', 'نوکر', 588, 'Genesis 24:10', 'yousafzai2019', 'OT', 'Genesis', 24, 10),
('work', 'نوکر', 637, 'Genesis 24:59', 'yousafzai2019', 'OT', 'Genesis', 24, 59);

-- body_parts_legs (5 entries from 3 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('body_parts_legs', 'ادوم', 958, 'Genesis 33:16', 'yousafzai2019', 'OT', 'Genesis', 33, 16),
('body_parts_legs', 'ادوم', 675, 'Genesis 25:30', 'yousafzai2019', 'OT', 'Genesis', 25, 30),
('body_parts_legs', 'پښه', 1198, 'Genesis 41:44', 'yousafzai2019', 'OT', 'Genesis', 41, 44),
('body_parts_legs', 'پونده', 671, 'Genesis 25:26', 'yousafzai2019', 'OT', 'Genesis', 25, 26),
('body_parts_legs', 'پونده', 71, 'Genesis 3:15', 'yousafzai2019', 'OT', 'Genesis', 3, 15);

-- actions_see (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('actions_see', 'کولاو', 1268, 'Genesis 43:21', 'yousafzai2019', 'OT', 'Genesis', 43, 21),
('actions_see', 'کولاو', 523, 'Genesis 21:19', 'yousafzai2019', 'OT', 'Genesis', 21, 19);

-- nature_animals (7 entries from 5 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('nature_animals', 'مار', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17),
('nature_animals', 'مار', 1551, 'Exodus 4:3', 'yousafzai2019', 'OT', 'Exodus', 4, 3),
('nature_animals', 'آس', 1445, 'Genesis 49:17', 'yousafzai2019', 'OT', 'Genesis', 49, 17),
('nature_animals', 'غوا', 2049, 'Exodus 22:1', 'yousafzai2019', 'OT', 'Exodus', 22, 1),
('nature_animals', 'غوا', 2080, 'Exodus 23:4', 'yousafzai2019', 'OT', 'Exodus', 23, 4),
('nature_animals', 'اوښ', 642, 'Genesis 24:64', 'yousafzai2019', 'OT', 'Genesis', 24, 64),
('nature_animals', 'سپی', 1754, 'Exodus 11:7', 'yousafzai2019', 'OT', 'Exodus', 11, 7);

-- colors (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('colors', 'تور', 1733, 'Exodus 10:15', 'yousafzai2019', 'OT', 'Exodus', 10, 15);

-- numbers_ordinal (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('numbers_ordinal', 'څلورم', 373, 'Genesis 15:16', 'yousafzai2019', 'OT', 'Genesis', 15, 16),
('numbers_ordinal', 'څلورم', 45, 'Genesis 2:14', 'yousafzai2019', 'OT', 'Genesis', 2, 14);

-- materials (2 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('materials', 'زېړ', 2586, 'Exodus 38:29', 'yousafzai2019', 'OT', 'Exodus', 38, 29),
('materials', 'زېړ', 2567, 'Exodus 38:8', 'yousafzai2019', 'OT', 'Exodus', 38, 8);

-- clothing (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('clothing', 'څپلۍ', 356, 'Genesis 14:23', 'yousafzai2019', 'OT', 'Genesis', 14, 23);

-- time_days (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('time_days', 'هفته', 2088, 'Exodus 23:12', 'yousafzai2019', 'OT', 'Exodus', 23, 12);

-- actions_eat (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('actions_eat', 'تنده', 597, 'Genesis 24:19', 'yousafzai2019', 'OT', 'Genesis', 24, 19);

-- leadership (1 entries from 1 unique words)
INSERT INTO category_verse_mappings (
  category_key, pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse
) VALUES
('leadership', 'شهزادګۍ', 1512, 'Exodus 2:9', 'yousafzai2019', 'OT', 'Exodus', 2, 9);

