-- Delete all parts of compound biblical names
-- Generated by delete-all-compound-name-parts.py
-- These parts exist separately but should only appear in compound forms

-- Note: اب is kept because it appears in verb phrases ("اب ورکړ"), not just compound names

-- Delete 'حنم' (freq: 4) - part of: حنم‌ايل
DELETE FROM word_verse_mapping WHERE pashto_word = 'حنم';
DELETE FROM word_frequencies WHERE pashto_word = 'حنم';

-- Delete 'حنن' (freq: 2) - part of: حنن‌ايل
DELETE FROM word_verse_mapping WHERE pashto_word = 'حنن';
DELETE FROM word_frequencies WHERE pashto_word = 'حنن';

-- Delete 'شلتى' (freq: 11) - part of: شلتى‌اېل
DELETE FROM word_verse_mapping WHERE pashto_word = 'شلتى';
DELETE FROM word_frequencies WHERE pashto_word = 'شلتى';

-- Delete 'عالى' (freq: 2) - part of: اِلى‌عالى
DELETE FROM word_verse_mapping WHERE pashto_word = 'عالى';
DELETE FROM word_frequencies WHERE pashto_word = 'عالى';

-- Delete 'اعلیحضرته' - appears to be a fragment, not a proper name
DELETE FROM word_verse_mapping WHERE pashto_word = 'اعلیحضرته';
DELETE FROM word_frequencies WHERE pashto_word = 'اعلیحضرته';

-- Delete 'عزتۍ' - appears to be a fragment, not a proper name
DELETE FROM word_verse_mapping WHERE pashto_word = 'عزتۍ';
DELETE FROM word_frequencies WHERE pashto_word = 'عزتۍ';

-- Delete 'قِريَت' - appears to be a fragment, not a proper name
DELETE FROM word_verse_mapping WHERE pashto_word = 'قِريَت';
DELETE FROM word_frequencies WHERE pashto_word = 'قِريَت';
