-- Delete words that are parts of compound biblical names
-- These should be removed since the compound form exists as a separate entry
-- Generated by analyzing verse context

-- Step 1: Ensure compound forms exist (insert if missing)
-- These should already exist from fix-compound-biblical-names.sql, but ensure they're there
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('اخى‌اب', 'proper_noun', 'n. prop.', 'Ahab', 0, '[]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('حنن‌ايل', 'proper_noun', 'n. prop.', 'Hananeel', 0, '[]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('حنم‌ايل', 'proper_noun', 'n. prop.', 'Hananeel', 0, '[]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('بيت‌ايل', 'proper_noun', 'n. prop.', 'Bethel', 0, '[]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('اِلى‌عالى', 'proper_noun', 'n. prop.', 'Elealeh', 0, '[]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags)
VALUES ('شلتى‌اېل', 'proper_noun', 'n. prop.', 'Shealtiel', 0, '[]');

-- Step 2: Delete parts of compound names
-- ايل is part of compound: حنن‌ايل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'ايل';

-- اخى is part of compound: اخى‌اب
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اخى';

-- اِلى is part of compound: اِلى‌عالى
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اِلى';

-- اېل is part of compound: شلتى‌اېل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اېل';

-- Note: اب was analyzed but doesn't appear to be part of a compound name
-- It appears in "اب ورکړ:" which is a verb phrase, not a compound name
-- So we'll keep اب as a separate entry

