-- Delete words that are parts of compound biblical names
-- These should be removed since the compound form exists as a separate entry
-- Generated by identify-compound-name-parts.py

-- Step 1: Ensure compound forms exist (insert if missing)
-- اخى‌اب = اخى + اب
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('اخى‌اب', 'proper_noun', 'n. prop.', 'Ahab', 0, '[]');

-- اِلى‌عالى = اِلى + عالى
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('اِلى‌عالى', 'proper_noun', 'n. prop.', 'Elealeh', 0, '[]');

-- بيت‌ايل = بيت + ايل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('بيت‌ايل', 'proper_noun', 'n. prop.', 'Bethel', 0, '[]');

-- حنم‌ايل = حنم + ايل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('حنم‌ايل', 'proper_noun', 'n. prop.', 'Hananeel', 0, '[]');

-- حنن‌ايل = حنن + ايل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('حنن‌ايل', 'proper_noun', 'n. prop.', 'Hananeel', 0, '[]');

-- شلتى‌اېل = شلتى + اېل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('شلتى‌اېل', 'proper_noun', 'n. prop.', 'Shealtiel', 0, '[]');

-- اِفتاح‌اېل = اِفتاح + اېل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('اِفتاح‌اېل', 'proper_noun', 'n. prop.', 'Ithiel', 0, '[]');

-- بتو‌اېل = بتو + اېل
INSERT OR IGNORE INTO word_frequencies (pashto_word, word_type, pos, romanization, has_issues, issue_flags) VALUES ('بتو‌اېل', 'proper_noun', 'n. prop.', 'Bethel', 0, '[]');

-- Step 2: Delete parts of compound names
-- ايل is part of compound: حنن‌ايل, حنم‌ايل, بيت‌ايل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'ايل';

-- اخى is part of compound: اخى‌اب
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اخى';

-- اِلى is part of compound: اِلى‌عالى
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اِلى';

-- اېل is part of compound: شلتى‌اېل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اېل';

-- اِفتاح is part of compound: اِفتاح‌اېل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'اِفتاح';

-- بتو is part of compound: بتو‌اېل
-- Delete individual entry since compound exists
DELETE FROM word_frequencies WHERE pashto_word = 'بتو';

-- Note: اب was analyzed but doesn't appear to be part of a compound name
-- It appears in "اب ورکړ:" which is a verb phrase, not a compound name
-- So we'll keep اب as a separate entry

-- Note: حضرت is a common word meaning "presence/honorific" and appears
-- in many contexts (not just in "اعلیحضرته"), so we'll keep it as a separate entry

-- Note: Other compound name parts like ابى, ارى, اسرى, اورى, ايتى, ادونى
-- don't exist as separate entries in the database, so no deletion needed