-- Identify and label biblical names from null-characterized entries
-- Generated by identify-names-from-null-entries.py
-- These entries have null characterizations and are confirmed biblical names
-- Processed 500 batches of 200 entries each

-- يعريم (ID: 3783) - Biblical name: Jerim
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jerim', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'يعريم';

-- میکایا (ID: 3862) - Biblical name: Micah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Micah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'میکایا';

-- صِدق (ID: 3878) - Biblical name: Zadok
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zadok', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'صِدق';

-- عېبه (ID: 3880) - Biblical name: Ebed
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ebed', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عېبه';

-- هدد (ID: 3975) - Biblical name: Hadad
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Hadad', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'هدد';

-- یدوتون (ID: 4035) - Biblical name: Jeduthun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jeduthun', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یدوتون';

-- یشیه (ID: 4237) - Biblical name: Jeshiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jeshiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یشیه';

-- شلتى (ID: 4690) - Biblical name: Shealtiel
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Shealtiel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'شلتى';

-- صقلغ (ID: 4760) - Biblical name: Ziklag
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ziklag', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'صقلغ';

-- عنياه (ID: 5023) - Biblical name: Ananiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ananiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عنياه';

-- عمى (ID: 5134) - Biblical name: Ammi
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ammi', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عمى';

-- پليتوى (ID: 5380) - Biblical name: Pilate
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Pilate', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'پليتوى';

-- یعبیز (ID: 5422) - Biblical name: Jabez
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jabez', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعبیز';

-- ییزو (ID: 5457) - Biblical name: Jezu
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jezu', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ییزو';

-- مناحیم (ID: 6431) - Biblical name: Menahem
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Menahem', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مناحیم';

-- کننیا (ID: 7027) - Biblical name: Conaniah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Conaniah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'کننیا';

-- یزهار (ID: 7049) - Biblical name: Izhar
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Izhar', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یزهار';

-- یعزیا (ID: 7053) - Biblical name: Jehaziah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehaziah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعزیا';

-- عصيون (ID: 7350) - Biblical name: Azion
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Azion', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عصيون';

-- يعى (ID: 7528) - Biblical name: Jai
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jai', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'يعى';

-- متتیا (ID: 7835) - Biblical name: Mattithiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Mattithiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'متتیا';

-- شافاط (ID: 7852) - Biblical name: Shaphat
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Shaphat', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'شافاط';

-- یشعي (ID: 7865) - Biblical name: Jeshua
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jeshua', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یشعي';

-- مشلمیا (ID: 7884) - Biblical name: Meshullam
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Meshullam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مشلمیا';

-- یقمعام (ID: 7910) - Biblical name: Jekameam
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jekameam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یقمعام';

-- فقحیا (ID: 7972) - Biblical name: Pekahiah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Pekahiah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'فقحیا';

-- محزیوت (ID: 8929) - Biblical name: Mahaziot
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Mahaziot', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'محزیوت';

-- عیبر (ID: 8988) - Biblical name: Eber
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Eber', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیبر';

-- یحت (ID: 9000) - Biblical name: Jehath
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehath', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یحت';

-- محیر (ID: 9002) - Biblical name: Mahir
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Mahir', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'محیر';

-- معونوتای (ID: 9005) - Biblical name: Maonothai
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Maonothai', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'معونوتای';

-- مشماع (ID: 9006) - Biblical name: Meshsham
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Meshsham', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مشماع';

-- یریا (ID: 9053) - Biblical name: Jeriah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jeriah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یریا';

-- عیدر (ID: 9054) - Biblical name: Eder
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Eder', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیدر';

-- يحزى (ID: 9381) - Biblical name: Jehaz
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehaz', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'يحزى';

-- عیفر (ID: 10637) - Biblical name: Ephah
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ephah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیفر';

-- صوحر (ID: 10650) - Biblical name: Zohar
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zohar', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'صوحر';

-- یامین (ID: 10655) - Biblical name: Yamin
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Yamin', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یامین';

-- شوعال (ID: 10656) - Biblical name: Shual
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Shual', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'شوعال';

-- عماسای (ID: 10670) - Biblical name: Amasai
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Amasai', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عماسای';

-- عیون (ID: 10804) - Biblical name: Eyon
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Eyon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیون';

-- يحلى (ID: 11246) - Biblical name: Jehallelel
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jehallelel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'يحلى';

-- یوشع (ID: 12309) - Biblical name: Joshua
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Joshua', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوشع';

-- یعقوب (ID: 12485) - Biblical name: Jacob
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jacob', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعقوب';

-- بلعام (ID: 12639) - Biblical name: Balaam
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Balaam', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'بلعام';

-- یوحنا (ID: 13015) - Biblical name: John
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'John', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوحنا';
