-- Identify biblical proper nouns from verse context
-- Generated by analyzing verses containing these words and matching to English translations

-- Add word_type column if missing
ALTER TABLE word_frequencies ADD COLUMN word_type TEXT;

-- Update biblical names
-- Biblical name: اخى (Ahab)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Ahab', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اخى';

-- Biblical name: ايل (Hananeel)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Hananeel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ايل';

-- Biblical name: اِلى (Elealeh)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Elealeh', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اِلى';

-- Biblical name: اېل (Shealtiel)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Shealtiel', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اېل';

-- Biblical name: داود (David)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'David', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'داود';

-- Biblical name: سلیمان (Solomon)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Solomon', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'سلیمان';

-- Biblical name: لابان (Laban)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Laban', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'لابان';

-- Biblical name: مریم (Mary)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Mary', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مریم';

-- Biblical name: موسی (Moses)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Moses', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'موسی';

-- Biblical name: هارون (Aaron)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Aaron', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'هارون';

-- Biblical name: پولس (Jesus)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jesus', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'پولس';

-- Biblical name: یعقوب (James)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'James', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یعقوب';

-- Biblical name: یوحنا (John)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'John', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوحنا';

-- Biblical name: یوسف (Joseph)
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Joseph', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوسف';


-- Create index
CREATE INDEX IF NOT EXISTS idx_word_frequencies_word_type ON word_frequencies (word_type);