-- Mark words that are parts of compound biblical names
-- Generated by analyzing verse context

-- Add word_type column if missing
ALTER TABLE word_frequencies ADD COLUMN word_type TEXT;

-- Mark compound parts
-- ايل is part of compound: حنن‌ايل
-- Update word_frequencies to mark as part of compound
-- Note: May need to merge frequencies with compound form
UPDATE word_frequencies SET word_type = 'compound_part', base_word = 'حننايل', has_issues = 1, issue_flags = '["part_of_compound_name"]' WHERE pashto_word = 'ايل';

-- اخى is part of compound: اخى‌اب
-- Update word_frequencies to mark as part of compound
-- Note: May need to merge frequencies with compound form
UPDATE word_frequencies SET word_type = 'compound_part', base_word = 'اخىاب', has_issues = 1, issue_flags = '["part_of_compound_name"]' WHERE pashto_word = 'اخى';

-- اِلى is part of compound: اِلى‌عالى
-- Update word_frequencies to mark as part of compound
-- Note: May need to merge frequencies with compound form
UPDATE word_frequencies SET word_type = 'compound_part', base_word = 'اِلىعالى', has_issues = 1, issue_flags = '["part_of_compound_name"]' WHERE pashto_word = 'اِلى';

-- اېل is part of compound: شلتى‌اېل
-- Update word_frequencies to mark as part of compound
-- Note: May need to merge frequencies with compound form
UPDATE word_frequencies SET word_type = 'compound_part', base_word = 'شلتىاېل', has_issues = 1, issue_flags = '["part_of_compound_name"]' WHERE pashto_word = 'اېل';


-- Create index
CREATE INDEX IF NOT EXISTS idx_word_frequencies_word_type ON word_frequencies (word_type);