-- Merge punctuation variants in word_frequencies and word_verse_mapping
-- Generated by merge-punctuation-variants.py
-- This consolidates entries like 'شول.' and 'شول،' into 'شول'

-- IMPORTANT: word_verse_mapping is the source of punctuation variants
-- Update it first to clean the word forms at the source
-- Then merge duplicates in word_frequencies


-- Merge 8 variants of 'دی': دی., دی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'دی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی!»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی.»]';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی.)';
DELETE FROM word_verse_mapping WHERE pashto_word = 'دی).';

-- Sum frequencies from all variants: 8059 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 8059
WHERE pashto_word = 'دی' AND pashto_word NOT IN ('دی.','دی،','دی.»','دی!','دی!»','دی.»]','دی.)','دی).');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('دی', 8059);

-- Delete 8 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'دی.';
DELETE FROM word_frequencies WHERE pashto_word = 'دی،';
DELETE FROM word_frequencies WHERE pashto_word = 'دی.»';
DELETE FROM word_frequencies WHERE pashto_word = 'دی!';
DELETE FROM word_frequencies WHERE pashto_word = 'دی!»';
DELETE FROM word_frequencies WHERE pashto_word = 'دی.»]';
DELETE FROM word_frequencies WHERE pashto_word = 'دی.)';
DELETE FROM word_frequencies WHERE pashto_word = 'دی).';

-- Merge 5 variants of 'شی': شی., شی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'شی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شی.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شی!»';

-- Sum frequencies from all variants: 5690 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 5690
WHERE pashto_word = 'شی' AND pashto_word NOT IN ('شی.','شی،','شی.»','شی!','شی!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شی', 5690);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شی.';
DELETE FROM word_frequencies WHERE pashto_word = 'شی،';
DELETE FROM word_frequencies WHERE pashto_word = 'شی.»';
DELETE FROM word_frequencies WHERE pashto_word = 'شی!';
DELETE FROM word_frequencies WHERE pashto_word = 'شی!»';

-- Merge 1 variants of 'چې': چې،

DELETE FROM word_verse_mapping WHERE pashto_word = 'چې،';

-- Sum frequencies from all variants: 2753 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2753
WHERE pashto_word = 'چې' AND pashto_word NOT IN ('چې،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('چې', 2753);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'چې،';

-- Merge 2 variants of 'وی': وی., وی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وی،';

-- Sum frequencies from all variants: 4258 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 4258
WHERE pashto_word = 'وی' AND pashto_word NOT IN ('وی.','وی،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وی', 4258);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وی.';
DELETE FROM word_frequencies WHERE pashto_word = 'وی،';

-- Merge 6 variants of 'وو': وو., وو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وو.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وو.)';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وو!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وو)،';

-- Sum frequencies from all variants: 3351 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3351
WHERE pashto_word = 'وو' AND pashto_word NOT IN ('وو.','وو،','وو.»','وو.)','وو!','وو)،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وو', 3351);

-- Delete 6 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وو.';
DELETE FROM word_frequencies WHERE pashto_word = 'وو،';
DELETE FROM word_frequencies WHERE pashto_word = 'وو.»';
DELETE FROM word_frequencies WHERE pashto_word = 'وو.)';
DELETE FROM word_frequencies WHERE pashto_word = 'وو!';
DELETE FROM word_frequencies WHERE pashto_word = 'وو)،';

-- Merge 5 variants of 'کوی': کوی., کوی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی!»';

-- Sum frequencies from all variants: 3613 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3613
WHERE pashto_word = 'کوی' AND pashto_word NOT IN ('کوی.','کوی،','کوی.»','کوی!','کوی!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوی', 3613);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوی.';
DELETE FROM word_frequencies WHERE pashto_word = 'کوی،';
DELETE FROM word_frequencies WHERE pashto_word = 'کوی.»';
DELETE FROM word_frequencies WHERE pashto_word = 'کوی!';
DELETE FROM word_frequencies WHERE pashto_word = 'کوی!»';

-- Merge 5 variants of 'کړی': کړی., کړی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی!»';

-- Sum frequencies from all variants: 3132 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3132
WHERE pashto_word = 'کړی' AND pashto_word NOT IN ('کړی.','کړی،','کړی.»','کړی!','کړی!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړی', 3132);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړی.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړی،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړی.»';
DELETE FROM word_frequencies WHERE pashto_word = 'کړی!';
DELETE FROM word_frequencies WHERE pashto_word = 'کړی!»';

-- Merge 2 variants of 'وفرمایيل': وفرمایيل،, وفرمایيل.

DELETE FROM word_verse_mapping WHERE pashto_word = 'وفرمایيل،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وفرمایيل.';

-- Sum frequencies from all variants: 1257 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1257
WHERE pashto_word = 'وفرمایيل' AND pashto_word NOT IN ('وفرمایيل،','وفرمایيل.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وفرمایيل', 1257);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وفرمایيل،';
DELETE FROM word_frequencies WHERE pashto_word = 'وفرمایيل.';

-- Merge 5 variants of 'شو': شو., شو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'شو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شو.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شو!»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شو.»]';

-- Sum frequencies from all variants: 1995 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1995
WHERE pashto_word = 'شو' AND pashto_word NOT IN ('شو.','شو،','شو.»','شو!»','شو.»]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شو', 1995);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شو.';
DELETE FROM word_frequencies WHERE pashto_word = 'شو،';
DELETE FROM word_frequencies WHERE pashto_word = 'شو.»';
DELETE FROM word_frequencies WHERE pashto_word = 'شو!»';
DELETE FROM word_frequencies WHERE pashto_word = 'شو.»]';

-- Merge 2 variants of 'وویيل': وویيل،, وویيل.

DELETE FROM word_verse_mapping WHERE pashto_word = 'وویيل،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وویيل.';

-- Sum frequencies from all variants: 1193 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1193
WHERE pashto_word = 'وویيل' AND pashto_word NOT IN ('وویيل،','وویيل.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وویيل', 1193);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وویيل،';
DELETE FROM word_frequencies WHERE pashto_word = 'وویيل.';

-- Merge 3 variants of 'وُو': وُو., وُو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وُو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وُو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وُو.)';

-- Sum frequencies from all variants: 1844 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1844
WHERE pashto_word = 'وُو' AND pashto_word NOT IN ('وُو.','وُو،','وُو.)');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وُو', 1844);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وُو.';
DELETE FROM word_frequencies WHERE pashto_word = 'وُو،';
DELETE FROM word_frequencies WHERE pashto_word = 'وُو.)';

-- Merge 6 variants of 'ده': ده., ده،

DELETE FROM word_verse_mapping WHERE pashto_word = 'ده.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ده،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ده.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ده!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ده.)';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ده!»';

-- Sum frequencies from all variants: 1971 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1971
WHERE pashto_word = 'ده' AND pashto_word NOT IN ('ده.','ده،','ده.»','ده!','ده.)','ده!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ده', 1971);

-- Delete 6 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ده.';
DELETE FROM word_frequencies WHERE pashto_word = 'ده،';
DELETE FROM word_frequencies WHERE pashto_word = 'ده.»';
DELETE FROM word_frequencies WHERE pashto_word = 'ده!';
DELETE FROM word_frequencies WHERE pashto_word = 'ده.)';
DELETE FROM word_frequencies WHERE pashto_word = 'ده!»';

-- Merge 5 variants of 'وکړی': وکړی., وکړی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی!»';

-- Sum frequencies from all variants: 1672 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1672
WHERE pashto_word = 'وکړی' AND pashto_word NOT IN ('وکړی.','وکړی،','وکړی!','وکړی.»','وکړی!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړی', 1672);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی.';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی،';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی!';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی.»';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی!»';

-- Merge 3 variants of 'وه': وه., وه،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وه.»';

-- Sum frequencies from all variants: 1364 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1364
WHERE pashto_word = 'وه' AND pashto_word NOT IN ('وه.','وه،','وه.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وه', 1364);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وه.';
DELETE FROM word_frequencies WHERE pashto_word = 'وه،';
DELETE FROM word_frequencies WHERE pashto_word = 'وه.»';

-- Merge 3 variants of 'شول': شول., شول،

DELETE FROM word_verse_mapping WHERE pashto_word = 'شول.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شول،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شول.»';

-- Sum frequencies from all variants: 1106 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1106
WHERE pashto_word = 'شول' AND pashto_word NOT IN ('شول.','شول،','شول.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شول', 1106);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شول.';
DELETE FROM word_frequencies WHERE pashto_word = 'شول،';
DELETE FROM word_frequencies WHERE pashto_word = 'شول.»';

-- Merge 3 variants of 'کړم': کړم., کړم،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړم.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړم،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړم.»';

-- Sum frequencies from all variants: 1212 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1212
WHERE pashto_word = 'کړم' AND pashto_word NOT IN ('کړم.','کړم،','کړم.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړم', 1212);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړم.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړم،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړم.»';

-- Merge 5 variants of 'یم': یم., یم،

DELETE FROM word_verse_mapping WHERE pashto_word = 'یم.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یم،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یم.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یم!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یم!»';

-- Sum frequencies from all variants: 1257 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1257
WHERE pashto_word = 'یم' AND pashto_word NOT IN ('یم.','یم،','یم.»','یم!','یم!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یم', 1257);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یم.';
DELETE FROM word_frequencies WHERE pashto_word = 'یم،';
DELETE FROM word_frequencies WHERE pashto_word = 'یم.»';
DELETE FROM word_frequencies WHERE pashto_word = 'یم!';
DELETE FROM word_frequencies WHERE pashto_word = 'یم!»';

-- Merge 5 variants of 'کړه': کړه., کړه،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه!»';

-- Sum frequencies from all variants: 1202 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1202
WHERE pashto_word = 'کړه' AND pashto_word NOT IN ('کړه.','کړه،','کړه.»','کړه!','کړه!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړه', 1202);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړه.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړه،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړه.»';
DELETE FROM word_frequencies WHERE pashto_word = 'کړه!';
DELETE FROM word_frequencies WHERE pashto_word = 'کړه!»';

-- Merge 2 variants of 'کړل': کړل., کړل،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړل.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړل،';

-- Sum frequencies from all variants: 954 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 954
WHERE pashto_word = 'کړل' AND pashto_word NOT IN ('کړل.','کړل،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړل', 954);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړل.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړل،';

-- Merge 3 variants of 'کړو': کړو., کړو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړو.»';

-- Sum frequencies from all variants: 996 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 996
WHERE pashto_word = 'کړو' AND pashto_word NOT IN ('کړو.','کړو،','کړو.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړو', 996);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړو.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړو،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړو.»';

-- Merge 5 variants of 'ؤ': ؤ،, ؤ.

DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ.)';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ)،';

-- Sum frequencies from all variants: 1236 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 1236
WHERE pashto_word = 'ؤ' AND pashto_word NOT IN ('ؤ،','ؤ.','ؤ.»','ؤ.)','ؤ)،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ؤ', 1236);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ،';
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ.';
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ.»';
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ.)';
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ)،';

-- Merge 2 variants of 'کیږی': کیږی., کیږی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کیږی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کیږی،';

-- Sum frequencies from all variants: 893 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 893
WHERE pashto_word = 'کیږی' AND pashto_word NOT IN ('کیږی.','کیږی،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کیږی', 893);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کیږی.';
DELETE FROM word_frequencies WHERE pashto_word = 'کیږی،';

-- Merge 3 variants of 'وکړو': وکړو،, وکړو.

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړو.»';

-- Sum frequencies from all variants: 907 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 907
WHERE pashto_word = 'وکړو' AND pashto_word NOT IN ('وکړو،','وکړو.','وکړو.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړو', 907);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړو،';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړو.';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړو.»';

-- Merge 5 variants of 'وکړه': وکړه., وکړه،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه!»';

-- Sum frequencies from all variants: 884 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 884
WHERE pashto_word = 'وکړه' AND pashto_word NOT IN ('وکړه.','وکړه،','وکړه.»','وکړه!','وکړه!»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړه', 884);

-- Delete 5 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه.';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه،';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه.»';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه!';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه!»';

-- Merge 2 variants of 'خُدايه': خُدايه،, خُدايه.

DELETE FROM word_verse_mapping WHERE pashto_word = 'خُدايه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'خُدايه.';

-- Sum frequencies from all variants: 469 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 469
WHERE pashto_word = 'خُدايه' AND pashto_word NOT IN ('خُدايه،','خُدايه.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('خُدايه', 469);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'خُدايه،';
DELETE FROM word_frequencies WHERE pashto_word = 'خُدايه.';

-- Merge 2 variants of 'ورکړو': ورکړو،, ورکړو.

DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړو،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړو.';

-- Sum frequencies from all variants: 557 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 557
WHERE pashto_word = 'ورکړو' AND pashto_word NOT IN ('ورکړو،','ورکړو.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ورکړو', 557);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړو،';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړو.';

-- Merge 4 variants of 'وې': وې., وې،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وې.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وې،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وې.)';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وې.»';

-- Sum frequencies from all variants: 683 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 683
WHERE pashto_word = 'وې' AND pashto_word NOT IN ('وې.','وې،','وې.)','وې.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وې', 683);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وې.';
DELETE FROM word_frequencies WHERE pashto_word = 'وې،';
DELETE FROM word_frequencies WHERE pashto_word = 'وې.)';
DELETE FROM word_frequencies WHERE pashto_word = 'وې.»';

-- Merge 2 variants of 'فرمایى': فرمایى،, فرمایى.

DELETE FROM word_verse_mapping WHERE pashto_word = 'فرمایى،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'فرمایى.';

-- Sum frequencies from all variants: 550 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 550
WHERE pashto_word = 'فرمایى' AND pashto_word NOT IN ('فرمایى،','فرمایى.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('فرمایى', 550);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'فرمایى،';
DELETE FROM word_frequencies WHERE pashto_word = 'فرمایى.';

-- Merge 7 variants of 'نه': نه،, نه.

DELETE FROM word_verse_mapping WHERE pashto_word = 'نه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'نه.';
DELETE FROM word_verse_mapping WHERE pashto_word = '«نه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'نه!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'نه.»';
DELETE FROM word_verse_mapping WHERE pashto_word = '«نه.»';
DELETE FROM word_verse_mapping WHERE pashto_word = '«نه!';

-- Sum frequencies from all variants: 534 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 534
WHERE pashto_word = 'نه' AND pashto_word NOT IN ('نه،','نه.','«نه،','نه!','نه.»','«نه.»','«نه!');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('نه', 534);

-- Delete 7 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'نه،';
DELETE FROM word_frequencies WHERE pashto_word = 'نه.';
DELETE FROM word_frequencies WHERE pashto_word = '«نه،';
DELETE FROM word_frequencies WHERE pashto_word = 'نه!';
DELETE FROM word_frequencies WHERE pashto_word = 'نه.»';
DELETE FROM word_frequencies WHERE pashto_word = '«نه.»';
DELETE FROM word_frequencies WHERE pashto_word = '«نه!';

-- Merge 3 variants of 'کړې': کړې., کړې،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړې.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړې،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړې.»';

-- Sum frequencies from all variants: 610 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 610
WHERE pashto_word = 'کړې' AND pashto_word NOT IN ('کړې.','کړې،','کړې.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړې', 610);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړې.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړې،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړې.»';

-- Merge 3 variants of 'شوه': شوه., شوه،

DELETE FROM word_verse_mapping WHERE pashto_word = 'شوه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شوه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شوه.»';

-- Sum frequencies from all variants: 463 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 463
WHERE pashto_word = 'شوه' AND pashto_word NOT IN ('شوه.','شوه،','شوه.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شوه', 463);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شوه.';
DELETE FROM word_frequencies WHERE pashto_word = 'شوه،';
DELETE FROM word_frequencies WHERE pashto_word = 'شوه.»';

-- Merge 4 variants of 'یې': یې،, یې.

DELETE FROM word_verse_mapping WHERE pashto_word = 'یې،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یې.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یې.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یې!';

-- Sum frequencies from all variants: 589 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 589
WHERE pashto_word = 'یې' AND pashto_word NOT IN ('یې،','یې.','یې.»','یې!');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یې', 589);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یې،';
DELETE FROM word_frequencies WHERE pashto_word = 'یې.';
DELETE FROM word_frequencies WHERE pashto_word = 'یې.»';
DELETE FROM word_frequencies WHERE pashto_word = 'یې!';

-- Merge 4 variants of 'کړ': کړ., کړ،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړ.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړ،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړ.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کړ!';

-- Sum frequencies from all variants: 414 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 414
WHERE pashto_word = 'کړ' AND pashto_word NOT IN ('کړ.','کړ،','کړ.»','کړ!');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړ', 414);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړ.';
DELETE FROM word_frequencies WHERE pashto_word = 'کړ،';
DELETE FROM word_frequencies WHERE pashto_word = 'کړ.»';
DELETE FROM word_frequencies WHERE pashto_word = 'کړ!';

-- Merge 3 variants of 'ورکړی': ورکړی., ورکړی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړی.»';

-- Sum frequencies from all variants: 443 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 443
WHERE pashto_word = 'ورکړی' AND pashto_word NOT IN ('ورکړی.','ورکړی،','ورکړی.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ورکړی', 443);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړی.';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړی،';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړی.»';

-- Merge 3 variants of 'یی': یی., یی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'یی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'یی.»';

-- Sum frequencies from all variants: 501 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 501
WHERE pashto_word = 'یی' AND pashto_word NOT IN ('یی.','یی،','یی.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یی', 501);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یی.';
DELETE FROM word_frequencies WHERE pashto_word = 'یی،';
DELETE FROM word_frequencies WHERE pashto_word = 'یی.»';

-- Merge 3 variants of 'ورکوی': ورکوی., ورکوی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکوی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکوی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکوی.»';

-- Sum frequencies from all variants: 434 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 434
WHERE pashto_word = 'ورکوی' AND pashto_word NOT IN ('ورکوی.','ورکوی،','ورکوی.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ورکوی', 434);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ورکوی.';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکوی،';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکوی.»';

-- Merge 3 variants of 'کوم': کوم., کوم،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوم.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوم،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوم.»';

-- Sum frequencies from all variants: 487 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 487
WHERE pashto_word = 'کوم' AND pashto_word NOT IN ('کوم.','کوم،','کوم.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوم', 487);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوم.';
DELETE FROM word_frequencies WHERE pashto_word = 'کوم،';
DELETE FROM word_frequencies WHERE pashto_word = 'کوم.»';

-- Merge 4 variants of 'شي': شي.», شي!»

DELETE FROM word_verse_mapping WHERE pashto_word = 'شي.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شي!»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شي.]';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شي.]»';

-- Sum frequencies from all variants: 206 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 206
WHERE pashto_word = 'شي' AND pashto_word NOT IN ('شي.»','شي!»','شي.]','شي.]»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شي', 206);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شي.»';
DELETE FROM word_frequencies WHERE pashto_word = 'شي!»';
DELETE FROM word_frequencies WHERE pashto_word = 'شي.]';
DELETE FROM word_frequencies WHERE pashto_word = 'شي.]»';

-- Merge 2 variants of 'لاړل': لاړل., لاړل،

DELETE FROM word_verse_mapping WHERE pashto_word = 'لاړل.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'لاړل،';

-- Sum frequencies from all variants: 283 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 283
WHERE pashto_word = 'لاړل' AND pashto_word NOT IN ('لاړل.','لاړل،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('لاړل', 283);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'لاړل.';
DELETE FROM word_frequencies WHERE pashto_word = 'لاړل،';

-- Merge 3 variants of 'راشی': راشی،, راشی.

DELETE FROM word_verse_mapping WHERE pashto_word = 'راشی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'راشی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'راشی.»';

-- Sum frequencies from all variants: 345 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 345
WHERE pashto_word = 'راشی' AND pashto_word NOT IN ('راشی،','راشی.','راشی.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('راشی', 345);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'راشی،';
DELETE FROM word_frequencies WHERE pashto_word = 'راشی.';
DELETE FROM word_frequencies WHERE pashto_word = 'راشی.»';

-- Merge 3 variants of 'نشته': نشته., نشته،

DELETE FROM word_verse_mapping WHERE pashto_word = 'نشته.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'نشته،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'نشته.»';

-- Sum frequencies from all variants: 288 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 288
WHERE pashto_word = 'نشته' AND pashto_word NOT IN ('نشته.','نشته،','نشته.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('نشته', 288);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'نشته.';
DELETE FROM word_frequencies WHERE pashto_word = 'نشته،';
DELETE FROM word_frequencies WHERE pashto_word = 'نشته.»';

-- Merge 2 variants of 'کولو': کولو., کولو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کولو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کولو،';

-- Sum frequencies from all variants: 316 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 316
WHERE pashto_word = 'کولو' AND pashto_word NOT IN ('کولو.','کولو،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کولو', 316);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کولو.';
DELETE FROM word_frequencies WHERE pashto_word = 'کولو،';

-- Merge 2 variants of 'اوسیږی': اوسیږی., اوسیږی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'اوسیږی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'اوسیږی،';

-- Sum frequencies from all variants: 307 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 307
WHERE pashto_word = 'اوسیږی' AND pashto_word NOT IN ('اوسیږی.','اوسیږی،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('اوسیږی', 307);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'اوسیږی.';
DELETE FROM word_frequencies WHERE pashto_word = 'اوسیږی،';

-- Merge 3 variants of 'ورکړه': ورکړه., ورکړه،

DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکړه.»';

-- Sum frequencies from all variants: 267 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 267
WHERE pashto_word = 'ورکړه' AND pashto_word NOT IN ('ورکړه.','ورکړه،','ورکړه.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ورکړه', 267);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړه.';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړه،';
DELETE FROM word_frequencies WHERE pashto_word = 'ورکړه.»';

-- Merge 2 variants of 'لاړو': لاړو., لاړو،

DELETE FROM word_verse_mapping WHERE pashto_word = 'لاړو.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'لاړو،';

-- Sum frequencies from all variants: 246 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 246
WHERE pashto_word = 'لاړو' AND pashto_word NOT IN ('لاړو.','لاړو،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('لاړو', 246);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'لاړو.';
DELETE FROM word_frequencies WHERE pashto_word = 'لاړو،';

-- Merge 3 variants of 'لری': لری،, لری.

DELETE FROM word_verse_mapping WHERE pashto_word = 'لری،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'لری.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'لری.»';

-- Sum frequencies from all variants: 311 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 311
WHERE pashto_word = 'لری' AND pashto_word NOT IN ('لری،','لری.','لری.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('لری', 311);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'لری،';
DELETE FROM word_frequencies WHERE pashto_word = 'لری.';
DELETE FROM word_frequencies WHERE pashto_word = 'لری.»';

-- Merge 2 variants of 'شوې': شوې., شوې،

DELETE FROM word_verse_mapping WHERE pashto_word = 'شوې.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شوې،';

-- Sum frequencies from all variants: 254 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 254
WHERE pashto_word = 'شوې' AND pashto_word NOT IN ('شوې.','شوې،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شوې', 254);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شوې.';
DELETE FROM word_frequencies WHERE pashto_word = 'شوې،';

-- Merge 3 variants of 'وکړم': وکړم., وکړم،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړم.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړم،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړم.»';

-- Sum frequencies from all variants: 289 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 289
WHERE pashto_word = 'وکړم' AND pashto_word NOT IN ('وکړم.','وکړم،','وکړم.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړم', 289);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړم.';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړم،';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړم.»';

-- Merge 2 variants of 'کوله': کوله., کوله،

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوله.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کوله،';

-- Sum frequencies from all variants: 259 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 259
WHERE pashto_word = 'کوله' AND pashto_word NOT IN ('کوله.','کوله،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوله', 259);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوله.';
DELETE FROM word_frequencies WHERE pashto_word = 'کوله،';

-- Merge 2 variants of 'څښتنه': څښتنه،, څښتنه!

DELETE FROM word_verse_mapping WHERE pashto_word = 'څښتنه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'څښتنه!';

-- Sum frequencies from all variants: 168 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 168
WHERE pashto_word = 'څښتنه' AND pashto_word NOT IN ('څښتنه،','څښتنه!');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('څښتنه', 168);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'څښتنه،';
DELETE FROM word_frequencies WHERE pashto_word = 'څښتنه!';

-- Merge 4 variants of 'وکړ': وکړ., وکړ،

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړ.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړ،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړ.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړ.]';

-- Sum frequencies from all variants: 212 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 212
WHERE pashto_word = 'وکړ' AND pashto_word NOT IN ('وکړ.','وکړ،','وکړ.»','وکړ.]');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړ', 212);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړ.';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړ،';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړ.»';
DELETE FROM word_frequencies WHERE pashto_word = 'وکړ.]';

-- Merge 3 variants of 'ګوری': ګوری،, ګوری.

DELETE FROM word_verse_mapping WHERE pashto_word = 'ګوری،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ګوری.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ګوری!';

-- Sum frequencies from all variants: 166 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 166
WHERE pashto_word = 'ګوری' AND pashto_word NOT IN ('ګوری،','ګوری.','ګوری!');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ګوری', 166);

-- Delete 3 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ګوری،';
DELETE FROM word_frequencies WHERE pashto_word = 'ګوری.';
DELETE FROM word_frequencies WHERE pashto_word = 'ګوری!';

-- Merge 2 variants of 'وایى': وایى،, وایى.

DELETE FROM word_verse_mapping WHERE pashto_word = 'وایى،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'وایى.';

-- Sum frequencies from all variants: 231 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 231
WHERE pashto_word = 'وایى' AND pashto_word NOT IN ('وایى،','وایى.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وایى', 231);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وایى،';
DELETE FROM word_frequencies WHERE pashto_word = 'وایى.';

-- Merge 2 variants of 'ویيل': ویيل،, ویيل.

DELETE FROM word_verse_mapping WHERE pashto_word = 'ویيل،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ویيل.';

-- Sum frequencies from all variants: 162 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 162
WHERE pashto_word = 'ویيل' AND pashto_word NOT IN ('ویيل،','ویيل.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ویيل', 162);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ویيل،';
DELETE FROM word_frequencies WHERE pashto_word = 'ویيل.';

-- Merge 4 variants of 'ونیسی': ونیسی., ونیسی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'ونیسی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ونیسی،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ونیسی!';
DELETE FROM word_verse_mapping WHERE pashto_word = 'ونیسی.»';

-- Sum frequencies from all variants: 221 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 221
WHERE pashto_word = 'ونیسی' AND pashto_word NOT IN ('ونیسی.','ونیسی،','ونیسی!','ونیسی.»');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ونیسی', 221);

-- Delete 4 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ونیسی.';
DELETE FROM word_frequencies WHERE pashto_word = 'ونیسی،';
DELETE FROM word_frequencies WHERE pashto_word = 'ونیسی!';
DELETE FROM word_frequencies WHERE pashto_word = 'ونیسی.»';

-- Merge 2 variants of 'راځی': راځی., راځی،

DELETE FROM word_verse_mapping WHERE pashto_word = 'راځی.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'راځی،';

-- Sum frequencies from all variants: 233 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 233
WHERE pashto_word = 'راځی' AND pashto_word NOT IN ('راځی.','راځی،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('راځی', 233);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'راځی.';
DELETE FROM word_frequencies WHERE pashto_word = 'راځی،';

-- Merge 1 variants of 'خُدای': خُدای،

DELETE FROM word_verse_mapping WHERE pashto_word = 'خُدای،';

-- Sum frequencies from all variants: 140 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 140
WHERE pashto_word = 'خُدای' AND pashto_word NOT IN ('خُدای،');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('خُدای', 140);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'خُدای،';

-- Merge 2 variants of 'کښې': کښې،, کښې.

DELETE FROM word_verse_mapping WHERE pashto_word = 'کښې،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'کښې.';

-- Sum frequencies from all variants: 150 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 150
WHERE pashto_word = 'کښې' AND pashto_word NOT IN ('کښې،','کښې.');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کښې', 150);

-- Delete 2 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کښې،';
DELETE FROM word_frequencies WHERE pashto_word = 'کښې.';

-- Merge 5 variants of 'شه': شه،, شه.

DELETE FROM word_verse_mapping WHERE pashto_word = 'شه،';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شه.';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شه.»';
DELETE FROM word_verse_mapping WHERE pashto_word = 'شه!';
