-- Merge punctuation variants in word_frequencies and word_verse_mapping
-- Generated by merge-punctuation-variants.py
-- This consolidates entries like 'شول.' and 'شول،' into 'شول'

-- IMPORTANT: word_verse_mapping is the source of punctuation variants
-- Update it first to clean the word forms at the source
-- Then merge duplicates in word_frequencies


-- Merge 1 variants of 'دي': دي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'دي.›';

-- Sum frequencies from all variants: 49 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 49
WHERE pashto_word = 'دي' AND pashto_word NOT IN ('دي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('دي', 49);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'دي.›';

-- Merge 1 variants of 'یم': یم.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'یم.›';

-- Sum frequencies from all variants: 44 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 44
WHERE pashto_word = 'یم' AND pashto_word NOT IN ('یم.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یم', 44);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یم.›';

-- Merge 1 variants of 'شي': شي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شي.›';

-- Sum frequencies from all variants: 32 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 32
WHERE pashto_word = 'شي' AND pashto_word NOT IN ('شي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شي', 32);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شي.›';

-- Merge 1 variants of 'دی': دی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'دی.›';

-- Sum frequencies from all variants: 21 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 21
WHERE pashto_word = 'دی' AND pashto_word NOT IN ('دی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('دی', 21);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'دی.›';

-- Merge 1 variants of 'وي': وي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وي.›';

-- Sum frequencies from all variants: 13 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 13
WHERE pashto_word = 'وي' AND pashto_word NOT IN ('وي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وي', 13);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وي.›';

-- Merge 1 variants of 'ده': ده.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ده.›';

-- Sum frequencies from all variants: 11 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 11
WHERE pashto_word = 'ده' AND pashto_word NOT IN ('ده.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ده', 11);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ده.›';

-- Merge 1 variants of 'کړی': کړی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړی.›';

-- Sum frequencies from all variants: 9 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 9
WHERE pashto_word = 'کړی' AND pashto_word NOT IN ('کړی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړی', 9);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړی.›';

-- Merge 1 variants of 'شی': شی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شی.›';

-- Sum frequencies from all variants: 9 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 9
WHERE pashto_word = 'شی' AND pashto_word NOT IN ('شی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شی', 9);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شی.›';

-- Merge 1 variants of 'کړم': کړم.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړم.›';

-- Sum frequencies from all variants: 7 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 7
WHERE pashto_word = 'کړم' AND pashto_word NOT IN ('کړم.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړم', 7);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړم.›';

-- Merge 1 variants of 'کیږي': کیږي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کیږي.›';

-- Sum frequencies from all variants: 6 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 6
WHERE pashto_word = 'کیږي' AND pashto_word NOT IN ('کیږي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کیږي', 6);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کیږي.›';

-- Merge 1 variants of 'وکړم': وکړم.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړم.›';

-- Sum frequencies from all variants: 6 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 6
WHERE pashto_word = 'وکړم' AND pashto_word NOT IN ('وکړم.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړم', 6);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړم.›';

-- Merge 1 variants of 'شه': شه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شه.›';

-- Sum frequencies from all variants: 5 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 5
WHERE pashto_word = 'شه' AND pashto_word NOT IN ('شه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شه', 5);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شه.›';

-- Merge 1 variants of 'کړه': کړه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړه.›';

-- Sum frequencies from all variants: 4 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 4
WHERE pashto_word = 'کړه' AND pashto_word NOT IN ('کړه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړه', 4);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړه.›';

-- Merge 1 variants of 'ؤ': ؤ.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ؤ.›';

-- Sum frequencies from all variants: 4 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 4
WHERE pashto_word = 'ؤ' AND pashto_word NOT IN ('ؤ.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ؤ', 4);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ؤ.›';

-- Merge 1 variants of 'راځي': راځي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'راځي.›';

-- Sum frequencies from all variants: 4 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 4
WHERE pashto_word = 'راځي' AND pashto_word NOT IN ('راځي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('راځي', 4);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'راځي.›';

-- Merge 1 variants of 'کوي': کوي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوي.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'کوي' AND pashto_word NOT IN ('کوي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوي', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوي.›';

-- Merge 1 variants of 'شو': شو.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شو.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'شو' AND pashto_word NOT IN ('شو.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شو', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شو.›';

-- Merge 1 variants of 'درکړم': درکړم.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'درکړم.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'درکړم' AND pashto_word NOT IN ('درکړم.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('درکړم', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'درکړم.›';

-- Merge 1 variants of 'راکړه': راکړه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'راکړه.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'راکړه' AND pashto_word NOT IN ('راکړه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('راکړه', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'راکړه.›';

-- Merge 1 variants of 'وکړي': وکړي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړي.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'وکړي' AND pashto_word NOT IN ('وکړي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړي', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړي.›';

-- Merge 1 variants of 'ورکوم': ورکوم.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ورکوم.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'ورکوم' AND pashto_word NOT IN ('ورکوم.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ورکوم', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ورکوم.›';

-- Merge 1 variants of 'کوه': کوه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوه.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'کوه' AND pashto_word NOT IN ('کوه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوه', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوه.›';

-- Merge 1 variants of 'کوی': کوی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوی.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'کوی' AND pashto_word NOT IN ('کوی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوی', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوی.›';

-- Merge 1 variants of 'ونیسی': ونیسی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ونیسی.›';

-- Sum frequencies from all variants: 3 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 3
WHERE pashto_word = 'ونیسی' AND pashto_word NOT IN ('ونیسی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ونیسی', 3);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ونیسی.›';

-- Merge 1 variants of 'ومنه': ومنه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ومنه.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'ومنه' AND pashto_word NOT IN ('ومنه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ومنه', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ومنه.›';

-- Merge 1 variants of 'شته': شته.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شته.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'شته' AND pashto_word NOT IN ('شته.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شته', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شته.›';

-- Merge 1 variants of 'راکړي': راکړي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'راکړي.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'راکړي' AND pashto_word NOT IN ('راکړي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('راکړي', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'راکړي.›';

-- Merge 1 variants of 'ولیکه': ولیکه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ولیکه.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'ولیکه' AND pashto_word NOT IN ('ولیکه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ولیکه', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ولیکه.›';

-- Merge 1 variants of 'کوې': کوې.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کوې.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'کوې' AND pashto_word NOT IN ('کوې.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کوې', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کوې.›';

-- Merge 1 variants of 'ژړل': ژړل.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'ژړل.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'ژړل' AND pashto_word NOT IN ('ژړل.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('ژړل', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'ژړل.›';

-- Merge 1 variants of 'وکړه': وکړه.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړه.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'وکړه' AND pashto_word NOT IN ('وکړه.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړه', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړه.›';

-- Merge 1 variants of 'اوسي': اوسي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'اوسي.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'اوسي' AND pashto_word NOT IN ('اوسي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('اوسي', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'اوسي.›';

-- Merge 1 variants of 'وګټلې': وګټلې.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وګټلې.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'وګټلې' AND pashto_word NOT IN ('وګټلې.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وګټلې', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وګټلې.›';

-- Merge 1 variants of 'څښتنه! ته': ‹څښتنه! ته

DELETE FROM word_verse_mapping WHERE pashto_word = '‹څښتنه! ته';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'څښتنه! ته' AND pashto_word NOT IN ('‹څښتنه! ته');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('څښتنه! ته', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = '‹څښتنه! ته';

-- Merge 1 variants of 'کړې': کړې.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'کړې.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'کړې' AND pashto_word NOT IN ('کړې.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('کړې', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'کړې.›';

-- Merge 1 variants of 'لړزیږي': لړزیږي.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'لړزیږي.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'لړزیږي' AND pashto_word NOT IN ('لړزیږي.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('لړزیږي', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'لړزیږي.›';

-- Merge 1 variants of 'شې': شې.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'شې.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'شې' AND pashto_word NOT IN ('شې.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('شې', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'شې.›';

-- Merge 1 variants of 'یې': یې!›

DELETE FROM word_verse_mapping WHERE pashto_word = 'یې!›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'یې' AND pashto_word NOT IN ('یې!›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یې', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یې!›';

-- Merge 1 variants of 'یو': یو.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'یو.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'یو' AND pashto_word NOT IN ('یو.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('یو', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'یو.›';

-- Merge 1 variants of 'وکړی': وکړی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'وکړی.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'وکړی' AND pashto_word NOT IN ('وکړی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('وکړی', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'وکړی.›';

-- Merge 1 variants of 'واخلی': واخلی.›

DELETE FROM word_verse_mapping WHERE pashto_word = 'واخلی.›';

-- Sum frequencies from all variants: 2 total occurrences
UPDATE word_frequencies SET
  frequency_total = frequency_total + 2
WHERE pashto_word = 'واخلی' AND pashto_word NOT IN ('واخلی.›');

INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('واخلی', 2);

-- Delete 1 punctuation variants
DELETE FROM word_frequencies WHERE pashto_word = 'واخلی.›';

