-- Split multi-word phrases into individual words
-- Generated by pattern matching

-- Postposition phrases ending with 'ته'

-- Process phrases ending with 'ته'
-- These will be split into [word] + 'ته'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% ته'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Postposition phrases ending with 'کې'

-- Process phrases ending with 'کې'
-- These will be split into [word] + 'کې'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% کې'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Postposition phrases ending with 'دپاره'

-- Process phrases ending with 'دپاره'
-- These will be split into [word] + 'دپاره'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% دپاره'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Postposition phrases ending with 'باندې'

-- Process phrases ending with 'باندې'
-- These will be split into [word] + 'باندې'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% باندې'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Postposition phrases ending with 'سره'

-- Process phrases ending with 'سره'
-- These will be split into [word] + 'سره'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% سره'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Postposition phrases ending with 'سربېره'

-- Process phrases ending with 'سربېره'
-- These will be split into [word] + 'سربېره'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% سربېره'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Preposition phrases starting with 'د'

-- Process phrases starting with 'د'
-- These will be split into 'د' + [word]
-- Example: 'د یوسف' -> 'د' + 'یوسف'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE 'د %'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pashto_word NOT LIKE 'د%کې'
  AND pashto_word NOT LIKE 'د%دپاره'
  AND pashto_word NOT LIKE 'د%په اړه'
  AND pashto_word NOT LIKE 'د%په بارې کې'
  AND pashto_word NOT LIKE 'د%سربېره'
  AND pashto_word NOT LIKE 'د%سره'
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Preposition phrases starting with 'په'

-- Process phrases starting with 'په'
-- These will be split into 'په' + [word]
-- Example: 'د یوسف' -> 'د' + 'یوسف'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE 'په %'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pashto_word NOT LIKE 'په%کې'
  AND pashto_word NOT LIKE 'په%دپاره'
  AND pashto_word NOT LIKE 'په%په اړه'
  AND pashto_word NOT LIKE 'په%په بارې کې'
  AND pashto_word NOT LIKE 'په%سربېره'
  AND pashto_word NOT LIKE 'په%سره'
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Preposition phrases starting with 'پر'

-- Process phrases starting with 'پر'
-- These will be split into 'پر' + [word]
-- Example: 'د یوسف' -> 'د' + 'یوسف'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE 'پر %'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pashto_word NOT LIKE 'پر%کې'
  AND pashto_word NOT LIKE 'پر%دپاره'
  AND pashto_word NOT LIKE 'پر%په اړه'
  AND pashto_word NOT LIKE 'پر%په بارې کې'
  AND pashto_word NOT LIKE 'پر%سربېره'
  AND pashto_word NOT LIKE 'پر%سره'
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Preposition phrases starting with 'له'

-- Process phrases starting with 'له'
-- These will be split into 'له' + [word]
-- Example: 'د یوسف' -> 'د' + 'یوسف'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE 'له %'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pashto_word NOT LIKE 'له%کې'
  AND pashto_word NOT LIKE 'له%دپاره'
  AND pashto_word NOT LIKE 'له%په اړه'
  AND pashto_word NOT LIKE 'له%په بارې کې'
  AND pashto_word NOT LIKE 'له%سربېره'
  AND pashto_word NOT LIKE 'له%سره'
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;

-- Particle phrases with 'به'

-- Process phrases containing 'به'
-- These will be split into [word] + 'به' or 'به' + [word]
-- Example: 'هغه به' -> 'هغه' + 'به'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE (pashto_word LIKE '% به' OR pashto_word LIKE 'به %')
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'particle_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;


-- Next step: Generate INSERT statements for each phrase marked as split_pending
-- This requires processing each phrase individually to extract word1 and word2