-- Update biblical names found in verses with multiple names
-- Generated by analyze-verses-with-names.py

-- ابراهیم (Abraham) - Update from noun to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Abraham', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ابراهیم';

-- اسحاق (Isaac) - Update from noun to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Isaac', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اسحاق';

-- عیسی (Jesus) - Update from noun to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Jesus', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیسی';

-- مریم (Mary) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Mary', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مریم';

-- پیلاتوس (Pilate) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Pilate', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'پیلاتوس';

-- یوسف (Joseph) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Joseph', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'یوسف';

-- موسی (Moses) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Moses', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'موسی';

-- هارون (Aaron) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Aaron', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'هارون';

-- عیسو (Esau) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Esau', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'عیسو';

-- مجدلیه (Magdalene) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Magdalene', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'مجدلیه';

-- تارح (Terah) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Terah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'تارح';

-- ناحور (Nahor) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Nahor', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'ناحور';

-- زبدي (Zebedee) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Zebedee', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'زبدي';

-- اوریا (Uriah) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Uriah', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'اوریا';

-- بنیامین (Benjamin) - Update from unknown to proper_noun
UPDATE word_frequencies SET word_type = 'proper_noun', pos = 'n. prop.', romanization = 'Benjamin', has_issues = 0, issue_flags = '[]' WHERE pashto_word = 'بنیامین';
