#!/usr/bin/env python3
"""
Delete all parts of compound biblical names.
Identifies compound proper names and deletes their individual parts.
"""

import json
import subprocess

def query_database(query):
    """Execute SQL query and return results"""
    result = subprocess.run(
        ['wrangler', 'd1', 'execute', 'pashto-bible-db', '--remote', '--command', query],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return []
    
    try:
        lines = result.stdout.strip().split('\n')
        json_start = -1
        for i, line in enumerate(lines):
            if line.strip().startswith('['):
                json_start = i
                break
        
        if json_start == -1:
            return []
        
        json_str = '\n'.join(lines[json_start:])
        output = json.loads(json_str)
        
        if output and len(output) > 0 and 'results' in output[0]:
            return output[0]['results']
        return []
    except Exception as e:
        print(f"Error parsing output: {e}")
        return []

def main():
    print("🔧 Identifying and deleting all compound name parts...\n")
    print("="*60)
    
    # Get all compound proper names
    query = """
    SELECT pashto_word, frequency_total, romanization
    FROM word_frequencies
    WHERE word_type = 'proper_noun'
      AND (pashto_word LIKE '%‌%' OR pashto_word LIKE '%-%' OR pashto_word LIKE '% %')
    ORDER BY frequency_total DESC
    """
    
    compound_names = query_database(query)
    print(f"Found {len(compound_names)} compound proper names\n")
    
    # Extract all parts
    all_parts = set()
    parts_to_names = {}
    
    for name_entry in compound_names:
        word = name_entry['pashto_word']
        parts = []
        
        # Split on zero-width space, hyphen, or space
        if '‌' in word:
            parts = word.split('‌')
        elif '-' in word:
            parts = word.split('-')
        elif ' ' in word:
            parts = word.split(' ')
        
        for part in parts:
            part = part.strip()
            if part:
                all_parts.add(part)
                if part not in parts_to_names:
                    parts_to_names[part] = []
                parts_to_names[part].append(word)
    
    print(f"Identified {len(all_parts)} unique parts:\n")
    for part in sorted(all_parts):
        names = parts_to_names[part]
        print(f"  {part} → part of: {', '.join(names)}")
    
    # Check which parts exist as separate entries
    print(f"\n{'='*60}")
    print("Checking which parts exist as separate entries...\n")
    
    parts_list = "','".join(all_parts)
    check_query = f"""
    SELECT pashto_word, frequency_total, word_type, pos
    FROM word_frequencies
    WHERE pashto_word IN ('{parts_list}')
    ORDER BY pashto_word
    """
    
    existing_parts = query_database(check_query)
    print(f"Found {len(existing_parts)} parts that exist as separate entries:\n")
    
    # Also check the user's specific words
    user_words = ['عزتۍ', 'اعلیحضرته', 'قِريَت', 'اب', 'عزر']
    user_query = f"""
    SELECT pashto_word, frequency_total, word_type, pos
    FROM word_frequencies
    WHERE pashto_word IN ('{"','".join(user_words)}')
    ORDER BY pashto_word
    """
    
    user_words_check = query_database(user_query)
    
    # Generate SQL
    sql_lines = [
        "-- Delete all parts of compound biblical names",
        "-- Generated by delete-all-compound-name-parts.py",
        "-- These parts exist separately but should only appear in compound forms",
        "",
    ]
    
    deleted_count = 0
    
    # Delete parts that are ONLY part of compound names
    for part_entry in existing_parts:
        part = part_entry['pashto_word']
        freq = part_entry['frequency_total']
        names = parts_to_names.get(part, [])
        
        if names:
            sql_lines.append(f"-- Delete '{part}' (freq: {freq}) - part of: {', '.join(names)}")
            sql_lines.append(f"DELETE FROM word_verse_mapping WHERE pashto_word = '{part.replace("'", "''")}';")
            sql_lines.append(f"DELETE FROM word_frequencies WHERE pashto_word = '{part.replace("'", "''")}';")
            sql_lines.append("")
            deleted_count += 1
    
    # Check user's words - if they're not proper names and don't appear independently, delete them
    # But keep اب since it's used in verb phrases
    for word_entry in user_words_check:
        word = word_entry['pashto_word']
        if word == 'اب':
            continue  # Keep اب as it's used in verb phrases
        
        # Check if it's a proper name
        if word_entry.get('word_type') != 'proper_noun':
            # Check if it appears in any proper names
            check_in_names = query_database(f"""
                SELECT COUNT(*) as count
                FROM word_frequencies
                WHERE word_type = 'proper_noun'
                  AND pashto_word LIKE '%{word}%'
                  AND pashto_word != '{word}'
            """)
            
            if check_in_names and check_in_names[0].get('count', 0) == 0:
                # Doesn't appear in proper names, safe to delete if it's a fragment
                sql_lines.append(f"-- Delete '{word}' - appears to be a fragment, not a proper name")
                sql_lines.append(f"DELETE FROM word_verse_mapping WHERE pashto_word = '{word.replace("'", "''")}';")
                sql_lines.append(f"DELETE FROM word_frequencies WHERE pashto_word = '{word.replace("'", "''")}';")
                sql_lines.append("")
                deleted_count += 1
    
    # Write SQL file
    sql_path = 'cloudflare/delete-all-compound-name-parts.sql'
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\n{'='*60}")
    print(f"✅ Generated SQL file: {sql_path}")
    print(f"\nSummary:")
    print(f"  - Found {len(compound_names)} compound proper names")
    print(f"  - Identified {len(all_parts)} unique parts")
    print(f"  - Found {len(existing_parts)} parts that exist separately")
    print(f"  - Will delete {deleted_count} part entries")
    print(f"\nNext steps:")
    print(f"  1. Review {sql_path}")
    print(f"  2. Run: wrangler d1 execute pashto-bible-db --remote --file {sql_path}")

if __name__ == '__main__':
    main()

