#!/usr/bin/env python3
"""
Fix orphaned frequency counts in word_frequencies.
Words with frequency_total > 0 but no entries in word_verse_mapping or video_word_mappings
should have their frequencies recalculated from source data.
"""

import json
import subprocess

def query_database(query):
    """Execute SQL query and return results"""
    result = subprocess.run(
        ['wrangler', 'd1', 'execute', 'pashto-bible-db', '--remote', '--command', query],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error: {result.stderr}")
        return []
    
    try:
        lines = result.stdout.strip().split('\n')
        json_start = -1
        for i, line in enumerate(lines):
            if line.strip().startswith('['):
                json_start = i
                break
        
        if json_start == -1:
            return []
        
        json_str = '\n'.join(lines[json_start:])
        output = json.loads(json_str)
        
        if output and len(output) > 0 and 'results' in output[0]:
            return output[0]['results']
        return []
    except Exception as e:
        print(f"Error parsing output: {e}")
        return []

def main():
    print("🔧 Fixing orphaned frequency counts...\n")
    print("="*60)
    
    # Step 1: Find orphaned words
    print("Step 1: Finding orphaned words...")
    orphaned_query = """
    SELECT 
      pashto_word,
      frequency_total
    FROM word_frequencies wf
    WHERE wf.frequency_total > 0
      AND wf.frequency_afghan2023_ot = 0
      AND wf.frequency_afghan2023_nt = 0
      AND wf.frequency_yousafzai2019_ot = 0
      AND wf.frequency_yousafzai2019_nt = 0
      AND NOT EXISTS (
        SELECT 1 FROM word_verse_mapping wvm 
        WHERE wvm.pashto_word = wf.pashto_word OR wvm.base_form = wf.pashto_word
      )
      AND NOT EXISTS (
        SELECT 1 FROM video_word_mappings vwm 
        WHERE vwm.pashto_word = wf.pashto_word
      )
    ORDER BY frequency_total DESC
    LIMIT 1000
    """
    
    orphaned = query_database(orphaned_query)
    print(f"Found {len(orphaned)} orphaned words\n")
    
    if not orphaned:
        print("No orphaned words found!")
        return
    
    # Step 2: Generate SQL to fix them
    sql_lines = [
        "-- Fix orphaned frequency counts",
        "-- Generated by fix-orphaned-frequencies.py",
        "-- These words have frequency_total > 0 but no entries in source tables",
        "-- Solution: Set frequency_total to 0 since they don't appear anywhere",
        "",
    ]
    
    fixed_count = 0
    total_frequency_reset = 0
    
    for word_entry in orphaned:
        word = word_entry.get('pashto_word', '')
        freq = word_entry.get('frequency_total', 0)
        
        sql_lines.append(f"-- Reset '{word}' (had {freq} but no source entries)")
        sql_lines.append(f"UPDATE word_frequencies SET frequency_total = 0 WHERE pashto_word = '{word.replace("'", "''")}';")
        sql_lines.append("")
        
        fixed_count += 1
        total_frequency_reset += freq
    
    # Write SQL file
    sql_path = 'cloudflare/fix-orphaned-frequencies.sql'
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\n{'='*60}")
    print(f"✅ Generated SQL file: {sql_path}")
    print(f"\nSummary:")
    print(f"  - Found {len(orphaned)} orphaned words")
    print(f"  - Will reset {fixed_count} words")
    print(f"  - Total frequency being reset: {total_frequency_reset}")
    print(f"\nNext steps:")
    print(f"  1. Review {sql_path}")
    print(f"  2. Run: wrangler d1 execute pashto-bible-db --remote --file {sql_path}")

if __name__ == '__main__':
    main()

