#!/usr/bin/env python3
"""
Generate splitting SQL - simpler version that processes known patterns

This generates SQL to split phrases by pattern matching rather than querying.
"""

from pathlib import Path

APP_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_SQL = APP_ROOT / 'cloudflare' / 'split-phrases-complete.sql'

POSTPOSITIONS = ['ته', 'کې', 'دپاره', 'باندې', 'سره', 'سربېره']
PREPOSITIONS = ['د', 'په', 'پر', 'له']
PARTICLES = ['به']


def split_phrase(phrase: str) -> tuple:
    """Split a phrase into component words"""
    words = phrase.split()
    
    if len(words) < 2:
        return (phrase, None, None)
    
    # Check for postposition (... ته)
    if words[-1] in POSTPOSITIONS:
        return (' '.join(words[:-1]), words[-1], 'postposition')
    
    # Check for preposition (د ...)
    if words[0] in PREPOSITIONS:
        return (words[0], ' '.join(words[1:]), 'preposition')
    
    # Check for particle (... به)
    if 'به' in words:
        idx = words.index('به')
        if idx > 0:
            return (' '.join(words[:idx]), 'به', 'particle')
        elif idx < len(words) - 1:
            return ('به', ' '.join(words[idx+1:]), 'particle')
    
    return (phrase, None, None)


def generate_sql_for_pattern(pattern: str, match_type: str, split_func) -> list:
    """Generate SQL for a specific pattern"""
    sql_statements = []
    
    # Use a CTE to find matching phrases, then split them
    sql_statements.append(f"-- Split {match_type} phrases matching pattern: {pattern}")
    sql_statements.append(f"""
-- Find phrases matching pattern
WITH phrases_to_split AS (
  SELECT id, pashto_word, frequency_total
  FROM word_frequencies
  WHERE pashto_word LIKE '{pattern}'
    AND pashto_word LIKE '% %'
    AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos = 'particle_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
    AND pos != 'circumposition'
    AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1
)
-- Note: Actual splitting logic would need to extract word1 and word2
-- This is a template - the Python script will generate specific INSERT statements
SELECT pashto_word FROM phrases_to_split LIMIT 10;
""")
    
    return sql_statements


def main():
    print("📝 Generating SQL to split phrases...\n")
    
    sql_statements = []
    sql_statements.append('-- Split multi-word phrases into individual words')
    sql_statements.append('-- Generated by pattern matching')
    sql_statements.append('')
    
    # Generate SQL for postposition patterns
    for post in POSTPOSITIONS:
        sql_statements.append(f"-- Postposition phrases ending with '{post}'")
        sql_statements.append(f"""
-- Process phrases ending with '{post}'
-- These will be split into [word] + '{post}'
-- Example: 'ما ته' -> 'ما' + 'ته'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '% {post}'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'postposition_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;
""")
    
    # Generate SQL for preposition patterns
    for prep in PREPOSITIONS:
        sql_statements.append(f"-- Preposition phrases starting with '{prep}'")
        sql_statements.append(f"""
-- Process phrases starting with '{prep}'
-- These will be split into '{prep}' + [word]
-- Example: 'د یوسف' -> 'د' + 'یوسف'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE pashto_word LIKE '{prep} %'
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pashto_word NOT LIKE '{prep}%کې'
  AND pashto_word NOT LIKE '{prep}%دپاره'
  AND pashto_word NOT LIKE '{prep}%په اړه'
  AND pashto_word NOT LIKE '{prep}%په بارې کې'
  AND pashto_word NOT LIKE '{prep}%سربېره'
  AND pashto_word NOT LIKE '{prep}%سره'
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;
""")
    
    # Generate SQL for particle patterns
    sql_statements.append("-- Particle phrases with 'به'")
    sql_statements.append("""
-- Process phrases containing 'به'
-- These will be split into [word] + 'به' or 'به' + [word]
-- Example: 'هغه به' -> 'هغه' + 'به'
UPDATE word_frequencies
SET pos = 'split_pending'
WHERE (pashto_word LIKE '% به' OR pashto_word LIKE 'به %')
  AND pashto_word LIKE '% %'
  AND (pos = 'phrase' OR pos = 'particle_phrase' OR pos IS NULL OR pos = '' OR pos = 'unknown')
  AND pos != 'circumposition'
  AND LENGTH(pashto_word) - LENGTH(REPLACE(pashto_word, ' ', '')) = 1;
""")
    
    sql_statements.append('')
    sql_statements.append('-- Next step: Generate INSERT statements for each phrase marked as split_pending')
    sql_statements.append('-- This requires processing each phrase individually to extract word1 and word2')
    
    OUTPUT_SQL.write_text('\n'.join(sql_statements), encoding='utf-8')
    
    print(f"   ✅ Generated {OUTPUT_SQL}")
    print("\n📋 This SQL marks phrases as 'split_pending'")
    print("   Next: Run a script to process each 'split_pending' phrase and generate INSERT statements")


if __name__ == '__main__':
    main()

