#!/usr/bin/env python3
"""
Merge word_frequencies entries that have punctuation variants.
For example: 'شول.' and 'شول' should be merged into 'شول'
"""

import json
import re
import subprocess
from collections import defaultdict

PUNCTUATION = ['،', '«', '»', '.', ',', '!', '?', ':', ';', '(', ')', '[', ']', '{', '}', '"', "'", '`', '"', '"', ''', ''', '›', '‹', '•', '-', '–', '—']

def clean_word(word):
    """Remove trailing/leading punctuation from a word"""
    # Remove trailing punctuation
    while word and word[-1] in PUNCTUATION:
        word = word[:-1]
    # Remove leading punctuation
    while word and word[0] in PUNCTUATION:
        word = word[1:]
    return word

def main():
    print("🔧 Merging punctuation variants in word_frequencies and word_verse_mapping...\n")
    print("="*60)
    
    # Read the JSON file we already fetched
    try:
        with open('/tmp/punctuation.json', 'r', encoding='utf-8') as f:
            content = f.read()
            
        # Parse JSON - find the start of JSON array
        json_start = content.find('[')
        if json_start == -1:
            print("❌ No JSON data found in /tmp/punctuation.json")
            return
        
        data = json.loads(content[json_start:])
        if not data or 'results' not in data[0]:
            print("❌ No results in JSON")
            return
        
        entries = data[0]['results']
        print(f"Found {len(entries)} words with punctuation\n")
        
    except Exception as e:
        print(f"❌ Error reading JSON: {e}")
        return
    
    # Group by cleaned word
    variants = defaultdict(list)
    for entry in entries:
        word = entry.get('pashto_word', '')
        cleaned = clean_word(word)
        if cleaned and cleaned != word:  # Only if cleaning changed something
            variants[cleaned].append(entry)
    
    print(f"Found {len(variants)} words with punctuation variants to merge\n")
    
    sql_lines = [
        "-- Merge punctuation variants in word_frequencies and word_verse_mapping",
        "-- Generated by merge-punctuation-variants.py",
        "-- This consolidates entries like 'شول.' and 'شول،' into 'شول'",
        "",
        "-- IMPORTANT: word_verse_mapping is the source of punctuation variants",
        "-- Update it first to clean the word forms at the source",
        "-- Then merge duplicates in word_frequencies",
        "",
        "BEGIN TRANSACTION;",
        "",
    ]
    
    merged_count = 0
    deleted_count = 0
    
    for cleaned_word, variant_entries in sorted(variants.items(), key=lambda x: -max(e.get('frequency_total', 0) for e in x[1])):
        if not cleaned_word:  # Skip empty words
            continue
        
        variant_words = [e.get('pashto_word') for e in variant_entries]
        total_freq = sum(e.get('frequency_total', 0) for e in variant_entries)
        
        sql_lines.append(f"-- Merge {len(variant_words)} variants of '{cleaned_word}': {', '.join(variant_words[:2])}")
        sql_lines.append("")
        
        # Step 1: Delete punctuation variants from word_verse_mapping
        # (Don't update them - that would create duplicates due to unique constraint)
        for variant_word in variant_words:
            sql_lines.append(f"DELETE FROM word_verse_mapping WHERE pashto_word = '{variant_word.replace("'", "''")}';")
        
        sql_lines.append("")
        
        # Step 2: Consolidate frequencies in word_frequencies
        # First, sum all variant frequencies and update the clean word
        variant_words_sql = ','.join(f"'{w.replace("'", "''")}'" for w in variant_words)
        
        sql_lines.append(f"-- Sum frequencies from all variants: {total_freq} total occurrences")
        sql_lines.append(f"UPDATE word_frequencies SET")
        sql_lines.append(f"  frequency_total = frequency_total + {total_freq}")
        sql_lines.append(f"WHERE pashto_word = '{cleaned_word.replace("'", "''")}' AND pashto_word NOT IN ({variant_words_sql});")
        sql_lines.append("")
        
        # Step 3: Insert clean word if it doesn't exist yet
        sql_lines.append(f"INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('{cleaned_word.replace("'", "''")}', {total_freq});")
        sql_lines.append("")
        
        # Step 4: Delete punctuation variants from word_frequencies
        sql_lines.append(f"-- Delete {len(variant_words)} punctuation variants")
        for variant_word in variant_words:
            sql_lines.append(f"DELETE FROM word_frequencies WHERE pashto_word = '{variant_word.replace("'", "''")}';")
        
        sql_lines.append("")
        merged_count += 1
        deleted_count += len(variant_words)
    
    sql_lines.append("COMMIT;")
    
    # Write SQL file
    sql_path = 'cloudflare/merge-punctuation-variants.sql'
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\n{'='*60}")
    print(f"✅ Generated SQL file: {sql_path}")
    print(f"\nSummary:")
    print(f"  - Found {len(variants)} word groups with punctuation variants")
    print(f"  - Will merge {merged_count} groups")
    print(f"  - Will update word_verse_mapping for {deleted_count} punctuation variants")
    print(f"  - Will delete {deleted_count} punctuation variant entries from word_frequencies")
    print(f"\nNext steps:")
    print(f"  1. Review {sql_path}")
    print(f"  2. Run: wrangler d1 execute pashto-bible-db --remote --file {sql_path}")

if __name__ == '__main__':
    main()

