#!/usr/bin/env python3
"""
Split words with embedded punctuation into separate words.
For example: 'استاذه، ته' should become 'استاذه' and 'ته'
"""

import json
import re
import subprocess
from collections import defaultdict

PUNCTUATION = ['،', '«', '»', '.', ',', '!', '?', ':', ';', '(', ')', '[', ']', '{', '}', '"', "'", '`', '"', '"', ''', ''', '›', '‹', '•', '-', '–', '—', '\u200c']

def has_embedded_punctuation(word):
    """Check if word has punctuation in the middle (not just at ends)"""
    if not word or len(word) < 2:
        return False
    
    # Check if there's punctuation that's not at the very start or end
    for i in range(1, len(word) - 1):
        if word[i] in PUNCTUATION:
            return True
    return False

def clean_part(part):
    """Remove trailing/leading punctuation from a part"""
    # Remove trailing punctuation
    while part and part[-1] in PUNCTUATION:
        part = part[:-1]
    # Remove leading punctuation
    while part and part[0] in PUNCTUATION:
        part = part[1:]
    return part.strip()

def split_at_punctuation(word):
    """Split word at punctuation boundaries, keeping Arabic/Persian characters together"""
    # Split on punctuation but keep multiple punctuation marks together
    parts = re.split(r'[' + re.escape(''.join(PUNCTUATION)) + r'\s]+', word)
    # Clean each part and filter out empty/whitespace-only/punctuation-only parts
    filtered = []
    for p in parts:
        cleaned = clean_part(p)
        # Only keep parts that contain at least one character that is NOT punctuation and NOT whitespace
        if cleaned and any(c not in PUNCTUATION and not c.isspace() for c in cleaned):
            filtered.append(cleaned)
    return filtered

def main():
    print("🔧 Splitting words with embedded punctuation into separate words...\n")
    print("="*60)
    
    # Query for words with punctuation
    print("Querying database for words with punctuation...")
    result = subprocess.run(
        ['wrangler', 'd1', 'execute', 'pashto-bible-db', '--remote', '--command',
         "SELECT pashto_word, frequency_total FROM word_frequencies WHERE pashto_word LIKE '%.%' OR pashto_word LIKE '%،%' OR pashto_word LIKE '%!%' OR pashto_word LIKE '%?%' ORDER BY frequency_total DESC"],
        capture_output=True,
        text=True
    )
    
    if result.returncode != 0:
        print(f"Error querying database: {result.stderr}")
        return
    
    # Parse JSON output
    try:
        lines = result.stdout.strip().split('\n')
        json_start = -1
        for i, line in enumerate(lines):
            if line.strip().startswith('['):
                json_start = i
                break
        
        if json_start == -1:
            print("No JSON data found")
            return
        
        json_str = '\n'.join(lines[json_start:])
        data = json.loads(json_str)
        
        if not data or 'results' not in data[0]:
            print("No results found")
            return
        
        entries = data[0]['results']
        print(f"Found {len(entries)} words with punctuation\n")
        
    except Exception as e:
        print(f"Error parsing output: {e}")
        return
    
    # Find words with embedded punctuation
    embedded_words = []
    for entry in entries:
        word = entry.get('pashto_word', '')
        if has_embedded_punctuation(word):
            parts = split_at_punctuation(word)
            if len(parts) > 1:  # Only if we can split into multiple parts
                embedded_words.append({
                    'original': word,
                    'parts': parts,
                    'frequency': entry.get('frequency_total', 0)
                })
    
    print(f"Found {len(embedded_words)} words with embedded punctuation to split\n")
    
    if not embedded_words:
        print("No words with embedded punctuation found!")
        return
    
    # Generate SQL
    sql_lines = [
        "-- Split words with embedded punctuation into separate words",
        "-- Generated by split-embedded-punctuation.py",
        "-- Example: 'استاذه، ته' becomes 'استاذه' and 'ته'",
        "",
    ]
    
    split_count = 0
    total_parts = 0
    
    for item in sorted(embedded_words, key=lambda x: -x['frequency']):
        original = item['original']
        parts = item['parts']
        freq = item['frequency']
        
        # Filter out any parts that are only punctuation (safety check)
        parts = [p for p in parts if p and any(c not in PUNCTUATION and not c.isspace() for c in p)]
        
        if len(parts) < 2:  # Skip if we don't have at least 2 valid parts
            continue
        
        sql_lines.append(f"-- Split '{original}' ({freq} occurrences) into: {', '.join(parts)}")
        sql_lines.append("")
        
        # Step 1: Insert remaining parts into word_verse_mapping BEFORE updating original
        # This way we preserve all verse mappings for the original word
        for i, part in enumerate(parts[1:], 1):
            sql_lines.append(f"-- Insert '{part}' into word_verse_mapping for same verses as '{original}'")
            sql_lines.append(f"INSERT INTO word_verse_mapping (pashto_word, verse_id, verse_ref, translation_key, testament, book, chapter, verse, word_position, base_form)")
            sql_lines.append(f"SELECT '{part.replace("'", "''")}', verse_id, verse_ref, translation_key, testament, book, chapter, verse, word_position, base_form")
            sql_lines.append(f"FROM word_verse_mapping")
            sql_lines.append(f"WHERE pashto_word = '{original.replace("'", "''")}'")
            sql_lines.append(f"  AND NOT EXISTS (")
            sql_lines.append(f"    SELECT 1 FROM word_verse_mapping wvm2")
            sql_lines.append(f"    WHERE wvm2.pashto_word = '{part.replace("'", "''")}'")
            sql_lines.append(f"      AND wvm2.verse_id = word_verse_mapping.verse_id")
            sql_lines.append(f"  );")
            sql_lines.append("")
        
        # Step 2: Update original to first part (after inserting other parts)
        sql_lines.append(f"-- Step 2: Update original to first part")
        sql_lines.append(f"UPDATE word_verse_mapping SET pashto_word = '{parts[0].replace("'", "''")}' WHERE pashto_word = '{original.replace("'", "''")}';")
        sql_lines.append("")
        
        # Step 3: Update word_frequencies
        # Delete the original combined word
        sql_lines.append(f"-- Delete original combined word from word_frequencies")
        sql_lines.append(f"DELETE FROM word_frequencies WHERE pashto_word = '{original.replace("'", "''")}';")
        sql_lines.append("")
        
        # Step 4: Ensure each part exists in word_frequencies
        # Each part gets the full frequency since they appear together in the same verses
        # But we need to avoid double-counting if parts already exist separately
        # So we'll add the frequency to each part, but only if it doesn't already have more
        for part in parts:
            sql_lines.append(f"-- Ensure '{part}' exists in word_frequencies")
            sql_lines.append(f"INSERT OR IGNORE INTO word_frequencies (pashto_word, frequency_total) VALUES ('{part.replace("'", "''")}', 0);")
            sql_lines.append(f"-- Add frequency to '{part}' (each part appears in all verses where original appeared)")
            sql_lines.append(f"UPDATE word_frequencies SET frequency_total = frequency_total + {freq} WHERE pashto_word = '{part.replace("'", "''")}';")
        
        sql_lines.append("")
        split_count += 1
        total_parts += len(parts)
    
    # Write SQL file
    sql_path = 'cloudflare/split-embedded-punctuation.sql'
    with open(sql_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql_lines))
    
    print(f"\n{'='*60}")
    print(f"✅ Generated SQL file: {sql_path}")
    print(f"\nSummary:")
    print(f"  - Found {len(embedded_words)} words with embedded punctuation")
    print(f"  - Will split into {total_parts} separate words")
    print(f"  - Will update word_verse_mapping for {split_count} entries")
    print(f"\nNext steps:")
    print(f"  1. Review {sql_path}")
    print(f"  2. Run: wrangler d1 execute pashto-bible-db --remote --file {sql_path}")

if __name__ == '__main__':
    main()

